// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.
// This file contains parsers for the accounts defined in the IDL.

package lsd_program

import (
	"fmt"
	binary "github.com/gagliardetto/binary"
)

func ParseAnyAccount(accountData []byte) (any, error) {
	decoder := binary.NewBorshDecoder(accountData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek account discriminator: %w", err)
	}
	switch discriminator {
	case Account_Stack:
		value := new(Stack)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal account as Stack: %w", err)
		}
		return value, nil
	case Account_StakeManager:
		value := new(StakeManager)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal account as StakeManager: %w", err)
		}
		return value, nil
	case Account_UnstakeAccount:
		value := new(UnstakeAccount)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal account as UnstakeAccount: %w", err)
		}
		return value, nil
	case Account_StackFeeAccount:
		value := new(StackFeeAccount)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal account as StackFeeAccount: %w", err)
		}
		return value, nil
	default:
		return nil, fmt.Errorf("unknown discriminator: %s", binary.FormatDiscriminator(discriminator))
	}
}

func ParseAccount_Stack(accountData []byte) (*Stack, error) {
	decoder := binary.NewBorshDecoder(accountData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Account_Stack {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Account_Stack, binary.FormatDiscriminator(discriminator))
	}
	acc := new(Stack)
	err = acc.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal account of type Stack: %w", err)
	}
	return acc, nil
}

func ParseAccount_StakeManager(accountData []byte) (*StakeManager, error) {
	decoder := binary.NewBorshDecoder(accountData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Account_StakeManager {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Account_StakeManager, binary.FormatDiscriminator(discriminator))
	}
	acc := new(StakeManager)
	err = acc.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal account of type StakeManager: %w", err)
	}
	return acc, nil
}

func ParseAccount_UnstakeAccount(accountData []byte) (*UnstakeAccount, error) {
	decoder := binary.NewBorshDecoder(accountData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Account_UnstakeAccount {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Account_UnstakeAccount, binary.FormatDiscriminator(discriminator))
	}
	acc := new(UnstakeAccount)
	err = acc.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal account of type UnstakeAccount: %w", err)
	}
	return acc, nil
}

func ParseAccount_StackFeeAccount(accountData []byte) (*StackFeeAccount, error) {
	decoder := binary.NewBorshDecoder(accountData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Account_StackFeeAccount {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Account_StackFeeAccount, binary.FormatDiscriminator(discriminator))
	}
	acc := new(StackFeeAccount)
	err = acc.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal account of type StackFeeAccount: %w", err)
	}
	return acc, nil
}
