// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package lsd_program

import (
	"fmt"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
)

type Stack struct {
	Admin                  ag_solanago.PublicKey
	StackFeeCommission     uint64
	StakeManagersLenLimit  uint64
	EntrustedStakeManagers []ag_solanago.PublicKey
}

var StackDiscriminator = [8]byte{58, 70, 168, 244, 188, 169, 129, 79}

func (obj Stack) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Write account discriminator:
	err = encoder.WriteBytes(StackDiscriminator[:], false)
	if err != nil {
		return err
	}
	// Serialize `Admin` param:
	err = encoder.Encode(obj.Admin)
	if err != nil {
		return err
	}
	// Serialize `StackFeeCommission` param:
	err = encoder.Encode(obj.StackFeeCommission)
	if err != nil {
		return err
	}
	// Serialize `StakeManagersLenLimit` param:
	err = encoder.Encode(obj.StakeManagersLenLimit)
	if err != nil {
		return err
	}
	// Serialize `EntrustedStakeManagers` param:
	err = encoder.Encode(obj.EntrustedStakeManagers)
	if err != nil {
		return err
	}
	return nil
}

func (obj *Stack) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Read and check account discriminator:
	{
		discriminator, err := decoder.ReadTypeID()
		if err != nil {
			return err
		}
		if !discriminator.Equal(StackDiscriminator[:]) {
			return fmt.Errorf(
				"wrong discriminator: wanted %s, got %s",
				"[58 70 168 244 188 169 129 79]",
				fmt.Sprint(discriminator[:]))
		}
	}
	// Deserialize `Admin`:
	err = decoder.Decode(&obj.Admin)
	if err != nil {
		return err
	}
	// Deserialize `StackFeeCommission`:
	err = decoder.Decode(&obj.StackFeeCommission)
	if err != nil {
		return err
	}
	// Deserialize `StakeManagersLenLimit`:
	err = decoder.Decode(&obj.StakeManagersLenLimit)
	if err != nil {
		return err
	}
	// Deserialize `EntrustedStakeManagers`:
	err = decoder.Decode(&obj.EntrustedStakeManagers)
	if err != nil {
		return err
	}
	return nil
}

type StakeManager struct {
	Admin                 ag_solanago.PublicKey
	Balancer              ag_solanago.PublicKey
	Stack                 ag_solanago.PublicKey
	LsdTokenMint          ag_solanago.PublicKey
	PoolSeedBump          uint8
	RentExemptForPoolAcc  uint64
	MinStakeAmount        uint64
	PlatformFeeCommission uint64
	StackFeeCommission    uint64
	RateChangeLimit       uint64
	StakeAccountsLenLimit uint64
	SplitAccountsLenLimit uint64
	UnbondingDuration     uint64
	LatestEra             uint64
	Rate                  uint64
	EraBond               uint64
	EraUnbond             uint64
	Active                uint64
	TotalPlatformFee      uint64
	Validators            []ag_solanago.PublicKey
	StakeAccounts         []ag_solanago.PublicKey
	SplitAccounts         []ag_solanago.PublicKey
	EraRates              []EraRate
	EraProcessData        EraProcessData
}

var StakeManagerDiscriminator = [8]byte{205, 143, 54, 235, 240, 28, 104, 211}

func (obj StakeManager) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Write account discriminator:
	err = encoder.WriteBytes(StakeManagerDiscriminator[:], false)
	if err != nil {
		return err
	}
	// Serialize `Admin` param:
	err = encoder.Encode(obj.Admin)
	if err != nil {
		return err
	}
	// Serialize `Balancer` param:
	err = encoder.Encode(obj.Balancer)
	if err != nil {
		return err
	}
	// Serialize `Stack` param:
	err = encoder.Encode(obj.Stack)
	if err != nil {
		return err
	}
	// Serialize `LsdTokenMint` param:
	err = encoder.Encode(obj.LsdTokenMint)
	if err != nil {
		return err
	}
	// Serialize `PoolSeedBump` param:
	err = encoder.Encode(obj.PoolSeedBump)
	if err != nil {
		return err
	}
	// Serialize `RentExemptForPoolAcc` param:
	err = encoder.Encode(obj.RentExemptForPoolAcc)
	if err != nil {
		return err
	}
	// Serialize `MinStakeAmount` param:
	err = encoder.Encode(obj.MinStakeAmount)
	if err != nil {
		return err
	}
	// Serialize `PlatformFeeCommission` param:
	err = encoder.Encode(obj.PlatformFeeCommission)
	if err != nil {
		return err
	}
	// Serialize `StackFeeCommission` param:
	err = encoder.Encode(obj.StackFeeCommission)
	if err != nil {
		return err
	}
	// Serialize `RateChangeLimit` param:
	err = encoder.Encode(obj.RateChangeLimit)
	if err != nil {
		return err
	}
	// Serialize `StakeAccountsLenLimit` param:
	err = encoder.Encode(obj.StakeAccountsLenLimit)
	if err != nil {
		return err
	}
	// Serialize `SplitAccountsLenLimit` param:
	err = encoder.Encode(obj.SplitAccountsLenLimit)
	if err != nil {
		return err
	}
	// Serialize `UnbondingDuration` param:
	err = encoder.Encode(obj.UnbondingDuration)
	if err != nil {
		return err
	}
	// Serialize `LatestEra` param:
	err = encoder.Encode(obj.LatestEra)
	if err != nil {
		return err
	}
	// Serialize `Rate` param:
	err = encoder.Encode(obj.Rate)
	if err != nil {
		return err
	}
	// Serialize `EraBond` param:
	err = encoder.Encode(obj.EraBond)
	if err != nil {
		return err
	}
	// Serialize `EraUnbond` param:
	err = encoder.Encode(obj.EraUnbond)
	if err != nil {
		return err
	}
	// Serialize `Active` param:
	err = encoder.Encode(obj.Active)
	if err != nil {
		return err
	}
	// Serialize `TotalPlatformFee` param:
	err = encoder.Encode(obj.TotalPlatformFee)
	if err != nil {
		return err
	}
	// Serialize `Validators` param:
	err = encoder.Encode(obj.Validators)
	if err != nil {
		return err
	}
	// Serialize `StakeAccounts` param:
	err = encoder.Encode(obj.StakeAccounts)
	if err != nil {
		return err
	}
	// Serialize `SplitAccounts` param:
	err = encoder.Encode(obj.SplitAccounts)
	if err != nil {
		return err
	}
	// Serialize `EraRates` param:
	err = encoder.Encode(obj.EraRates)
	if err != nil {
		return err
	}
	// Serialize `EraProcessData` param:
	err = encoder.Encode(obj.EraProcessData)
	if err != nil {
		return err
	}
	return nil
}

func (obj *StakeManager) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Read and check account discriminator:
	{
		discriminator, err := decoder.ReadTypeID()
		if err != nil {
			return err
		}
		if !discriminator.Equal(StakeManagerDiscriminator[:]) {
			return fmt.Errorf(
				"wrong discriminator: wanted %s, got %s",
				"[205 143 54 235 240 28 104 211]",
				fmt.Sprint(discriminator[:]))
		}
	}
	// Deserialize `Admin`:
	err = decoder.Decode(&obj.Admin)
	if err != nil {
		return err
	}
	// Deserialize `Balancer`:
	err = decoder.Decode(&obj.Balancer)
	if err != nil {
		return err
	}
	// Deserialize `Stack`:
	err = decoder.Decode(&obj.Stack)
	if err != nil {
		return err
	}
	// Deserialize `LsdTokenMint`:
	err = decoder.Decode(&obj.LsdTokenMint)
	if err != nil {
		return err
	}
	// Deserialize `PoolSeedBump`:
	err = decoder.Decode(&obj.PoolSeedBump)
	if err != nil {
		return err
	}
	// Deserialize `RentExemptForPoolAcc`:
	err = decoder.Decode(&obj.RentExemptForPoolAcc)
	if err != nil {
		return err
	}
	// Deserialize `MinStakeAmount`:
	err = decoder.Decode(&obj.MinStakeAmount)
	if err != nil {
		return err
	}
	// Deserialize `PlatformFeeCommission`:
	err = decoder.Decode(&obj.PlatformFeeCommission)
	if err != nil {
		return err
	}
	// Deserialize `StackFeeCommission`:
	err = decoder.Decode(&obj.StackFeeCommission)
	if err != nil {
		return err
	}
	// Deserialize `RateChangeLimit`:
	err = decoder.Decode(&obj.RateChangeLimit)
	if err != nil {
		return err
	}
	// Deserialize `StakeAccountsLenLimit`:
	err = decoder.Decode(&obj.StakeAccountsLenLimit)
	if err != nil {
		return err
	}
	// Deserialize `SplitAccountsLenLimit`:
	err = decoder.Decode(&obj.SplitAccountsLenLimit)
	if err != nil {
		return err
	}
	// Deserialize `UnbondingDuration`:
	err = decoder.Decode(&obj.UnbondingDuration)
	if err != nil {
		return err
	}
	// Deserialize `LatestEra`:
	err = decoder.Decode(&obj.LatestEra)
	if err != nil {
		return err
	}
	// Deserialize `Rate`:
	err = decoder.Decode(&obj.Rate)
	if err != nil {
		return err
	}
	// Deserialize `EraBond`:
	err = decoder.Decode(&obj.EraBond)
	if err != nil {
		return err
	}
	// Deserialize `EraUnbond`:
	err = decoder.Decode(&obj.EraUnbond)
	if err != nil {
		return err
	}
	// Deserialize `Active`:
	err = decoder.Decode(&obj.Active)
	if err != nil {
		return err
	}
	// Deserialize `TotalPlatformFee`:
	err = decoder.Decode(&obj.TotalPlatformFee)
	if err != nil {
		return err
	}
	// Deserialize `Validators`:
	err = decoder.Decode(&obj.Validators)
	if err != nil {
		return err
	}
	// Deserialize `StakeAccounts`:
	err = decoder.Decode(&obj.StakeAccounts)
	if err != nil {
		return err
	}
	// Deserialize `SplitAccounts`:
	err = decoder.Decode(&obj.SplitAccounts)
	if err != nil {
		return err
	}
	// Deserialize `EraRates`:
	err = decoder.Decode(&obj.EraRates)
	if err != nil {
		return err
	}
	// Deserialize `EraProcessData`:
	err = decoder.Decode(&obj.EraProcessData)
	if err != nil {
		return err
	}
	return nil
}

type UnstakeAccount struct {
	StakeManager ag_solanago.PublicKey
	Recipient    ag_solanago.PublicKey
	Amount       uint64
	CreatedEpoch uint64
}

var UnstakeAccountDiscriminator = [8]byte{45, 203, 242, 225, 172, 87, 112, 71}

func (obj UnstakeAccount) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Write account discriminator:
	err = encoder.WriteBytes(UnstakeAccountDiscriminator[:], false)
	if err != nil {
		return err
	}
	// Serialize `StakeManager` param:
	err = encoder.Encode(obj.StakeManager)
	if err != nil {
		return err
	}
	// Serialize `Recipient` param:
	err = encoder.Encode(obj.Recipient)
	if err != nil {
		return err
	}
	// Serialize `Amount` param:
	err = encoder.Encode(obj.Amount)
	if err != nil {
		return err
	}
	// Serialize `CreatedEpoch` param:
	err = encoder.Encode(obj.CreatedEpoch)
	if err != nil {
		return err
	}
	return nil
}

func (obj *UnstakeAccount) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Read and check account discriminator:
	{
		discriminator, err := decoder.ReadTypeID()
		if err != nil {
			return err
		}
		if !discriminator.Equal(UnstakeAccountDiscriminator[:]) {
			return fmt.Errorf(
				"wrong discriminator: wanted %s, got %s",
				"[45 203 242 225 172 87 112 71]",
				fmt.Sprint(discriminator[:]))
		}
	}
	// Deserialize `StakeManager`:
	err = decoder.Decode(&obj.StakeManager)
	if err != nil {
		return err
	}
	// Deserialize `Recipient`:
	err = decoder.Decode(&obj.Recipient)
	if err != nil {
		return err
	}
	// Deserialize `Amount`:
	err = decoder.Decode(&obj.Amount)
	if err != nil {
		return err
	}
	// Deserialize `CreatedEpoch`:
	err = decoder.Decode(&obj.CreatedEpoch)
	if err != nil {
		return err
	}
	return nil
}

type StackFeeAccount struct {
	Bump   uint8
	Amount uint64
}

var StackFeeAccountDiscriminator = [8]byte{76, 201, 86, 252, 221, 169, 67, 99}

func (obj StackFeeAccount) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Write account discriminator:
	err = encoder.WriteBytes(StackFeeAccountDiscriminator[:], false)
	if err != nil {
		return err
	}
	// Serialize `Bump` param:
	err = encoder.Encode(obj.Bump)
	if err != nil {
		return err
	}
	// Serialize `Amount` param:
	err = encoder.Encode(obj.Amount)
	if err != nil {
		return err
	}
	return nil
}

func (obj *StackFeeAccount) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Read and check account discriminator:
	{
		discriminator, err := decoder.ReadTypeID()
		if err != nil {
			return err
		}
		if !discriminator.Equal(StackFeeAccountDiscriminator[:]) {
			return fmt.Errorf(
				"wrong discriminator: wanted %s, got %s",
				"[76 201 86 252 221 169 67 99]",
				fmt.Sprint(discriminator[:]))
		}
	}
	// Deserialize `Bump`:
	err = decoder.Decode(&obj.Bump)
	if err != nil {
		return err
	}
	// Deserialize `Amount`:
	err = decoder.Decode(&obj.Amount)
	if err != nil {
		return err
	}
	return nil
}
