// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package lsd_program

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// AddValidator is the `addValidator` instruction.
type AddValidator struct {
	NewValidator *ag_solanago.PublicKey

	// [0] = [WRITE] stakeManager
	//
	// [1] = [SIGNER] admin
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewAddValidatorInstructionBuilder creates a new `AddValidator` instruction builder.
func NewAddValidatorInstructionBuilder() *AddValidator {
	nd := &AddValidator{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 2),
	}
	return nd
}

// SetNewValidator sets the "newValidator" parameter.
func (inst *AddValidator) SetNewValidator(newValidator ag_solanago.PublicKey) *AddValidator {
	inst.NewValidator = &newValidator
	return inst
}

// SetStakeManagerAccount sets the "stakeManager" account.
func (inst *AddValidator) SetStakeManagerAccount(stakeManager ag_solanago.PublicKey) *AddValidator {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(stakeManager).WRITE()
	return inst
}

// GetStakeManagerAccount gets the "stakeManager" account.
func (inst *AddValidator) GetStakeManagerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetAdminAccount sets the "admin" account.
func (inst *AddValidator) SetAdminAccount(admin ag_solanago.PublicKey) *AddValidator {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(admin).SIGNER()
	return inst
}

// GetAdminAccount gets the "admin" account.
func (inst *AddValidator) GetAdminAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

func (inst AddValidator) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_AddValidator,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst AddValidator) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *AddValidator) Validate() error {
	// Check whether all (required) parameters are set:
	{
		if inst.NewValidator == nil {
			return errors.New("NewValidator parameter is not set")
		}
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.StakeManager is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.Admin is not set")
		}
	}
	return nil
}

func (inst *AddValidator) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("AddValidator")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=1]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param("NewValidator", *inst.NewValidator))
					})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=2]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("stakeManager", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("       admin", inst.AccountMetaSlice.Get(1)))
					})
				})
		})
}

func (obj AddValidator) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `NewValidator` param:
	err = encoder.Encode(obj.NewValidator)
	if err != nil {
		return err
	}
	return nil
}
func (obj *AddValidator) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `NewValidator`:
	err = decoder.Decode(&obj.NewValidator)
	if err != nil {
		return err
	}
	return nil
}

// NewAddValidatorInstruction declares a new AddValidator instruction with the provided parameters and accounts.
func NewAddValidatorInstruction(
	// Parameters:
	newValidator ag_solanago.PublicKey,
	// Accounts:
	stakeManager ag_solanago.PublicKey,
	admin ag_solanago.PublicKey) *AddValidator {
	return NewAddValidatorInstructionBuilder().
		SetNewValidator(newValidator).
		SetStakeManagerAccount(stakeManager).
		SetAdminAccount(admin)
}
