// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package lsd_program

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// CreateMetadataV1 is the `createMetadataV1` instruction.
type CreateMetadataV1 struct {
	Params *CreateMetadataParams

	// [0] = [WRITE, SIGNER] feeAndRentPayer
	//
	// [1] = [SIGNER] admin
	//
	// [2] = [WRITE] stakeManager
	//
	// [3] = [WRITE] stakePool
	//
	// [4] = [WRITE] lsdTokenMint
	//
	// [5] = [WRITE] metadataAccount
	//
	// [6] = [] metadataProgram
	//
	// [7] = [] systemProgram
	//
	// [8] = [] sysvarInstruction
	//
	// [9] = [] splTokenProgram
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewCreateMetadataV1InstructionBuilder creates a new `CreateMetadataV1` instruction builder.
func NewCreateMetadataV1InstructionBuilder() *CreateMetadataV1 {
	nd := &CreateMetadataV1{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 10),
	}
	return nd
}

// SetParams sets the "params" parameter.
func (inst *CreateMetadataV1) SetParams(params CreateMetadataParams) *CreateMetadataV1 {
	inst.Params = &params
	return inst
}

// SetFeeAndRentPayerAccount sets the "feeAndRentPayer" account.
func (inst *CreateMetadataV1) SetFeeAndRentPayerAccount(feeAndRentPayer ag_solanago.PublicKey) *CreateMetadataV1 {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(feeAndRentPayer).WRITE().SIGNER()
	return inst
}

// GetFeeAndRentPayerAccount gets the "feeAndRentPayer" account.
func (inst *CreateMetadataV1) GetFeeAndRentPayerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetAdminAccount sets the "admin" account.
func (inst *CreateMetadataV1) SetAdminAccount(admin ag_solanago.PublicKey) *CreateMetadataV1 {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(admin).SIGNER()
	return inst
}

// GetAdminAccount gets the "admin" account.
func (inst *CreateMetadataV1) GetAdminAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

// SetStakeManagerAccount sets the "stakeManager" account.
func (inst *CreateMetadataV1) SetStakeManagerAccount(stakeManager ag_solanago.PublicKey) *CreateMetadataV1 {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(stakeManager).WRITE()
	return inst
}

// GetStakeManagerAccount gets the "stakeManager" account.
func (inst *CreateMetadataV1) GetStakeManagerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(2)
}

// SetStakePoolAccount sets the "stakePool" account.
func (inst *CreateMetadataV1) SetStakePoolAccount(stakePool ag_solanago.PublicKey) *CreateMetadataV1 {
	inst.AccountMetaSlice[3] = ag_solanago.Meta(stakePool).WRITE()
	return inst
}

// GetStakePoolAccount gets the "stakePool" account.
func (inst *CreateMetadataV1) GetStakePoolAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(3)
}

// SetLsdTokenMintAccount sets the "lsdTokenMint" account.
func (inst *CreateMetadataV1) SetLsdTokenMintAccount(lsdTokenMint ag_solanago.PublicKey) *CreateMetadataV1 {
	inst.AccountMetaSlice[4] = ag_solanago.Meta(lsdTokenMint).WRITE()
	return inst
}

// GetLsdTokenMintAccount gets the "lsdTokenMint" account.
func (inst *CreateMetadataV1) GetLsdTokenMintAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(4)
}

// SetMetadataAccountAccount sets the "metadataAccount" account.
func (inst *CreateMetadataV1) SetMetadataAccountAccount(metadataAccount ag_solanago.PublicKey) *CreateMetadataV1 {
	inst.AccountMetaSlice[5] = ag_solanago.Meta(metadataAccount).WRITE()
	return inst
}

// GetMetadataAccountAccount gets the "metadataAccount" account.
func (inst *CreateMetadataV1) GetMetadataAccountAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(5)
}

// SetMetadataProgramAccount sets the "metadataProgram" account.
func (inst *CreateMetadataV1) SetMetadataProgramAccount(metadataProgram ag_solanago.PublicKey) *CreateMetadataV1 {
	inst.AccountMetaSlice[6] = ag_solanago.Meta(metadataProgram)
	return inst
}

// GetMetadataProgramAccount gets the "metadataProgram" account.
func (inst *CreateMetadataV1) GetMetadataProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(6)
}

// SetSystemProgramAccount sets the "systemProgram" account.
func (inst *CreateMetadataV1) SetSystemProgramAccount(systemProgram ag_solanago.PublicKey) *CreateMetadataV1 {
	inst.AccountMetaSlice[7] = ag_solanago.Meta(systemProgram)
	return inst
}

// GetSystemProgramAccount gets the "systemProgram" account.
func (inst *CreateMetadataV1) GetSystemProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(7)
}

// SetSysvarInstructionAccount sets the "sysvarInstruction" account.
func (inst *CreateMetadataV1) SetSysvarInstructionAccount(sysvarInstruction ag_solanago.PublicKey) *CreateMetadataV1 {
	inst.AccountMetaSlice[8] = ag_solanago.Meta(sysvarInstruction)
	return inst
}

// GetSysvarInstructionAccount gets the "sysvarInstruction" account.
func (inst *CreateMetadataV1) GetSysvarInstructionAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(8)
}

// SetSplTokenProgramAccount sets the "splTokenProgram" account.
func (inst *CreateMetadataV1) SetSplTokenProgramAccount(splTokenProgram ag_solanago.PublicKey) *CreateMetadataV1 {
	inst.AccountMetaSlice[9] = ag_solanago.Meta(splTokenProgram)
	return inst
}

// GetSplTokenProgramAccount gets the "splTokenProgram" account.
func (inst *CreateMetadataV1) GetSplTokenProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(9)
}

func (inst CreateMetadataV1) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_CreateMetadataV1,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst CreateMetadataV1) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *CreateMetadataV1) Validate() error {
	// Check whether all (required) parameters are set:
	{
		if inst.Params == nil {
			return errors.New("Params parameter is not set")
		}
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.FeeAndRentPayer is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.Admin is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.StakeManager is not set")
		}
		if inst.AccountMetaSlice[3] == nil {
			return errors.New("accounts.StakePool is not set")
		}
		if inst.AccountMetaSlice[4] == nil {
			return errors.New("accounts.LsdTokenMint is not set")
		}
		if inst.AccountMetaSlice[5] == nil {
			return errors.New("accounts.MetadataAccount is not set")
		}
		if inst.AccountMetaSlice[6] == nil {
			return errors.New("accounts.MetadataProgram is not set")
		}
		if inst.AccountMetaSlice[7] == nil {
			return errors.New("accounts.SystemProgram is not set")
		}
		if inst.AccountMetaSlice[8] == nil {
			return errors.New("accounts.SysvarInstruction is not set")
		}
		if inst.AccountMetaSlice[9] == nil {
			return errors.New("accounts.SplTokenProgram is not set")
		}
	}
	return nil
}

func (inst *CreateMetadataV1) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("CreateMetadataV1")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=1]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param("Params", *inst.Params))
					})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=10]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("  feeAndRentPayer", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("            admin", inst.AccountMetaSlice.Get(1)))
						accountsBranch.Child(ag_format.Meta("     stakeManager", inst.AccountMetaSlice.Get(2)))
						accountsBranch.Child(ag_format.Meta("        stakePool", inst.AccountMetaSlice.Get(3)))
						accountsBranch.Child(ag_format.Meta("     lsdTokenMint", inst.AccountMetaSlice.Get(4)))
						accountsBranch.Child(ag_format.Meta("         metadata", inst.AccountMetaSlice.Get(5)))
						accountsBranch.Child(ag_format.Meta("  metadataProgram", inst.AccountMetaSlice.Get(6)))
						accountsBranch.Child(ag_format.Meta("    systemProgram", inst.AccountMetaSlice.Get(7)))
						accountsBranch.Child(ag_format.Meta("sysvarInstruction", inst.AccountMetaSlice.Get(8)))
						accountsBranch.Child(ag_format.Meta("  splTokenProgram", inst.AccountMetaSlice.Get(9)))
					})
				})
		})
}

func (obj CreateMetadataV1) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `Params` param:
	err = encoder.Encode(obj.Params)
	if err != nil {
		return err
	}
	return nil
}
func (obj *CreateMetadataV1) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `Params`:
	err = decoder.Decode(&obj.Params)
	if err != nil {
		return err
	}
	return nil
}

// NewCreateMetadataV1Instruction declares a new CreateMetadataV1 instruction with the provided parameters and accounts.
func NewCreateMetadataV1Instruction(
	// Parameters:
	params CreateMetadataParams,
	// Accounts:
	feeAndRentPayer ag_solanago.PublicKey,
	admin ag_solanago.PublicKey,
	stakeManager ag_solanago.PublicKey,
	stakePool ag_solanago.PublicKey,
	lsdTokenMint ag_solanago.PublicKey,
	metadataAccount ag_solanago.PublicKey,
	metadataProgram ag_solanago.PublicKey,
	systemProgram ag_solanago.PublicKey,
	sysvarInstruction ag_solanago.PublicKey,
	splTokenProgram ag_solanago.PublicKey) *CreateMetadataV1 {
	return NewCreateMetadataV1InstructionBuilder().
		SetParams(params).
		SetFeeAndRentPayerAccount(feeAndRentPayer).
		SetAdminAccount(admin).
		SetStakeManagerAccount(stakeManager).
		SetStakePoolAccount(stakePool).
		SetLsdTokenMintAccount(lsdTokenMint).
		SetMetadataAccountAccount(metadataAccount).
		SetMetadataProgramAccount(metadataProgram).
		SetSystemProgramAccount(systemProgram).
		SetSysvarInstructionAccount(sysvarInstruction).
		SetSplTokenProgramAccount(splTokenProgram)
}
