// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.
// This file contains the discriminators for accounts and events defined in the IDL.

package lsd_program

// Account discriminators
var (
	Account_Stack           = [8]byte{58, 70, 168, 244, 188, 169, 129, 79}
	Account_StakeManager    = [8]byte{205, 143, 54, 235, 240, 28, 104, 211}
	Account_UnstakeAccount  = [8]byte{45, 203, 242, 225, 172, 87, 112, 71}
	Account_StackFeeAccount = [8]byte{76, 201, 86, 252, 221, 169, 67, 99}
)

// Event discriminators
var (
	Event_EventEraBond         = [8]byte{201, 184, 165, 183, 119, 31, 13, 45}
	Event_EventEraMerge        = [8]byte{214, 23, 6, 241, 108, 236, 45, 255}
	Event_EventEraNew          = [8]byte{136, 194, 142, 92, 250, 156, 169, 205}
	Event_EventEraSkipBond     = [8]byte{151, 9, 57, 217, 134, 146, 239, 62}
	Event_EventEraUnbond       = [8]byte{143, 241, 61, 122, 199, 237, 39, 69}
	Event_EventEraUpdateActive = [8]byte{48, 177, 221, 77, 44, 227, 41, 27}
	Event_EventEraUpdateRate   = [8]byte{85, 102, 224, 204, 12, 121, 241, 252}
	Event_EventEraWithdraw     = [8]byte{185, 4, 129, 162, 74, 189, 5, 141}
	Event_EventRedelegate      = [8]byte{213, 89, 235, 90, 33, 141, 34, 65}
	Event_EventStake           = [8]byte{193, 220, 225, 33, 201, 27, 61, 43}
	Event_EventUnstake         = [8]byte{7, 14, 248, 129, 43, 55, 41, 104}
	Event_EventWithdraw        = [8]byte{216, 247, 255, 93, 80, 238, 33, 136}
)

// Instruction discriminators
var (
	Instruction_InitializeStack               = [8]byte{139, 248, 249, 177, 239, 66, 51, 252}
	Instruction_InitializeStakeManager        = [8]byte{75, 220, 4, 110, 166, 194, 173, 1}
	Instruction_TransferStackAdmin            = [8]byte{239, 183, 112, 103, 100, 99, 128, 84}
	Instruction_SetStackFeeCommission         = [8]byte{170, 16, 193, 90, 33, 62, 62, 97}
	Instruction_SetPlatformStackFeeCommission = [8]byte{85, 251, 61, 253, 7, 73, 13, 178}
	Instruction_AddEntrustedStakeManager      = [8]byte{81, 65, 28, 165, 239, 10, 152, 193}
	Instruction_RemoveEntrustedStakeManager   = [8]byte{232, 175, 69, 153, 85, 181, 33, 160}
	Instruction_TransferStakeManagerAdmin     = [8]byte{225, 28, 79, 223, 28, 96, 210, 226}
	Instruction_TransferBalancer              = [8]byte{99, 139, 245, 206, 226, 124, 106, 83}
	Instruction_SetMinStakeAmount             = [8]byte{30, 179, 162, 249, 158, 57, 14, 254}
	Instruction_SetUnbondingDuration          = [8]byte{143, 183, 204, 237, 156, 203, 133, 250}
	Instruction_SetRateChangeLimit            = [8]byte{13, 141, 180, 253, 190, 210, 229, 210}
	Instruction_SetPlatformFeeCommission      = [8]byte{193, 162, 133, 226, 38, 87, 16, 252}
	Instruction_AddValidator                  = [8]byte{250, 113, 53, 54, 141, 117, 215, 185}
	Instruction_RemoveValidator               = [8]byte{25, 96, 211, 155, 161, 14, 168, 188}
	Instruction_ReallocStakeManager           = [8]byte{124, 76, 19, 251, 234, 127, 12, 141}
	Instruction_Redelegate                    = [8]byte{212, 82, 51, 160, 228, 80, 116, 35}
	Instruction_Stake                         = [8]byte{206, 176, 202, 18, 200, 209, 179, 108}
	Instruction_Unstake                       = [8]byte{90, 95, 107, 42, 205, 124, 50, 225}
	Instruction_Withdraw                      = [8]byte{183, 18, 70, 156, 148, 109, 161, 34}
	Instruction_EraNew                        = [8]byte{96, 178, 91, 52, 66, 223, 134, 98}
	Instruction_EraBond                       = [8]byte{44, 238, 86, 188, 197, 69, 241, 91}
	Instruction_EraSkipBond                   = [8]byte{191, 75, 28, 113, 210, 201, 136, 19}
	Instruction_EraUnbond                     = [8]byte{193, 62, 151, 104, 91, 68, 92, 148}
	Instruction_EraUpdateActive               = [8]byte{185, 133, 175, 129, 26, 151, 115, 218}
	Instruction_EraUpdateRate                 = [8]byte{223, 55, 230, 209, 252, 154, 227, 116}
	Instruction_EraMerge                      = [8]byte{174, 80, 147, 234, 24, 233, 211, 195}
	Instruction_EraWithdraw                   = [8]byte{92, 3, 86, 172, 211, 111, 176, 238}
)
