// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package lsd_program

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// EraBond is the `eraBond` instruction.
type EraBond struct {

	// [0] = [WRITE] stakeManager
	//
	// [1] = [WRITE] validator
	//
	// [2] = [WRITE] stakePool
	//
	// [3] = [WRITE, SIGNER] stakeAccount
	//
	// [4] = [WRITE, SIGNER] rentPayer
	//
	// [5] = [] clock
	//
	// [6] = [] rent
	//
	// [7] = [] stakeConfig
	//
	// [8] = [] stakeHistory
	//
	// [9] = [] stakeProgram
	//
	// [10] = [] systemProgram
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewEraBondInstructionBuilder creates a new `EraBond` instruction builder.
func NewEraBondInstructionBuilder() *EraBond {
	nd := &EraBond{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 11),
	}
	return nd
}

// SetStakeManagerAccount sets the "stakeManager" account.
func (inst *EraBond) SetStakeManagerAccount(stakeManager ag_solanago.PublicKey) *EraBond {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(stakeManager).WRITE()
	return inst
}

// GetStakeManagerAccount gets the "stakeManager" account.
func (inst *EraBond) GetStakeManagerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetValidatorAccount sets the "validator" account.
func (inst *EraBond) SetValidatorAccount(validator ag_solanago.PublicKey) *EraBond {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(validator).WRITE()
	return inst
}

// GetValidatorAccount gets the "validator" account.
func (inst *EraBond) GetValidatorAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

// SetStakePoolAccount sets the "stakePool" account.
func (inst *EraBond) SetStakePoolAccount(stakePool ag_solanago.PublicKey) *EraBond {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(stakePool).WRITE()
	return inst
}

// GetStakePoolAccount gets the "stakePool" account.
func (inst *EraBond) GetStakePoolAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(2)
}

// SetStakeAccountAccount sets the "stakeAccount" account.
func (inst *EraBond) SetStakeAccountAccount(stakeAccount ag_solanago.PublicKey) *EraBond {
	inst.AccountMetaSlice[3] = ag_solanago.Meta(stakeAccount).WRITE().SIGNER()
	return inst
}

// GetStakeAccountAccount gets the "stakeAccount" account.
func (inst *EraBond) GetStakeAccountAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(3)
}

// SetRentPayerAccount sets the "rentPayer" account.
func (inst *EraBond) SetRentPayerAccount(rentPayer ag_solanago.PublicKey) *EraBond {
	inst.AccountMetaSlice[4] = ag_solanago.Meta(rentPayer).WRITE().SIGNER()
	return inst
}

// GetRentPayerAccount gets the "rentPayer" account.
func (inst *EraBond) GetRentPayerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(4)
}

// SetClockAccount sets the "clock" account.
func (inst *EraBond) SetClockAccount(clock ag_solanago.PublicKey) *EraBond {
	inst.AccountMetaSlice[5] = ag_solanago.Meta(clock)
	return inst
}

// GetClockAccount gets the "clock" account.
func (inst *EraBond) GetClockAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(5)
}

// SetRentAccount sets the "rent" account.
func (inst *EraBond) SetRentAccount(rent ag_solanago.PublicKey) *EraBond {
	inst.AccountMetaSlice[6] = ag_solanago.Meta(rent)
	return inst
}

// GetRentAccount gets the "rent" account.
func (inst *EraBond) GetRentAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(6)
}

// SetStakeConfigAccount sets the "stakeConfig" account.
func (inst *EraBond) SetStakeConfigAccount(stakeConfig ag_solanago.PublicKey) *EraBond {
	inst.AccountMetaSlice[7] = ag_solanago.Meta(stakeConfig)
	return inst
}

// GetStakeConfigAccount gets the "stakeConfig" account.
func (inst *EraBond) GetStakeConfigAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(7)
}

// SetStakeHistoryAccount sets the "stakeHistory" account.
func (inst *EraBond) SetStakeHistoryAccount(stakeHistory ag_solanago.PublicKey) *EraBond {
	inst.AccountMetaSlice[8] = ag_solanago.Meta(stakeHistory)
	return inst
}

// GetStakeHistoryAccount gets the "stakeHistory" account.
func (inst *EraBond) GetStakeHistoryAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(8)
}

// SetStakeProgramAccount sets the "stakeProgram" account.
func (inst *EraBond) SetStakeProgramAccount(stakeProgram ag_solanago.PublicKey) *EraBond {
	inst.AccountMetaSlice[9] = ag_solanago.Meta(stakeProgram)
	return inst
}

// GetStakeProgramAccount gets the "stakeProgram" account.
func (inst *EraBond) GetStakeProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(9)
}

// SetSystemProgramAccount sets the "systemProgram" account.
func (inst *EraBond) SetSystemProgramAccount(systemProgram ag_solanago.PublicKey) *EraBond {
	inst.AccountMetaSlice[10] = ag_solanago.Meta(systemProgram)
	return inst
}

// GetSystemProgramAccount gets the "systemProgram" account.
func (inst *EraBond) GetSystemProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(10)
}

func (inst EraBond) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_EraBond,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst EraBond) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *EraBond) Validate() error {
	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.StakeManager is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.Validator is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.StakePool is not set")
		}
		if inst.AccountMetaSlice[3] == nil {
			return errors.New("accounts.StakeAccount is not set")
		}
		if inst.AccountMetaSlice[4] == nil {
			return errors.New("accounts.RentPayer is not set")
		}
		if inst.AccountMetaSlice[5] == nil {
			return errors.New("accounts.Clock is not set")
		}
		if inst.AccountMetaSlice[6] == nil {
			return errors.New("accounts.Rent is not set")
		}
		if inst.AccountMetaSlice[7] == nil {
			return errors.New("accounts.StakeConfig is not set")
		}
		if inst.AccountMetaSlice[8] == nil {
			return errors.New("accounts.StakeHistory is not set")
		}
		if inst.AccountMetaSlice[9] == nil {
			return errors.New("accounts.StakeProgram is not set")
		}
		if inst.AccountMetaSlice[10] == nil {
			return errors.New("accounts.SystemProgram is not set")
		}
	}
	return nil
}

func (inst *EraBond) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("EraBond")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=0]").ParentFunc(func(paramsBranch ag_treeout.Branches) {})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=11]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta(" stakeManager", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("    validator", inst.AccountMetaSlice.Get(1)))
						accountsBranch.Child(ag_format.Meta("    stakePool", inst.AccountMetaSlice.Get(2)))
						accountsBranch.Child(ag_format.Meta("        stake", inst.AccountMetaSlice.Get(3)))
						accountsBranch.Child(ag_format.Meta("    rentPayer", inst.AccountMetaSlice.Get(4)))
						accountsBranch.Child(ag_format.Meta("        clock", inst.AccountMetaSlice.Get(5)))
						accountsBranch.Child(ag_format.Meta("         rent", inst.AccountMetaSlice.Get(6)))
						accountsBranch.Child(ag_format.Meta("  stakeConfig", inst.AccountMetaSlice.Get(7)))
						accountsBranch.Child(ag_format.Meta(" stakeHistory", inst.AccountMetaSlice.Get(8)))
						accountsBranch.Child(ag_format.Meta(" stakeProgram", inst.AccountMetaSlice.Get(9)))
						accountsBranch.Child(ag_format.Meta("systemProgram", inst.AccountMetaSlice.Get(10)))
					})
				})
		})
}

func (obj EraBond) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	return nil
}
func (obj *EraBond) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	return nil
}

// NewEraBondInstruction declares a new EraBond instruction with the provided parameters and accounts.
func NewEraBondInstruction(
	// Accounts:
	stakeManager ag_solanago.PublicKey,
	validator ag_solanago.PublicKey,
	stakePool ag_solanago.PublicKey,
	stakeAccount ag_solanago.PublicKey,
	rentPayer ag_solanago.PublicKey,
	clock ag_solanago.PublicKey,
	rent ag_solanago.PublicKey,
	stakeConfig ag_solanago.PublicKey,
	stakeHistory ag_solanago.PublicKey,
	stakeProgram ag_solanago.PublicKey,
	systemProgram ag_solanago.PublicKey) *EraBond {
	return NewEraBondInstructionBuilder().
		SetStakeManagerAccount(stakeManager).
		SetValidatorAccount(validator).
		SetStakePoolAccount(stakePool).
		SetStakeAccountAccount(stakeAccount).
		SetRentPayerAccount(rentPayer).
		SetClockAccount(clock).
		SetRentAccount(rent).
		SetStakeConfigAccount(stakeConfig).
		SetStakeHistoryAccount(stakeHistory).
		SetStakeProgramAccount(stakeProgram).
		SetSystemProgramAccount(systemProgram)
}
