// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package lsd_program

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// EraSkipBond is the `eraSkipBond` instruction.
type EraSkipBond struct {

	// [0] = [WRITE] stakeManager
	//
	// [1] = [] stakeProgram
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewEraSkipBondInstructionBuilder creates a new `EraSkipBond` instruction builder.
func NewEraSkipBondInstructionBuilder() *EraSkipBond {
	nd := &EraSkipBond{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 2),
	}
	return nd
}

// SetStakeManagerAccount sets the "stakeManager" account.
func (inst *EraSkipBond) SetStakeManagerAccount(stakeManager ag_solanago.PublicKey) *EraSkipBond {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(stakeManager).WRITE()
	return inst
}

// GetStakeManagerAccount gets the "stakeManager" account.
func (inst *EraSkipBond) GetStakeManagerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetStakeProgramAccount sets the "stakeProgram" account.
func (inst *EraSkipBond) SetStakeProgramAccount(stakeProgram ag_solanago.PublicKey) *EraSkipBond {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(stakeProgram)
	return inst
}

// GetStakeProgramAccount gets the "stakeProgram" account.
func (inst *EraSkipBond) GetStakeProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

func (inst EraSkipBond) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_EraSkipBond,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst EraSkipBond) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *EraSkipBond) Validate() error {
	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.StakeManager is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.StakeProgram is not set")
		}
	}
	return nil
}

func (inst *EraSkipBond) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("EraSkipBond")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=0]").ParentFunc(func(paramsBranch ag_treeout.Branches) {})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=2]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("stakeManager", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("stakeProgram", inst.AccountMetaSlice.Get(1)))
					})
				})
		})
}

func (obj EraSkipBond) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	return nil
}
func (obj *EraSkipBond) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	return nil
}

// NewEraSkipBondInstruction declares a new EraSkipBond instruction with the provided parameters and accounts.
func NewEraSkipBondInstruction(
	// Accounts:
	stakeManager ag_solanago.PublicKey,
	stakeProgram ag_solanago.PublicKey) *EraSkipBond {
	return NewEraSkipBondInstructionBuilder().
		SetStakeManagerAccount(stakeManager).
		SetStakeProgramAccount(stakeProgram)
}
