// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package lsd_program

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// EraUpdateActive is the `eraUpdateActive` instruction.
type EraUpdateActive struct {

	// [0] = [WRITE] stakeManager
	//
	// [1] = [] stakeAccount
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewEraUpdateActiveInstructionBuilder creates a new `EraUpdateActive` instruction builder.
func NewEraUpdateActiveInstructionBuilder() *EraUpdateActive {
	nd := &EraUpdateActive{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 2),
	}
	return nd
}

// SetStakeManagerAccount sets the "stakeManager" account.
func (inst *EraUpdateActive) SetStakeManagerAccount(stakeManager ag_solanago.PublicKey) *EraUpdateActive {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(stakeManager).WRITE()
	return inst
}

// GetStakeManagerAccount gets the "stakeManager" account.
func (inst *EraUpdateActive) GetStakeManagerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetStakeAccountAccount sets the "stakeAccount" account.
func (inst *EraUpdateActive) SetStakeAccountAccount(stakeAccount ag_solanago.PublicKey) *EraUpdateActive {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(stakeAccount)
	return inst
}

// GetStakeAccountAccount gets the "stakeAccount" account.
func (inst *EraUpdateActive) GetStakeAccountAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

func (inst EraUpdateActive) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_EraUpdateActive,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst EraUpdateActive) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *EraUpdateActive) Validate() error {
	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.StakeManager is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.StakeAccount is not set")
		}
	}
	return nil
}

func (inst *EraUpdateActive) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("EraUpdateActive")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=0]").ParentFunc(func(paramsBranch ag_treeout.Branches) {})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=2]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("stakeManager", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("       stake", inst.AccountMetaSlice.Get(1)))
					})
				})
		})
}

func (obj EraUpdateActive) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	return nil
}
func (obj *EraUpdateActive) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	return nil
}

// NewEraUpdateActiveInstruction declares a new EraUpdateActive instruction with the provided parameters and accounts.
func NewEraUpdateActiveInstruction(
	// Accounts:
	stakeManager ag_solanago.PublicKey,
	stakeAccount ag_solanago.PublicKey) *EraUpdateActive {
	return NewEraUpdateActiveInstructionBuilder().
		SetStakeManagerAccount(stakeManager).
		SetStakeAccountAccount(stakeAccount)
}
