// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package lsd_program

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// EraUnbond is the `eraUnbond` instruction.
type EraUnbond struct {

	// [0] = [WRITE] stakeManager
	//
	// [1] = [] stakePool
	//
	// [2] = [WRITE] fromStakeAccount
	//
	// [3] = [WRITE, SIGNER] splitStakeAccount
	//
	// [4] = [WRITE] validator
	//
	// [5] = [WRITE, SIGNER] rentPayer
	//
	// [6] = [] clock
	//
	// [7] = [] rent
	//
	// [8] = [] stakeHistory
	//
	// [9] = [] stakeProgram
	//
	// [10] = [] systemProgram
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewEraUnbondInstructionBuilder creates a new `EraUnbond` instruction builder.
func NewEraUnbondInstructionBuilder() *EraUnbond {
	nd := &EraUnbond{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 11),
	}
	return nd
}

// SetStakeManagerAccount sets the "stakeManager" account.
func (inst *EraUnbond) SetStakeManagerAccount(stakeManager ag_solanago.PublicKey) *EraUnbond {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(stakeManager).WRITE()
	return inst
}

// GetStakeManagerAccount gets the "stakeManager" account.
func (inst *EraUnbond) GetStakeManagerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetStakePoolAccount sets the "stakePool" account.
func (inst *EraUnbond) SetStakePoolAccount(stakePool ag_solanago.PublicKey) *EraUnbond {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(stakePool)
	return inst
}

// GetStakePoolAccount gets the "stakePool" account.
func (inst *EraUnbond) GetStakePoolAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

// SetFromStakeAccountAccount sets the "fromStakeAccount" account.
func (inst *EraUnbond) SetFromStakeAccountAccount(fromStakeAccount ag_solanago.PublicKey) *EraUnbond {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(fromStakeAccount).WRITE()
	return inst
}

// GetFromStakeAccountAccount gets the "fromStakeAccount" account.
func (inst *EraUnbond) GetFromStakeAccountAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(2)
}

// SetSplitStakeAccountAccount sets the "splitStakeAccount" account.
func (inst *EraUnbond) SetSplitStakeAccountAccount(splitStakeAccount ag_solanago.PublicKey) *EraUnbond {
	inst.AccountMetaSlice[3] = ag_solanago.Meta(splitStakeAccount).WRITE().SIGNER()
	return inst
}

// GetSplitStakeAccountAccount gets the "splitStakeAccount" account.
func (inst *EraUnbond) GetSplitStakeAccountAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(3)
}

// SetValidatorAccount sets the "validator" account.
func (inst *EraUnbond) SetValidatorAccount(validator ag_solanago.PublicKey) *EraUnbond {
	inst.AccountMetaSlice[4] = ag_solanago.Meta(validator).WRITE()
	return inst
}

// GetValidatorAccount gets the "validator" account.
func (inst *EraUnbond) GetValidatorAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(4)
}

// SetRentPayerAccount sets the "rentPayer" account.
func (inst *EraUnbond) SetRentPayerAccount(rentPayer ag_solanago.PublicKey) *EraUnbond {
	inst.AccountMetaSlice[5] = ag_solanago.Meta(rentPayer).WRITE().SIGNER()
	return inst
}

// GetRentPayerAccount gets the "rentPayer" account.
func (inst *EraUnbond) GetRentPayerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(5)
}

// SetClockAccount sets the "clock" account.
func (inst *EraUnbond) SetClockAccount(clock ag_solanago.PublicKey) *EraUnbond {
	inst.AccountMetaSlice[6] = ag_solanago.Meta(clock)
	return inst
}

// GetClockAccount gets the "clock" account.
func (inst *EraUnbond) GetClockAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(6)
}

// SetRentAccount sets the "rent" account.
func (inst *EraUnbond) SetRentAccount(rent ag_solanago.PublicKey) *EraUnbond {
	inst.AccountMetaSlice[7] = ag_solanago.Meta(rent)
	return inst
}

// GetRentAccount gets the "rent" account.
func (inst *EraUnbond) GetRentAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(7)
}

// SetStakeHistoryAccount sets the "stakeHistory" account.
func (inst *EraUnbond) SetStakeHistoryAccount(stakeHistory ag_solanago.PublicKey) *EraUnbond {
	inst.AccountMetaSlice[8] = ag_solanago.Meta(stakeHistory)
	return inst
}

// GetStakeHistoryAccount gets the "stakeHistory" account.
func (inst *EraUnbond) GetStakeHistoryAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(8)
}

// SetStakeProgramAccount sets the "stakeProgram" account.
func (inst *EraUnbond) SetStakeProgramAccount(stakeProgram ag_solanago.PublicKey) *EraUnbond {
	inst.AccountMetaSlice[9] = ag_solanago.Meta(stakeProgram)
	return inst
}

// GetStakeProgramAccount gets the "stakeProgram" account.
func (inst *EraUnbond) GetStakeProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(9)
}

// SetSystemProgramAccount sets the "systemProgram" account.
func (inst *EraUnbond) SetSystemProgramAccount(systemProgram ag_solanago.PublicKey) *EraUnbond {
	inst.AccountMetaSlice[10] = ag_solanago.Meta(systemProgram)
	return inst
}

// GetSystemProgramAccount gets the "systemProgram" account.
func (inst *EraUnbond) GetSystemProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(10)
}

func (inst EraUnbond) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_EraUnbond,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst EraUnbond) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *EraUnbond) Validate() error {
	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.StakeManager is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.StakePool is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.FromStakeAccount is not set")
		}
		if inst.AccountMetaSlice[3] == nil {
			return errors.New("accounts.SplitStakeAccount is not set")
		}
		if inst.AccountMetaSlice[4] == nil {
			return errors.New("accounts.Validator is not set")
		}
		if inst.AccountMetaSlice[5] == nil {
			return errors.New("accounts.RentPayer is not set")
		}
		if inst.AccountMetaSlice[6] == nil {
			return errors.New("accounts.Clock is not set")
		}
		if inst.AccountMetaSlice[7] == nil {
			return errors.New("accounts.Rent is not set")
		}
		if inst.AccountMetaSlice[8] == nil {
			return errors.New("accounts.StakeHistory is not set")
		}
		if inst.AccountMetaSlice[9] == nil {
			return errors.New("accounts.StakeProgram is not set")
		}
		if inst.AccountMetaSlice[10] == nil {
			return errors.New("accounts.SystemProgram is not set")
		}
	}
	return nil
}

func (inst *EraUnbond) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("EraUnbond")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=0]").ParentFunc(func(paramsBranch ag_treeout.Branches) {})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=11]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta(" stakeManager", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("    stakePool", inst.AccountMetaSlice.Get(1)))
						accountsBranch.Child(ag_format.Meta("    fromStake", inst.AccountMetaSlice.Get(2)))
						accountsBranch.Child(ag_format.Meta("   splitStake", inst.AccountMetaSlice.Get(3)))
						accountsBranch.Child(ag_format.Meta("    validator", inst.AccountMetaSlice.Get(4)))
						accountsBranch.Child(ag_format.Meta("    rentPayer", inst.AccountMetaSlice.Get(5)))
						accountsBranch.Child(ag_format.Meta("        clock", inst.AccountMetaSlice.Get(6)))
						accountsBranch.Child(ag_format.Meta("         rent", inst.AccountMetaSlice.Get(7)))
						accountsBranch.Child(ag_format.Meta(" stakeHistory", inst.AccountMetaSlice.Get(8)))
						accountsBranch.Child(ag_format.Meta(" stakeProgram", inst.AccountMetaSlice.Get(9)))
						accountsBranch.Child(ag_format.Meta("systemProgram", inst.AccountMetaSlice.Get(10)))
					})
				})
		})
}

func (obj EraUnbond) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	return nil
}
func (obj *EraUnbond) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	return nil
}

// NewEraUnbondInstruction declares a new EraUnbond instruction with the provided parameters and accounts.
func NewEraUnbondInstruction(
	// Accounts:
	stakeManager ag_solanago.PublicKey,
	stakePool ag_solanago.PublicKey,
	fromStakeAccount ag_solanago.PublicKey,
	splitStakeAccount ag_solanago.PublicKey,
	validator ag_solanago.PublicKey,
	rentPayer ag_solanago.PublicKey,
	clock ag_solanago.PublicKey,
	rent ag_solanago.PublicKey,
	stakeHistory ag_solanago.PublicKey,
	stakeProgram ag_solanago.PublicKey,
	systemProgram ag_solanago.PublicKey) *EraUnbond {
	return NewEraUnbondInstructionBuilder().
		SetStakeManagerAccount(stakeManager).
		SetStakePoolAccount(stakePool).
		SetFromStakeAccountAccount(fromStakeAccount).
		SetSplitStakeAccountAccount(splitStakeAccount).
		SetValidatorAccount(validator).
		SetRentPayerAccount(rentPayer).
		SetClockAccount(clock).
		SetRentAccount(rent).
		SetStakeHistoryAccount(stakeHistory).
		SetStakeProgramAccount(stakeProgram).
		SetSystemProgramAccount(systemProgram)
}
