// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package lsd_program

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// EraWithdraw is the `eraWithdraw` instruction.
type EraWithdraw struct {

	// [0] = [WRITE] stakeManager
	//
	// [1] = [WRITE] stakePool
	//
	// [2] = [WRITE] stakeAccount
	//
	// [3] = [] clock
	//
	// [4] = [] stakeHistory
	//
	// [5] = [] stakeProgram
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewEraWithdrawInstructionBuilder creates a new `EraWithdraw` instruction builder.
func NewEraWithdrawInstructionBuilder() *EraWithdraw {
	nd := &EraWithdraw{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 6),
	}
	return nd
}

// SetStakeManagerAccount sets the "stakeManager" account.
func (inst *EraWithdraw) SetStakeManagerAccount(stakeManager ag_solanago.PublicKey) *EraWithdraw {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(stakeManager).WRITE()
	return inst
}

// GetStakeManagerAccount gets the "stakeManager" account.
func (inst *EraWithdraw) GetStakeManagerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetStakePoolAccount sets the "stakePool" account.
func (inst *EraWithdraw) SetStakePoolAccount(stakePool ag_solanago.PublicKey) *EraWithdraw {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(stakePool).WRITE()
	return inst
}

// GetStakePoolAccount gets the "stakePool" account.
func (inst *EraWithdraw) GetStakePoolAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

// SetStakeAccountAccount sets the "stakeAccount" account.
func (inst *EraWithdraw) SetStakeAccountAccount(stakeAccount ag_solanago.PublicKey) *EraWithdraw {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(stakeAccount).WRITE()
	return inst
}

// GetStakeAccountAccount gets the "stakeAccount" account.
func (inst *EraWithdraw) GetStakeAccountAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(2)
}

// SetClockAccount sets the "clock" account.
func (inst *EraWithdraw) SetClockAccount(clock ag_solanago.PublicKey) *EraWithdraw {
	inst.AccountMetaSlice[3] = ag_solanago.Meta(clock)
	return inst
}

// GetClockAccount gets the "clock" account.
func (inst *EraWithdraw) GetClockAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(3)
}

// SetStakeHistoryAccount sets the "stakeHistory" account.
func (inst *EraWithdraw) SetStakeHistoryAccount(stakeHistory ag_solanago.PublicKey) *EraWithdraw {
	inst.AccountMetaSlice[4] = ag_solanago.Meta(stakeHistory)
	return inst
}

// GetStakeHistoryAccount gets the "stakeHistory" account.
func (inst *EraWithdraw) GetStakeHistoryAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(4)
}

// SetStakeProgramAccount sets the "stakeProgram" account.
func (inst *EraWithdraw) SetStakeProgramAccount(stakeProgram ag_solanago.PublicKey) *EraWithdraw {
	inst.AccountMetaSlice[5] = ag_solanago.Meta(stakeProgram)
	return inst
}

// GetStakeProgramAccount gets the "stakeProgram" account.
func (inst *EraWithdraw) GetStakeProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(5)
}

func (inst EraWithdraw) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_EraWithdraw,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst EraWithdraw) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *EraWithdraw) Validate() error {
	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.StakeManager is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.StakePool is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.StakeAccount is not set")
		}
		if inst.AccountMetaSlice[3] == nil {
			return errors.New("accounts.Clock is not set")
		}
		if inst.AccountMetaSlice[4] == nil {
			return errors.New("accounts.StakeHistory is not set")
		}
		if inst.AccountMetaSlice[5] == nil {
			return errors.New("accounts.StakeProgram is not set")
		}
	}
	return nil
}

func (inst *EraWithdraw) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("EraWithdraw")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=0]").ParentFunc(func(paramsBranch ag_treeout.Branches) {})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=6]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("stakeManager", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("   stakePool", inst.AccountMetaSlice.Get(1)))
						accountsBranch.Child(ag_format.Meta("       stake", inst.AccountMetaSlice.Get(2)))
						accountsBranch.Child(ag_format.Meta("       clock", inst.AccountMetaSlice.Get(3)))
						accountsBranch.Child(ag_format.Meta("stakeHistory", inst.AccountMetaSlice.Get(4)))
						accountsBranch.Child(ag_format.Meta("stakeProgram", inst.AccountMetaSlice.Get(5)))
					})
				})
		})
}

func (obj EraWithdraw) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	return nil
}
func (obj *EraWithdraw) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	return nil
}

// NewEraWithdrawInstruction declares a new EraWithdraw instruction with the provided parameters and accounts.
func NewEraWithdrawInstruction(
	// Accounts:
	stakeManager ag_solanago.PublicKey,
	stakePool ag_solanago.PublicKey,
	stakeAccount ag_solanago.PublicKey,
	clock ag_solanago.PublicKey,
	stakeHistory ag_solanago.PublicKey,
	stakeProgram ag_solanago.PublicKey) *EraWithdraw {
	return NewEraWithdrawInstructionBuilder().
		SetStakeManagerAccount(stakeManager).
		SetStakePoolAccount(stakePool).
		SetStakeAccountAccount(stakeAccount).
		SetClockAccount(clock).
		SetStakeHistoryAccount(stakeHistory).
		SetStakeProgramAccount(stakeProgram)
}
