// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.
// This file contains parsers for the events defined in the IDL.

package lsd_program

import (
	"fmt"
	binary "github.com/gagliardetto/binary"
)

func ParseAnyEvent(eventData []byte) (any, error) {
	decoder := binary.NewBorshDecoder(eventData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek event discriminator: %w", err)
	}
	switch discriminator {
	case Event_EventEraBond:
		value := new(EventEraBond)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal event as EventEraBond: %w", err)
		}
		return value, nil
	case Event_EventEraMerge:
		value := new(EventEraMerge)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal event as EventEraMerge: %w", err)
		}
		return value, nil
	case Event_EventEraNew:
		value := new(EventEraNew)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal event as EventEraNew: %w", err)
		}
		return value, nil
	case Event_EventEraSkipBond:
		value := new(EventEraSkipBond)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal event as EventEraSkipBond: %w", err)
		}
		return value, nil
	case Event_EventEraUnbond:
		value := new(EventEraUnbond)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal event as EventEraUnbond: %w", err)
		}
		return value, nil
	case Event_EventEraUpdateActive:
		value := new(EventEraUpdateActive)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal event as EventEraUpdateActive: %w", err)
		}
		return value, nil
	case Event_EventEraUpdateRate:
		value := new(EventEraUpdateRate)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal event as EventEraUpdateRate: %w", err)
		}
		return value, nil
	case Event_EventEraWithdraw:
		value := new(EventEraWithdraw)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal event as EventEraWithdraw: %w", err)
		}
		return value, nil
	case Event_EventRedelegate:
		value := new(EventRedelegate)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal event as EventRedelegate: %w", err)
		}
		return value, nil
	case Event_EventStake:
		value := new(EventStake)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal event as EventStake: %w", err)
		}
		return value, nil
	case Event_EventUnstake:
		value := new(EventUnstake)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal event as EventUnstake: %w", err)
		}
		return value, nil
	case Event_EventWithdraw:
		value := new(EventWithdraw)
		err := value.UnmarshalWithDecoder(decoder)
		if err != nil {
			return nil, fmt.Errorf("failed to unmarshal event as EventWithdraw: %w", err)
		}
		return value, nil
	default:
		return nil, fmt.Errorf("unknown discriminator: %s", binary.FormatDiscriminator(discriminator))
	}
}

func ParseEvent_EventEraBond(eventData []byte) (*EventEraBond, error) {
	decoder := binary.NewBorshDecoder(eventData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Event_EventEraBond {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Event_EventEraBond, binary.FormatDiscriminator(discriminator))
	}
	event := new(EventEraBond)
	err = event.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal event of type EventEraBond: %w", err)
	}
	return event, nil
}

func ParseEvent_EventEraMerge(eventData []byte) (*EventEraMerge, error) {
	decoder := binary.NewBorshDecoder(eventData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Event_EventEraMerge {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Event_EventEraMerge, binary.FormatDiscriminator(discriminator))
	}
	event := new(EventEraMerge)
	err = event.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal event of type EventEraMerge: %w", err)
	}
	return event, nil
}

func ParseEvent_EventEraNew(eventData []byte) (*EventEraNew, error) {
	decoder := binary.NewBorshDecoder(eventData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Event_EventEraNew {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Event_EventEraNew, binary.FormatDiscriminator(discriminator))
	}
	event := new(EventEraNew)
	err = event.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal event of type EventEraNew: %w", err)
	}
	return event, nil
}

func ParseEvent_EventEraSkipBond(eventData []byte) (*EventEraSkipBond, error) {
	decoder := binary.NewBorshDecoder(eventData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Event_EventEraSkipBond {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Event_EventEraSkipBond, binary.FormatDiscriminator(discriminator))
	}
	event := new(EventEraSkipBond)
	err = event.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal event of type EventEraSkipBond: %w", err)
	}
	return event, nil
}

func ParseEvent_EventEraUnbond(eventData []byte) (*EventEraUnbond, error) {
	decoder := binary.NewBorshDecoder(eventData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Event_EventEraUnbond {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Event_EventEraUnbond, binary.FormatDiscriminator(discriminator))
	}
	event := new(EventEraUnbond)
	err = event.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal event of type EventEraUnbond: %w", err)
	}
	return event, nil
}

func ParseEvent_EventEraUpdateActive(eventData []byte) (*EventEraUpdateActive, error) {
	decoder := binary.NewBorshDecoder(eventData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Event_EventEraUpdateActive {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Event_EventEraUpdateActive, binary.FormatDiscriminator(discriminator))
	}
	event := new(EventEraUpdateActive)
	err = event.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal event of type EventEraUpdateActive: %w", err)
	}
	return event, nil
}

func ParseEvent_EventEraUpdateRate(eventData []byte) (*EventEraUpdateRate, error) {
	decoder := binary.NewBorshDecoder(eventData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Event_EventEraUpdateRate {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Event_EventEraUpdateRate, binary.FormatDiscriminator(discriminator))
	}
	event := new(EventEraUpdateRate)
	err = event.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal event of type EventEraUpdateRate: %w", err)
	}
	return event, nil
}

func ParseEvent_EventEraWithdraw(eventData []byte) (*EventEraWithdraw, error) {
	decoder := binary.NewBorshDecoder(eventData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Event_EventEraWithdraw {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Event_EventEraWithdraw, binary.FormatDiscriminator(discriminator))
	}
	event := new(EventEraWithdraw)
	err = event.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal event of type EventEraWithdraw: %w", err)
	}
	return event, nil
}

func ParseEvent_EventRedelegate(eventData []byte) (*EventRedelegate, error) {
	decoder := binary.NewBorshDecoder(eventData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Event_EventRedelegate {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Event_EventRedelegate, binary.FormatDiscriminator(discriminator))
	}
	event := new(EventRedelegate)
	err = event.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal event of type EventRedelegate: %w", err)
	}
	return event, nil
}

func ParseEvent_EventStake(eventData []byte) (*EventStake, error) {
	decoder := binary.NewBorshDecoder(eventData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Event_EventStake {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Event_EventStake, binary.FormatDiscriminator(discriminator))
	}
	event := new(EventStake)
	err = event.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal event of type EventStake: %w", err)
	}
	return event, nil
}

func ParseEvent_EventUnstake(eventData []byte) (*EventUnstake, error) {
	decoder := binary.NewBorshDecoder(eventData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Event_EventUnstake {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Event_EventUnstake, binary.FormatDiscriminator(discriminator))
	}
	event := new(EventUnstake)
	err = event.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal event of type EventUnstake: %w", err)
	}
	return event, nil
}

func ParseEvent_EventWithdraw(eventData []byte) (*EventWithdraw, error) {
	decoder := binary.NewBorshDecoder(eventData)
	discriminator, err := decoder.ReadDiscriminator()
	if err != nil {
		return nil, fmt.Errorf("failed to peek discriminator: %w", err)
	}
	if discriminator != Event_EventWithdraw {
		return nil, fmt.Errorf("expected discriminator %v, got %s", Event_EventWithdraw, binary.FormatDiscriminator(discriminator))
	}
	event := new(EventWithdraw)
	err = event.UnmarshalWithDecoder(decoder)
	if err != nil {
		return nil, fmt.Errorf("failed to unmarshal event of type EventWithdraw: %w", err)
	}
	return event, nil
}
