// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.
// This file contains instructions.

package lsd_program

import (
	"bytes"
	"fmt"
	errors "github.com/gagliardetto/anchor-go/errors"
	binary "github.com/gagliardetto/binary"
	solanago "github.com/gagliardetto/solana-go"
)

// Builds a "initialize_stack" instruction.
func NewInitializeStackInstruction(
	stackAccount solanago.PublicKey,
	rentPayerAccount solanago.PublicKey,
	adminAccount solanago.PublicKey,
	systemProgramAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "stack": Writable, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(stackAccount, true, true))
		// Account 1 "rent_payer": Writable, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(rentPayerAccount, true, true))
		// Account 2 "admin": Read-only, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(adminAccount, false, true))
		// Account 3 "system_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(systemProgramAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		nil,
	), nil
}

// Builds a "initialize_stake_manager" instruction.
func NewInitializeStakeManagerInstruction(
	stakeManagerAccount solanago.PublicKey,
	stackAccount solanago.PublicKey,
	stakePoolAccount solanago.PublicKey,
	stackFeeAccountAccount solanago.PublicKey,
	lsdTokenMintAccount solanago.PublicKey,
	validatorAccount solanago.PublicKey,
	rentPayerAccount solanago.PublicKey,
	adminAccount solanago.PublicKey,
	associatedTokenProgramAccount solanago.PublicKey,
	systemProgramAccount solanago.PublicKey,
	clockAccount solanago.PublicKey,
	rentAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "stake_manager": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(stakeManagerAccount, true, false))
		// Account 1 "stack": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(stackAccount, false, false))
		// Account 2 "stake_pool": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(stakePoolAccount, false, false))
		// Account 3 "stack_fee_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(stackFeeAccountAccount, true, false))
		// Account 4 "lsd_token_mint": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(lsdTokenMintAccount, false, false))
		// Account 5 "validator": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(validatorAccount, false, false))
		// Account 6 "rent_payer": Writable, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(rentPayerAccount, true, true))
		// Account 7 "admin": Read-only, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(adminAccount, false, true))
		// Account 8 "associated_token_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(associatedTokenProgramAccount, false, false))
		// Account 9 "system_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(systemProgramAccount, false, false))
		// Account 10 "clock": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(clockAccount, false, false))
		// Account 11 "rent": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(rentAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		nil,
	), nil
}

// Builds a "transfer_stack_admin" instruction.
func NewTransferStackAdminInstruction(
	// Params:
	newAdminParam solanago.PublicKey,

	// Accounts:
	stackAccount solanago.PublicKey,
	adminAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_TransferStackAdmin[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `newAdminParam`:
		err = enc__.Encode(newAdminParam)
		if err != nil {
			return nil, errors.NewField("newAdminParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "stack": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(stackAccount, true, false))
		// Account 1 "admin": Read-only, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(adminAccount, false, true))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "set_stack_fee_commission" instruction.
func NewSetStackFeeCommissionInstruction(
	// Params:
	stackFeeCommissionParam uint64,

	// Accounts:
	stackAccount solanago.PublicKey,
	adminAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_SetStackFeeCommission[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `stackFeeCommissionParam`:
		err = enc__.Encode(stackFeeCommissionParam)
		if err != nil {
			return nil, errors.NewField("stackFeeCommissionParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "stack": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(stackAccount, true, false))
		// Account 1 "admin": Read-only, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(adminAccount, false, true))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "set_platform_stack_fee_commission" instruction.
func NewSetPlatformStackFeeCommissionInstruction(
	// Params:
	stackFeeCommissionParam uint64,

	// Accounts:
	stakeManagerAccount solanago.PublicKey,
	stackAccount solanago.PublicKey,
	adminAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_SetPlatformStackFeeCommission[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `stackFeeCommissionParam`:
		err = enc__.Encode(stackFeeCommissionParam)
		if err != nil {
			return nil, errors.NewField("stackFeeCommissionParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "stake_manager": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(stakeManagerAccount, true, false))
		// Account 1 "stack": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(stackAccount, false, false))
		// Account 2 "admin": Read-only, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(adminAccount, false, true))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "add_entrusted_stake_manager" instruction.
func NewAddEntrustedStakeManagerInstruction(
	// Params:
	stakeManagerParam solanago.PublicKey,

	// Accounts:
	stackAccount solanago.PublicKey,
	adminAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_AddEntrustedStakeManager[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `stakeManagerParam`:
		err = enc__.Encode(stakeManagerParam)
		if err != nil {
			return nil, errors.NewField("stakeManagerParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "stack": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(stackAccount, true, false))
		// Account 1 "admin": Read-only, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(adminAccount, false, true))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "remove_entrusted_stake_manager" instruction.
func NewRemoveEntrustedStakeManagerInstruction(
	// Params:
	stakeManagerParam solanago.PublicKey,

	// Accounts:
	stackAccount solanago.PublicKey,
	adminAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_RemoveEntrustedStakeManager[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `stakeManagerParam`:
		err = enc__.Encode(stakeManagerParam)
		if err != nil {
			return nil, errors.NewField("stakeManagerParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "stack": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(stackAccount, true, false))
		// Account 1 "admin": Read-only, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(adminAccount, false, true))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "transfer_stake_manager_admin" instruction.
func NewTransferStakeManagerAdminInstruction(
	// Params:
	newAdminParam solanago.PublicKey,

	// Accounts:
	stakeManagerAccount solanago.PublicKey,
	adminAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_TransferStakeManagerAdmin[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `newAdminParam`:
		err = enc__.Encode(newAdminParam)
		if err != nil {
			return nil, errors.NewField("newAdminParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "stake_manager": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(stakeManagerAccount, true, false))
		// Account 1 "admin": Read-only, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(adminAccount, false, true))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "transfer_balancer" instruction.
func NewTransferBalancerInstruction(
	// Params:
	newBalancerParam solanago.PublicKey,

	// Accounts:
	stakeManagerAccount solanago.PublicKey,
	adminAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_TransferBalancer[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `newBalancerParam`:
		err = enc__.Encode(newBalancerParam)
		if err != nil {
			return nil, errors.NewField("newBalancerParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "stake_manager": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(stakeManagerAccount, true, false))
		// Account 1 "admin": Read-only, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(adminAccount, false, true))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "set_min_stake_amount" instruction.
func NewSetMinStakeAmountInstruction(
	// Params:
	amountParam uint64,

	// Accounts:
	stakeManagerAccount solanago.PublicKey,
	adminAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_SetMinStakeAmount[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `amountParam`:
		err = enc__.Encode(amountParam)
		if err != nil {
			return nil, errors.NewField("amountParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "stake_manager": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(stakeManagerAccount, true, false))
		// Account 1 "admin": Read-only, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(adminAccount, false, true))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "set_unbonding_duration" instruction.
func NewSetUnbondingDurationInstruction(
	// Params:
	durationParam uint64,

	// Accounts:
	stakeManagerAccount solanago.PublicKey,
	adminAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_SetUnbondingDuration[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `durationParam`:
		err = enc__.Encode(durationParam)
		if err != nil {
			return nil, errors.NewField("durationParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "stake_manager": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(stakeManagerAccount, true, false))
		// Account 1 "admin": Read-only, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(adminAccount, false, true))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "set_rate_change_limit" instruction.
func NewSetRateChangeLimitInstruction(
	// Params:
	rateChangeLimitParam uint64,

	// Accounts:
	stakeManagerAccount solanago.PublicKey,
	adminAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_SetRateChangeLimit[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `rateChangeLimitParam`:
		err = enc__.Encode(rateChangeLimitParam)
		if err != nil {
			return nil, errors.NewField("rateChangeLimitParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "stake_manager": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(stakeManagerAccount, true, false))
		// Account 1 "admin": Read-only, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(adminAccount, false, true))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "set_platform_fee_commission" instruction.
func NewSetPlatformFeeCommissionInstruction(
	// Params:
	protocolFeeCommissionParam uint64,

	// Accounts:
	stakeManagerAccount solanago.PublicKey,
	adminAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_SetPlatformFeeCommission[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `protocolFeeCommissionParam`:
		err = enc__.Encode(protocolFeeCommissionParam)
		if err != nil {
			return nil, errors.NewField("protocolFeeCommissionParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "stake_manager": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(stakeManagerAccount, true, false))
		// Account 1 "admin": Read-only, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(adminAccount, false, true))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "add_validator" instruction.
func NewAddValidatorInstruction(
	// Params:
	newValidatorParam solanago.PublicKey,

	// Accounts:
	stakeManagerAccount solanago.PublicKey,
	adminAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_AddValidator[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `newValidatorParam`:
		err = enc__.Encode(newValidatorParam)
		if err != nil {
			return nil, errors.NewField("newValidatorParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "stake_manager": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(stakeManagerAccount, true, false))
		// Account 1 "admin": Read-only, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(adminAccount, false, true))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "remove_validator" instruction.
func NewRemoveValidatorInstruction(
	// Params:
	removeValidatorParam solanago.PublicKey,

	// Accounts:
	stakeManagerAccount solanago.PublicKey,
	adminAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_RemoveValidator[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `removeValidatorParam`:
		err = enc__.Encode(removeValidatorParam)
		if err != nil {
			return nil, errors.NewField("removeValidatorParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "stake_manager": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(stakeManagerAccount, true, false))
		// Account 1 "admin": Read-only, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(adminAccount, false, true))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "realloc_stake_manager" instruction.
func NewReallocStakeManagerInstruction(
	// Params:
	newSizeParam uint32,

	// Accounts:
	stakeManagerAccount solanago.PublicKey,
	adminAccount solanago.PublicKey,
	rentPayerAccount solanago.PublicKey,
	systemProgramAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_ReallocStakeManager[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `newSizeParam`:
		err = enc__.Encode(newSizeParam)
		if err != nil {
			return nil, errors.NewField("newSizeParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "stake_manager": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(stakeManagerAccount, true, false))
		// Account 1 "admin": Read-only, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(adminAccount, false, true))
		// Account 2 "rent_payer": Writable, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(rentPayerAccount, true, true))
		// Account 3 "system_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(systemProgramAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "redelegate" instruction.
func NewRedelegateInstruction(
	// Params:
	redelegateAmountParam uint64,

	// Accounts:
	stakeManagerAccount solanago.PublicKey,
	balancerAccount solanago.PublicKey,
	toValidatorAccount solanago.PublicKey,
	stakePoolAccount solanago.PublicKey,
	fromStakeAccountAccount solanago.PublicKey,
	splitStakeAccountAccount solanago.PublicKey,
	toStakeAccountAccount solanago.PublicKey,
	rentPayerAccount solanago.PublicKey,
	clockAccount solanago.PublicKey,
	stakeConfigAccount solanago.PublicKey,
	stakeHistoryAccount solanago.PublicKey,
	stakeProgramAccount solanago.PublicKey,
	systemProgramAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_Redelegate[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `redelegateAmountParam`:
		err = enc__.Encode(redelegateAmountParam)
		if err != nil {
			return nil, errors.NewField("redelegateAmountParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "stake_manager": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(stakeManagerAccount, true, false))
		// Account 1 "balancer": Read-only, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(balancerAccount, false, true))
		// Account 2 "to_validator": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(toValidatorAccount, true, false))
		// Account 3 "stake_pool": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(stakePoolAccount, false, false))
		// Account 4 "from_stake_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(fromStakeAccountAccount, true, false))
		// Account 5 "split_stake_account": Writable, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(splitStakeAccountAccount, true, true))
		// Account 6 "to_stake_account": Writable, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(toStakeAccountAccount, true, true))
		// Account 7 "rent_payer": Writable, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(rentPayerAccount, true, true))
		// Account 8 "clock": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(clockAccount, false, false))
		// Account 9 "stake_config": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(stakeConfigAccount, false, false))
		// Account 10 "stake_history": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(stakeHistoryAccount, false, false))
		// Account 11 "stake_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(stakeProgramAccount, false, false))
		// Account 12 "system_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(systemProgramAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "stake" instruction.
func NewStakeInstruction(
	// Params:
	stakeAmountParam uint64,

	// Accounts:
	stakeManagerAccount solanago.PublicKey,
	stakePoolAccount solanago.PublicKey,
	fromAccount solanago.PublicKey,
	lsdTokenMintAccount solanago.PublicKey,
	mintToAccount solanago.PublicKey,
	systemProgramAccount solanago.PublicKey,
	tokenProgramAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_Stake[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `stakeAmountParam`:
		err = enc__.Encode(stakeAmountParam)
		if err != nil {
			return nil, errors.NewField("stakeAmountParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "stake_manager": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(stakeManagerAccount, true, false))
		// Account 1 "stake_pool": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(stakePoolAccount, true, false))
		// Account 2 "from": Writable, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(fromAccount, true, true))
		// Account 3 "lsd_token_mint": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(lsdTokenMintAccount, true, false))
		// Account 4 "mint_to": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(mintToAccount, true, false))
		// Account 5 "system_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(systemProgramAccount, false, false))
		// Account 6 "token_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(tokenProgramAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "unstake" instruction.
func NewUnstakeInstruction(
	// Params:
	unstakeAmountParam uint64,

	// Accounts:
	stakeManagerAccount solanago.PublicKey,
	lsdTokenMintAccount solanago.PublicKey,
	burnLsdTokenFromAccount solanago.PublicKey,
	burnLsdTokenAuthorityAccount solanago.PublicKey,
	unstakeAccountAccount solanago.PublicKey,
	rentPayerAccount solanago.PublicKey,
	systemProgramAccount solanago.PublicKey,
	tokenProgramAccount solanago.PublicKey,
	clockAccount solanago.PublicKey,
	rentAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	buf__ := new(bytes.Buffer)
	enc__ := binary.NewBorshEncoder(buf__)

	// Encode the instruction discriminator.
	err := enc__.WriteBytes(Instruction_Unstake[:], false)
	if err != nil {
		return nil, fmt.Errorf("failed to write instruction discriminator: %w", err)
	}
	{
		// Serialize `unstakeAmountParam`:
		err = enc__.Encode(unstakeAmountParam)
		if err != nil {
			return nil, errors.NewField("unstakeAmountParam", err)
		}
	}
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "stake_manager": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(stakeManagerAccount, true, false))
		// Account 1 "lsd_token_mint": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(lsdTokenMintAccount, true, false))
		// Account 2 "burn_lsd_token_from": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(burnLsdTokenFromAccount, true, false))
		// Account 3 "burn_lsd_token_authority": Read-only, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(burnLsdTokenAuthorityAccount, false, true))
		// Account 4 "unstake_account": Writable, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(unstakeAccountAccount, true, true))
		// Account 5 "rent_payer": Writable, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(rentPayerAccount, true, true))
		// Account 6 "system_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(systemProgramAccount, false, false))
		// Account 7 "token_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(tokenProgramAccount, false, false))
		// Account 8 "clock": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(clockAccount, false, false))
		// Account 9 "rent": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(rentAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		buf__.Bytes(),
	), nil
}

// Builds a "withdraw" instruction.
func NewWithdrawInstruction(
	stakeManagerAccount solanago.PublicKey,
	stakePoolAccount solanago.PublicKey,
	unstakeAccountAccount solanago.PublicKey,
	recipientAccount solanago.PublicKey,
	clockAccount solanago.PublicKey,
	systemProgramAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "stake_manager": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(stakeManagerAccount, true, false))
		// Account 1 "stake_pool": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(stakePoolAccount, true, false))
		// Account 2 "unstake_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(unstakeAccountAccount, true, false))
		// Account 3 "recipient": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(recipientAccount, true, false))
		// Account 4 "clock": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(clockAccount, false, false))
		// Account 5 "system_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(systemProgramAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		nil,
	), nil
}

// Builds a "era_new" instruction.
func NewEraNewInstruction(
	stakeManagerAccount solanago.PublicKey,
	clockAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "stake_manager": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(stakeManagerAccount, true, false))
		// Account 1 "clock": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(clockAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		nil,
	), nil
}

// Builds a "era_bond" instruction.
func NewEraBondInstruction(
	stakeManagerAccount solanago.PublicKey,
	validatorAccount solanago.PublicKey,
	stakePoolAccount solanago.PublicKey,
	stakeAccountAccount solanago.PublicKey,
	rentPayerAccount solanago.PublicKey,
	clockAccount solanago.PublicKey,
	rentAccount solanago.PublicKey,
	stakeConfigAccount solanago.PublicKey,
	stakeHistoryAccount solanago.PublicKey,
	stakeProgramAccount solanago.PublicKey,
	systemProgramAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "stake_manager": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(stakeManagerAccount, true, false))
		// Account 1 "validator": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(validatorAccount, true, false))
		// Account 2 "stake_pool": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(stakePoolAccount, true, false))
		// Account 3 "stake_account": Writable, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(stakeAccountAccount, true, true))
		// Account 4 "rent_payer": Writable, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(rentPayerAccount, true, true))
		// Account 5 "clock": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(clockAccount, false, false))
		// Account 6 "rent": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(rentAccount, false, false))
		// Account 7 "stake_config": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(stakeConfigAccount, false, false))
		// Account 8 "stake_history": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(stakeHistoryAccount, false, false))
		// Account 9 "stake_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(stakeProgramAccount, false, false))
		// Account 10 "system_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(systemProgramAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		nil,
	), nil
}

// Builds a "era_skip_bond" instruction.
func NewEraSkipBondInstruction(
	stakeManagerAccount solanago.PublicKey,
	stakeProgramAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "stake_manager": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(stakeManagerAccount, true, false))
		// Account 1 "stake_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(stakeProgramAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		nil,
	), nil
}

// Builds a "era_unbond" instruction.
func NewEraUnbondInstruction(
	stakeManagerAccount solanago.PublicKey,
	stakePoolAccount solanago.PublicKey,
	fromStakeAccountAccount solanago.PublicKey,
	splitStakeAccountAccount solanago.PublicKey,
	validatorAccount solanago.PublicKey,
	rentPayerAccount solanago.PublicKey,
	clockAccount solanago.PublicKey,
	rentAccount solanago.PublicKey,
	stakeHistoryAccount solanago.PublicKey,
	stakeProgramAccount solanago.PublicKey,
	systemProgramAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "stake_manager": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(stakeManagerAccount, true, false))
		// Account 1 "stake_pool": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(stakePoolAccount, false, false))
		// Account 2 "from_stake_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(fromStakeAccountAccount, true, false))
		// Account 3 "split_stake_account": Writable, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(splitStakeAccountAccount, true, true))
		// Account 4 "validator": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(validatorAccount, true, false))
		// Account 5 "rent_payer": Writable, Signer, Required
		accounts__.Append(solanago.NewAccountMeta(rentPayerAccount, true, true))
		// Account 6 "clock": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(clockAccount, false, false))
		// Account 7 "rent": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(rentAccount, false, false))
		// Account 8 "stake_history": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(stakeHistoryAccount, false, false))
		// Account 9 "stake_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(stakeProgramAccount, false, false))
		// Account 10 "system_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(systemProgramAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		nil,
	), nil
}

// Builds a "era_update_active" instruction.
func NewEraUpdateActiveInstruction(
	stakeManagerAccount solanago.PublicKey,
	stakeAccountAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "stake_manager": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(stakeManagerAccount, true, false))
		// Account 1 "stake_account": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(stakeAccountAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		nil,
	), nil
}

// Builds a "era_update_rate" instruction.
func NewEraUpdateRateInstruction(
	stakeManagerAccount solanago.PublicKey,
	stackAccount solanago.PublicKey,
	stakePoolAccount solanago.PublicKey,
	lsdTokenMintAccount solanago.PublicKey,
	platformFeeRecipientAccount solanago.PublicKey,
	stackFeeRecipientAccount solanago.PublicKey,
	stackFeeAccountAccount solanago.PublicKey,
	associatedTokenProgramAccount solanago.PublicKey,
	tokenProgramAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "stake_manager": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(stakeManagerAccount, true, false))
		// Account 1 "stack": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(stackAccount, false, false))
		// Account 2 "stake_pool": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(stakePoolAccount, false, false))
		// Account 3 "lsd_token_mint": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(lsdTokenMintAccount, true, false))
		// Account 4 "platform_fee_recipient": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(platformFeeRecipientAccount, true, false))
		// Account 5 "stack_fee_recipient": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(stackFeeRecipientAccount, true, false))
		// Account 6 "stack_fee_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(stackFeeAccountAccount, true, false))
		// Account 7 "associated_token_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(associatedTokenProgramAccount, false, false))
		// Account 8 "token_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(tokenProgramAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		nil,
	), nil
}

// Builds a "era_merge" instruction.
func NewEraMergeInstruction(
	stakeManagerAccount solanago.PublicKey,
	srcStakeAccountAccount solanago.PublicKey,
	dstStakeAccountAccount solanago.PublicKey,
	stakePoolAccount solanago.PublicKey,
	clockAccount solanago.PublicKey,
	stakeHistoryAccount solanago.PublicKey,
	stakeProgramAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "stake_manager": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(stakeManagerAccount, true, false))
		// Account 1 "src_stake_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(srcStakeAccountAccount, true, false))
		// Account 2 "dst_stake_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(dstStakeAccountAccount, true, false))
		// Account 3 "stake_pool": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(stakePoolAccount, false, false))
		// Account 4 "clock": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(clockAccount, false, false))
		// Account 5 "stake_history": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(stakeHistoryAccount, false, false))
		// Account 6 "stake_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(stakeProgramAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		nil,
	), nil
}

// Builds a "era_withdraw" instruction.
func NewEraWithdrawInstruction(
	stakeManagerAccount solanago.PublicKey,
	stakePoolAccount solanago.PublicKey,
	stakeAccountAccount solanago.PublicKey,
	clockAccount solanago.PublicKey,
	stakeHistoryAccount solanago.PublicKey,
	stakeProgramAccount solanago.PublicKey,
) (solanago.Instruction, error) {
	accounts__ := solanago.AccountMetaSlice{}

	// Add the accounts to the instruction.
	{
		// Account 0 "stake_manager": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(stakeManagerAccount, true, false))
		// Account 1 "stake_pool": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(stakePoolAccount, true, false))
		// Account 2 "stake_account": Writable, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(stakeAccountAccount, true, false))
		// Account 3 "clock": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(clockAccount, false, false))
		// Account 4 "stake_history": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(stakeHistoryAccount, false, false))
		// Account 5 "stake_program": Read-only, Non-signer, Required
		accounts__.Append(solanago.NewAccountMeta(stakeProgramAccount, false, false))
	}

	// Create the instruction.
	return solanago.NewInstruction(
		ProgramID,
		accounts__,
		nil,
	), nil
}
