// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package lsd_program

import (
	"bytes"
	"fmt"
	ag_spew "github.com/davecgh/go-spew/spew"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_text "github.com/gagliardetto/solana-go/text"
	ag_treeout "github.com/gagliardetto/treeout"
)

var ProgramID ag_solanago.PublicKey

func SetProgramID(pubkey ag_solanago.PublicKey) {
	ProgramID = pubkey
	ag_solanago.RegisterInstructionDecoder(ProgramID, registryDecodeInstruction)
}

const ProgramName = "LsdProgram"

func init() {
	if !ProgramID.IsZero() {
		ag_solanago.RegisterInstructionDecoder(ProgramID, registryDecodeInstruction)
	}
}

var (
	Instruction_InitializeStack = ag_binary.TypeID([8]byte{139, 248, 249, 177, 239, 66, 51, 252})

	Instruction_InitializeStakeManager = ag_binary.TypeID([8]byte{75, 220, 4, 110, 166, 194, 173, 1})

	Instruction_TransferStackAdmin = ag_binary.TypeID([8]byte{239, 183, 112, 103, 100, 99, 128, 84})

	Instruction_SetStackFeeCommission = ag_binary.TypeID([8]byte{170, 16, 193, 90, 33, 62, 62, 97})

	Instruction_SetPlatformStackFeeCommission = ag_binary.TypeID([8]byte{85, 251, 61, 253, 7, 73, 13, 178})

	Instruction_AddEntrustedStakeManager = ag_binary.TypeID([8]byte{81, 65, 28, 165, 239, 10, 152, 193})

	Instruction_RemoveEntrustedStakeManager = ag_binary.TypeID([8]byte{232, 175, 69, 153, 85, 181, 33, 160})

	Instruction_TransferStakeManagerAdmin = ag_binary.TypeID([8]byte{225, 28, 79, 223, 28, 96, 210, 226})

	Instruction_TransferBalancer = ag_binary.TypeID([8]byte{99, 139, 245, 206, 226, 124, 106, 83})

	Instruction_SetMinStakeAmount = ag_binary.TypeID([8]byte{30, 179, 162, 249, 158, 57, 14, 254})

	Instruction_SetUnbondingDuration = ag_binary.TypeID([8]byte{143, 183, 204, 237, 156, 203, 133, 250})

	Instruction_SetRateChangeLimit = ag_binary.TypeID([8]byte{13, 141, 180, 253, 190, 210, 229, 210})

	Instruction_SetPlatformFeeCommission = ag_binary.TypeID([8]byte{193, 162, 133, 226, 38, 87, 16, 252})

	Instruction_AddValidator = ag_binary.TypeID([8]byte{250, 113, 53, 54, 141, 117, 215, 185})

	Instruction_RemoveValidator = ag_binary.TypeID([8]byte{25, 96, 211, 155, 161, 14, 168, 188})

	Instruction_ReallocStakeManager = ag_binary.TypeID([8]byte{124, 76, 19, 251, 234, 127, 12, 141})

	Instruction_Redelegate = ag_binary.TypeID([8]byte{212, 82, 51, 160, 228, 80, 116, 35})

	Instruction_Stake = ag_binary.TypeID([8]byte{206, 176, 202, 18, 200, 209, 179, 108})

	Instruction_Unstake = ag_binary.TypeID([8]byte{90, 95, 107, 42, 205, 124, 50, 225})

	Instruction_Withdraw = ag_binary.TypeID([8]byte{183, 18, 70, 156, 148, 109, 161, 34})

	Instruction_EraNew = ag_binary.TypeID([8]byte{96, 178, 91, 52, 66, 223, 134, 98})

	Instruction_EraBond = ag_binary.TypeID([8]byte{44, 238, 86, 188, 197, 69, 241, 91})

	Instruction_EraSkipBond = ag_binary.TypeID([8]byte{191, 75, 28, 113, 210, 201, 136, 19})

	Instruction_EraUnbond = ag_binary.TypeID([8]byte{193, 62, 151, 104, 91, 68, 92, 148})

	Instruction_EraUpdateActive = ag_binary.TypeID([8]byte{185, 133, 175, 129, 26, 151, 115, 218})

	Instruction_EraUpdateRate = ag_binary.TypeID([8]byte{223, 55, 230, 209, 252, 154, 227, 116})

	Instruction_EraMerge = ag_binary.TypeID([8]byte{174, 80, 147, 234, 24, 233, 211, 195})

	Instruction_EraWithdraw = ag_binary.TypeID([8]byte{92, 3, 86, 172, 211, 111, 176, 238})
)

// InstructionIDToName returns the name of the instruction given its ID.
func InstructionIDToName(id ag_binary.TypeID) string {
	switch id {
	case Instruction_InitializeStack:
		return "InitializeStack"
	case Instruction_InitializeStakeManager:
		return "InitializeStakeManager"
	case Instruction_TransferStackAdmin:
		return "TransferStackAdmin"
	case Instruction_SetStackFeeCommission:
		return "SetStackFeeCommission"
	case Instruction_SetPlatformStackFeeCommission:
		return "SetPlatformStackFeeCommission"
	case Instruction_AddEntrustedStakeManager:
		return "AddEntrustedStakeManager"
	case Instruction_RemoveEntrustedStakeManager:
		return "RemoveEntrustedStakeManager"
	case Instruction_TransferStakeManagerAdmin:
		return "TransferStakeManagerAdmin"
	case Instruction_TransferBalancer:
		return "TransferBalancer"
	case Instruction_SetMinStakeAmount:
		return "SetMinStakeAmount"
	case Instruction_SetUnbondingDuration:
		return "SetUnbondingDuration"
	case Instruction_SetRateChangeLimit:
		return "SetRateChangeLimit"
	case Instruction_SetPlatformFeeCommission:
		return "SetPlatformFeeCommission"
	case Instruction_AddValidator:
		return "AddValidator"
	case Instruction_RemoveValidator:
		return "RemoveValidator"
	case Instruction_ReallocStakeManager:
		return "ReallocStakeManager"
	case Instruction_Redelegate:
		return "Redelegate"
	case Instruction_Stake:
		return "Stake"
	case Instruction_Unstake:
		return "Unstake"
	case Instruction_Withdraw:
		return "Withdraw"
	case Instruction_EraNew:
		return "EraNew"
	case Instruction_EraBond:
		return "EraBond"
	case Instruction_EraSkipBond:
		return "EraSkipBond"
	case Instruction_EraUnbond:
		return "EraUnbond"
	case Instruction_EraUpdateActive:
		return "EraUpdateActive"
	case Instruction_EraUpdateRate:
		return "EraUpdateRate"
	case Instruction_EraMerge:
		return "EraMerge"
	case Instruction_EraWithdraw:
		return "EraWithdraw"
	default:
		return ""
	}
}

type Instruction struct {
	ag_binary.BaseVariant
}

func (inst *Instruction) EncodeToTree(parent ag_treeout.Branches) {
	if enToTree, ok := inst.Impl.(ag_text.EncodableToTree); ok {
		enToTree.EncodeToTree(parent)
	} else {
		parent.Child(ag_spew.Sdump(inst))
	}
}

var InstructionImplDef = ag_binary.NewVariantDefinition(
	ag_binary.AnchorTypeIDEncoding,
	[]ag_binary.VariantType{
		{
			"initialize_stack", (*InitializeStack)(nil),
		},
		{
			"initialize_stake_manager", (*InitializeStakeManager)(nil),
		},
		{
			"transfer_stack_admin", (*TransferStackAdmin)(nil),
		},
		{
			"set_stack_fee_commission", (*SetStackFeeCommission)(nil),
		},
		{
			"set_platform_stack_fee_commission", (*SetPlatformStackFeeCommission)(nil),
		},
		{
			"add_entrusted_stake_manager", (*AddEntrustedStakeManager)(nil),
		},
		{
			"remove_entrusted_stake_manager", (*RemoveEntrustedStakeManager)(nil),
		},
		{
			"transfer_stake_manager_admin", (*TransferStakeManagerAdmin)(nil),
		},
		{
			"transfer_balancer", (*TransferBalancer)(nil),
		},
		{
			"set_min_stake_amount", (*SetMinStakeAmount)(nil),
		},
		{
			"set_unbonding_duration", (*SetUnbondingDuration)(nil),
		},
		{
			"set_rate_change_limit", (*SetRateChangeLimit)(nil),
		},
		{
			"set_platform_fee_commission", (*SetPlatformFeeCommission)(nil),
		},
		{
			"add_validator", (*AddValidator)(nil),
		},
		{
			"remove_validator", (*RemoveValidator)(nil),
		},
		{
			"realloc_stake_manager", (*ReallocStakeManager)(nil),
		},
		{
			"redelegate", (*Redelegate)(nil),
		},
		{
			"stake", (*Stake)(nil),
		},
		{
			"unstake", (*Unstake)(nil),
		},
		{
			"withdraw", (*Withdraw)(nil),
		},
		{
			"era_new", (*EraNew)(nil),
		},
		{
			"era_bond", (*EraBond)(nil),
		},
		{
			"era_skip_bond", (*EraSkipBond)(nil),
		},
		{
			"era_unbond", (*EraUnbond)(nil),
		},
		{
			"era_update_active", (*EraUpdateActive)(nil),
		},
		{
			"era_update_rate", (*EraUpdateRate)(nil),
		},
		{
			"era_merge", (*EraMerge)(nil),
		},
		{
			"era_withdraw", (*EraWithdraw)(nil),
		},
	},
)

func (inst *Instruction) ProgramID() ag_solanago.PublicKey {
	return ProgramID
}

func (inst *Instruction) Accounts() (out []*ag_solanago.AccountMeta) {
	return inst.Impl.(ag_solanago.AccountsGettable).GetAccounts()
}

func (inst *Instruction) Data() ([]byte, error) {
	buf := new(bytes.Buffer)
	if err := ag_binary.NewBorshEncoder(buf).Encode(inst); err != nil {
		return nil, fmt.Errorf("unable to encode instruction: %w", err)
	}
	return buf.Bytes(), nil
}

func (inst *Instruction) TextEncode(encoder *ag_text.Encoder, option *ag_text.Option) error {
	return encoder.Encode(inst.Impl, option)
}

func (inst *Instruction) UnmarshalWithDecoder(decoder *ag_binary.Decoder) error {
	return inst.BaseVariant.UnmarshalBinaryVariant(decoder, InstructionImplDef)
}

func (inst *Instruction) MarshalWithEncoder(encoder *ag_binary.Encoder) error {
	err := encoder.WriteBytes(inst.TypeID.Bytes(), false)
	if err != nil {
		return fmt.Errorf("unable to write variant type: %w", err)
	}
	return encoder.Encode(inst.Impl)
}

func registryDecodeInstruction(accounts []*ag_solanago.AccountMeta, data []byte) (interface{}, error) {
	inst, err := DecodeInstruction(accounts, data)
	if err != nil {
		return nil, err
	}
	return inst, nil
}

func DecodeInstruction(accounts []*ag_solanago.AccountMeta, data []byte) (*Instruction, error) {
	inst := new(Instruction)
	if err := ag_binary.NewBorshDecoder(data).Decode(inst); err != nil {
		return nil, fmt.Errorf("unable to decode instruction: %w", err)
	}
	if v, ok := inst.Impl.(ag_solanago.AccountsSettable); ok {
		err := v.SetAccounts(accounts)
		if err != nil {
			return nil, fmt.Errorf("unable to set accounts for instruction: %w", err)
		}
	}
	return inst, nil
}
