// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.
// This file contains the program ID.

package lsd_program

import solanago "github.com/gagliardetto/solana-go"

var ProgramID = solanago.MustPublicKeyFromBase58("8ufkkVBM6s52WRnhdF2yUCu1eNPnS123SoVKv8wyBFAp")
