// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package lsd_program

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// RemoveValidator is the `removeValidator` instruction.
type RemoveValidator struct {
	RemoveValidator *ag_solanago.PublicKey

	// [0] = [WRITE] stakeManager
	//
	// [1] = [SIGNER] admin
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewRemoveValidatorInstructionBuilder creates a new `RemoveValidator` instruction builder.
func NewRemoveValidatorInstructionBuilder() *RemoveValidator {
	nd := &RemoveValidator{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 2),
	}
	return nd
}

// SetRemoveValidator sets the "removeValidator" parameter.
func (inst *RemoveValidator) SetRemoveValidator(removeValidator ag_solanago.PublicKey) *RemoveValidator {
	inst.RemoveValidator = &removeValidator
	return inst
}

// SetStakeManagerAccount sets the "stakeManager" account.
func (inst *RemoveValidator) SetStakeManagerAccount(stakeManager ag_solanago.PublicKey) *RemoveValidator {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(stakeManager).WRITE()
	return inst
}

// GetStakeManagerAccount gets the "stakeManager" account.
func (inst *RemoveValidator) GetStakeManagerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetAdminAccount sets the "admin" account.
func (inst *RemoveValidator) SetAdminAccount(admin ag_solanago.PublicKey) *RemoveValidator {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(admin).SIGNER()
	return inst
}

// GetAdminAccount gets the "admin" account.
func (inst *RemoveValidator) GetAdminAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

func (inst RemoveValidator) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_RemoveValidator,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst RemoveValidator) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *RemoveValidator) Validate() error {
	// Check whether all (required) parameters are set:
	{
		if inst.RemoveValidator == nil {
			return errors.New("RemoveValidator parameter is not set")
		}
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.StakeManager is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.Admin is not set")
		}
	}
	return nil
}

func (inst *RemoveValidator) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("RemoveValidator")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=1]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param("RemoveValidator", *inst.RemoveValidator))
					})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=2]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("stakeManager", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("       admin", inst.AccountMetaSlice.Get(1)))
					})
				})
		})
}

func (obj RemoveValidator) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `RemoveValidator` param:
	err = encoder.Encode(obj.RemoveValidator)
	if err != nil {
		return err
	}
	return nil
}
func (obj *RemoveValidator) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `RemoveValidator`:
	err = decoder.Decode(&obj.RemoveValidator)
	if err != nil {
		return err
	}
	return nil
}

// NewRemoveValidatorInstruction declares a new RemoveValidator instruction with the provided parameters and accounts.
func NewRemoveValidatorInstruction(
	// Parameters:
	removeValidator ag_solanago.PublicKey,
	// Accounts:
	stakeManager ag_solanago.PublicKey,
	admin ag_solanago.PublicKey) *RemoveValidator {
	return NewRemoveValidatorInstructionBuilder().
		SetRemoveValidator(removeValidator).
		SetStakeManagerAccount(stakeManager).
		SetAdminAccount(admin)
}
