// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package lsd_program

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// SetPlatformFeeCommission is the `setPlatformFeeCommission` instruction.
type SetPlatformFeeCommission struct {
	ProtocolFeeCommission *uint64

	// [0] = [WRITE] stakeManager
	//
	// [1] = [SIGNER] admin
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewSetPlatformFeeCommissionInstructionBuilder creates a new `SetPlatformFeeCommission` instruction builder.
func NewSetPlatformFeeCommissionInstructionBuilder() *SetPlatformFeeCommission {
	nd := &SetPlatformFeeCommission{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 2),
	}
	return nd
}

// SetProtocolFeeCommission sets the "protocolFeeCommission" parameter.
func (inst *SetPlatformFeeCommission) SetProtocolFeeCommission(protocolFeeCommission uint64) *SetPlatformFeeCommission {
	inst.ProtocolFeeCommission = &protocolFeeCommission
	return inst
}

// SetStakeManagerAccount sets the "stakeManager" account.
func (inst *SetPlatformFeeCommission) SetStakeManagerAccount(stakeManager ag_solanago.PublicKey) *SetPlatformFeeCommission {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(stakeManager).WRITE()
	return inst
}

// GetStakeManagerAccount gets the "stakeManager" account.
func (inst *SetPlatformFeeCommission) GetStakeManagerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetAdminAccount sets the "admin" account.
func (inst *SetPlatformFeeCommission) SetAdminAccount(admin ag_solanago.PublicKey) *SetPlatformFeeCommission {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(admin).SIGNER()
	return inst
}

// GetAdminAccount gets the "admin" account.
func (inst *SetPlatformFeeCommission) GetAdminAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

func (inst SetPlatformFeeCommission) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_SetPlatformFeeCommission,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst SetPlatformFeeCommission) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *SetPlatformFeeCommission) Validate() error {
	// Check whether all (required) parameters are set:
	{
		if inst.ProtocolFeeCommission == nil {
			return errors.New("ProtocolFeeCommission parameter is not set")
		}
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.StakeManager is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.Admin is not set")
		}
	}
	return nil
}

func (inst *SetPlatformFeeCommission) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("SetPlatformFeeCommission")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=1]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param("ProtocolFeeCommission", *inst.ProtocolFeeCommission))
					})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=2]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("stakeManager", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("       admin", inst.AccountMetaSlice.Get(1)))
					})
				})
		})
}

func (obj SetPlatformFeeCommission) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `ProtocolFeeCommission` param:
	err = encoder.Encode(obj.ProtocolFeeCommission)
	if err != nil {
		return err
	}
	return nil
}
func (obj *SetPlatformFeeCommission) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `ProtocolFeeCommission`:
	err = decoder.Decode(&obj.ProtocolFeeCommission)
	if err != nil {
		return err
	}
	return nil
}

// NewSetPlatformFeeCommissionInstruction declares a new SetPlatformFeeCommission instruction with the provided parameters and accounts.
func NewSetPlatformFeeCommissionInstruction(
	// Parameters:
	protocolFeeCommission uint64,
	// Accounts:
	stakeManager ag_solanago.PublicKey,
	admin ag_solanago.PublicKey) *SetPlatformFeeCommission {
	return NewSetPlatformFeeCommissionInstructionBuilder().
		SetProtocolFeeCommission(protocolFeeCommission).
		SetStakeManagerAccount(stakeManager).
		SetAdminAccount(admin)
}
