// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package lsd_program

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// SetRateChangeLimit is the `setRateChangeLimit` instruction.
type SetRateChangeLimit struct {
	RateChangeLimit *uint64

	// [0] = [WRITE] stakeManager
	//
	// [1] = [SIGNER] admin
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewSetRateChangeLimitInstructionBuilder creates a new `SetRateChangeLimit` instruction builder.
func NewSetRateChangeLimitInstructionBuilder() *SetRateChangeLimit {
	nd := &SetRateChangeLimit{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 2),
	}
	return nd
}

// SetRateChangeLimit sets the "rateChangeLimit" parameter.
func (inst *SetRateChangeLimit) SetRateChangeLimit(rateChangeLimit uint64) *SetRateChangeLimit {
	inst.RateChangeLimit = &rateChangeLimit
	return inst
}

// SetStakeManagerAccount sets the "stakeManager" account.
func (inst *SetRateChangeLimit) SetStakeManagerAccount(stakeManager ag_solanago.PublicKey) *SetRateChangeLimit {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(stakeManager).WRITE()
	return inst
}

// GetStakeManagerAccount gets the "stakeManager" account.
func (inst *SetRateChangeLimit) GetStakeManagerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetAdminAccount sets the "admin" account.
func (inst *SetRateChangeLimit) SetAdminAccount(admin ag_solanago.PublicKey) *SetRateChangeLimit {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(admin).SIGNER()
	return inst
}

// GetAdminAccount gets the "admin" account.
func (inst *SetRateChangeLimit) GetAdminAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

func (inst SetRateChangeLimit) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_SetRateChangeLimit,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst SetRateChangeLimit) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *SetRateChangeLimit) Validate() error {
	// Check whether all (required) parameters are set:
	{
		if inst.RateChangeLimit == nil {
			return errors.New("RateChangeLimit parameter is not set")
		}
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.StakeManager is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.Admin is not set")
		}
	}
	return nil
}

func (inst *SetRateChangeLimit) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("SetRateChangeLimit")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=1]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param("RateChangeLimit", *inst.RateChangeLimit))
					})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=2]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("stakeManager", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("       admin", inst.AccountMetaSlice.Get(1)))
					})
				})
		})
}

func (obj SetRateChangeLimit) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `RateChangeLimit` param:
	err = encoder.Encode(obj.RateChangeLimit)
	if err != nil {
		return err
	}
	return nil
}
func (obj *SetRateChangeLimit) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `RateChangeLimit`:
	err = decoder.Decode(&obj.RateChangeLimit)
	if err != nil {
		return err
	}
	return nil
}

// NewSetRateChangeLimitInstruction declares a new SetRateChangeLimit instruction with the provided parameters and accounts.
func NewSetRateChangeLimitInstruction(
	// Parameters:
	rateChangeLimit uint64,
	// Accounts:
	stakeManager ag_solanago.PublicKey,
	admin ag_solanago.PublicKey) *SetRateChangeLimit {
	return NewSetRateChangeLimitInstructionBuilder().
		SetRateChangeLimit(rateChangeLimit).
		SetStakeManagerAccount(stakeManager).
		SetAdminAccount(admin)
}
