// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package lsd_program

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// SetUnbondingDuration is the `setUnbondingDuration` instruction.
type SetUnbondingDuration struct {
	Duration *uint64

	// [0] = [WRITE] stakeManager
	//
	// [1] = [SIGNER] admin
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewSetUnbondingDurationInstructionBuilder creates a new `SetUnbondingDuration` instruction builder.
func NewSetUnbondingDurationInstructionBuilder() *SetUnbondingDuration {
	nd := &SetUnbondingDuration{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 2),
	}
	return nd
}

// SetDuration sets the "duration" parameter.
func (inst *SetUnbondingDuration) SetDuration(duration uint64) *SetUnbondingDuration {
	inst.Duration = &duration
	return inst
}

// SetStakeManagerAccount sets the "stakeManager" account.
func (inst *SetUnbondingDuration) SetStakeManagerAccount(stakeManager ag_solanago.PublicKey) *SetUnbondingDuration {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(stakeManager).WRITE()
	return inst
}

// GetStakeManagerAccount gets the "stakeManager" account.
func (inst *SetUnbondingDuration) GetStakeManagerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetAdminAccount sets the "admin" account.
func (inst *SetUnbondingDuration) SetAdminAccount(admin ag_solanago.PublicKey) *SetUnbondingDuration {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(admin).SIGNER()
	return inst
}

// GetAdminAccount gets the "admin" account.
func (inst *SetUnbondingDuration) GetAdminAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

func (inst SetUnbondingDuration) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_SetUnbondingDuration,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst SetUnbondingDuration) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *SetUnbondingDuration) Validate() error {
	// Check whether all (required) parameters are set:
	{
		if inst.Duration == nil {
			return errors.New("Duration parameter is not set")
		}
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.StakeManager is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.Admin is not set")
		}
	}
	return nil
}

func (inst *SetUnbondingDuration) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("SetUnbondingDuration")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=1]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param("Duration", *inst.Duration))
					})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=2]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("stakeManager", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("       admin", inst.AccountMetaSlice.Get(1)))
					})
				})
		})
}

func (obj SetUnbondingDuration) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `Duration` param:
	err = encoder.Encode(obj.Duration)
	if err != nil {
		return err
	}
	return nil
}
func (obj *SetUnbondingDuration) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `Duration`:
	err = decoder.Decode(&obj.Duration)
	if err != nil {
		return err
	}
	return nil
}

// NewSetUnbondingDurationInstruction declares a new SetUnbondingDuration instruction with the provided parameters and accounts.
func NewSetUnbondingDurationInstruction(
	// Parameters:
	duration uint64,
	// Accounts:
	stakeManager ag_solanago.PublicKey,
	admin ag_solanago.PublicKey) *SetUnbondingDuration {
	return NewSetUnbondingDurationInstructionBuilder().
		SetDuration(duration).
		SetStakeManagerAccount(stakeManager).
		SetAdminAccount(admin)
}
