// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package lsd_program

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// Stake is the `stake` instruction.
type Stake struct {
	StakeAmount *uint64

	// [0] = [WRITE] stakeManager
	//
	// [1] = [WRITE] stakePool
	//
	// [2] = [WRITE, SIGNER] from
	//
	// [3] = [WRITE] lsdTokenMint
	//
	// [4] = [WRITE] mintTo
	//
	// [5] = [] systemProgram
	//
	// [6] = [] tokenProgram
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewStakeInstructionBuilder creates a new `Stake` instruction builder.
func NewStakeInstructionBuilder() *Stake {
	nd := &Stake{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 7),
	}
	return nd
}

// SetStakeAmount sets the "stakeAmount" parameter.
func (inst *Stake) SetStakeAmount(stakeAmount uint64) *Stake {
	inst.StakeAmount = &stakeAmount
	return inst
}

// SetStakeManagerAccount sets the "stakeManager" account.
func (inst *Stake) SetStakeManagerAccount(stakeManager ag_solanago.PublicKey) *Stake {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(stakeManager).WRITE()
	return inst
}

// GetStakeManagerAccount gets the "stakeManager" account.
func (inst *Stake) GetStakeManagerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetStakePoolAccount sets the "stakePool" account.
func (inst *Stake) SetStakePoolAccount(stakePool ag_solanago.PublicKey) *Stake {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(stakePool).WRITE()
	return inst
}

// GetStakePoolAccount gets the "stakePool" account.
func (inst *Stake) GetStakePoolAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

// SetFromAccount sets the "from" account.
func (inst *Stake) SetFromAccount(from ag_solanago.PublicKey) *Stake {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(from).WRITE().SIGNER()
	return inst
}

// GetFromAccount gets the "from" account.
func (inst *Stake) GetFromAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(2)
}

// SetLsdTokenMintAccount sets the "lsdTokenMint" account.
func (inst *Stake) SetLsdTokenMintAccount(lsdTokenMint ag_solanago.PublicKey) *Stake {
	inst.AccountMetaSlice[3] = ag_solanago.Meta(lsdTokenMint).WRITE()
	return inst
}

// GetLsdTokenMintAccount gets the "lsdTokenMint" account.
func (inst *Stake) GetLsdTokenMintAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(3)
}

// SetMintToAccount sets the "mintTo" account.
func (inst *Stake) SetMintToAccount(mintTo ag_solanago.PublicKey) *Stake {
	inst.AccountMetaSlice[4] = ag_solanago.Meta(mintTo).WRITE()
	return inst
}

// GetMintToAccount gets the "mintTo" account.
func (inst *Stake) GetMintToAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(4)
}

// SetSystemProgramAccount sets the "systemProgram" account.
func (inst *Stake) SetSystemProgramAccount(systemProgram ag_solanago.PublicKey) *Stake {
	inst.AccountMetaSlice[5] = ag_solanago.Meta(systemProgram)
	return inst
}

// GetSystemProgramAccount gets the "systemProgram" account.
func (inst *Stake) GetSystemProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(5)
}

// SetTokenProgramAccount sets the "tokenProgram" account.
func (inst *Stake) SetTokenProgramAccount(tokenProgram ag_solanago.PublicKey) *Stake {
	inst.AccountMetaSlice[6] = ag_solanago.Meta(tokenProgram)
	return inst
}

// GetTokenProgramAccount gets the "tokenProgram" account.
func (inst *Stake) GetTokenProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(6)
}

func (inst Stake) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_Stake,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst Stake) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *Stake) Validate() error {
	// Check whether all (required) parameters are set:
	{
		if inst.StakeAmount == nil {
			return errors.New("StakeAmount parameter is not set")
		}
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.StakeManager is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.StakePool is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.From is not set")
		}
		if inst.AccountMetaSlice[3] == nil {
			return errors.New("accounts.LsdTokenMint is not set")
		}
		if inst.AccountMetaSlice[4] == nil {
			return errors.New("accounts.MintTo is not set")
		}
		if inst.AccountMetaSlice[5] == nil {
			return errors.New("accounts.SystemProgram is not set")
		}
		if inst.AccountMetaSlice[6] == nil {
			return errors.New("accounts.TokenProgram is not set")
		}
	}
	return nil
}

func (inst *Stake) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("Stake")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=1]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param("StakeAmount", *inst.StakeAmount))
					})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=7]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta(" stakeManager", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("    stakePool", inst.AccountMetaSlice.Get(1)))
						accountsBranch.Child(ag_format.Meta("         from", inst.AccountMetaSlice.Get(2)))
						accountsBranch.Child(ag_format.Meta(" lsdTokenMint", inst.AccountMetaSlice.Get(3)))
						accountsBranch.Child(ag_format.Meta("       mintTo", inst.AccountMetaSlice.Get(4)))
						accountsBranch.Child(ag_format.Meta("systemProgram", inst.AccountMetaSlice.Get(5)))
						accountsBranch.Child(ag_format.Meta(" tokenProgram", inst.AccountMetaSlice.Get(6)))
					})
				})
		})
}

func (obj Stake) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `StakeAmount` param:
	err = encoder.Encode(obj.StakeAmount)
	if err != nil {
		return err
	}
	return nil
}
func (obj *Stake) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `StakeAmount`:
	err = decoder.Decode(&obj.StakeAmount)
	if err != nil {
		return err
	}
	return nil
}

// NewStakeInstruction declares a new Stake instruction with the provided parameters and accounts.
func NewStakeInstruction(
	// Parameters:
	stakeAmount uint64,
	// Accounts:
	stakeManager ag_solanago.PublicKey,
	stakePool ag_solanago.PublicKey,
	from ag_solanago.PublicKey,
	lsdTokenMint ag_solanago.PublicKey,
	mintTo ag_solanago.PublicKey,
	systemProgram ag_solanago.PublicKey,
	tokenProgram ag_solanago.PublicKey) *Stake {
	return NewStakeInstructionBuilder().
		SetStakeAmount(stakeAmount).
		SetStakeManagerAccount(stakeManager).
		SetStakePoolAccount(stakePool).
		SetFromAccount(from).
		SetLsdTokenMintAccount(lsdTokenMint).
		SetMintToAccount(mintTo).
		SetSystemProgramAccount(systemProgram).
		SetTokenProgramAccount(tokenProgram)
}
