// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package lsd_program

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// TransferBalancer is the `transferBalancer` instruction.
type TransferBalancer struct {
	NewBalancer *ag_solanago.PublicKey

	// [0] = [WRITE] stakeManager
	//
	// [1] = [SIGNER] admin
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewTransferBalancerInstructionBuilder creates a new `TransferBalancer` instruction builder.
func NewTransferBalancerInstructionBuilder() *TransferBalancer {
	nd := &TransferBalancer{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 2),
	}
	return nd
}

// SetNewBalancer sets the "newBalancer" parameter.
func (inst *TransferBalancer) SetNewBalancer(newBalancer ag_solanago.PublicKey) *TransferBalancer {
	inst.NewBalancer = &newBalancer
	return inst
}

// SetStakeManagerAccount sets the "stakeManager" account.
func (inst *TransferBalancer) SetStakeManagerAccount(stakeManager ag_solanago.PublicKey) *TransferBalancer {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(stakeManager).WRITE()
	return inst
}

// GetStakeManagerAccount gets the "stakeManager" account.
func (inst *TransferBalancer) GetStakeManagerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetAdminAccount sets the "admin" account.
func (inst *TransferBalancer) SetAdminAccount(admin ag_solanago.PublicKey) *TransferBalancer {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(admin).SIGNER()
	return inst
}

// GetAdminAccount gets the "admin" account.
func (inst *TransferBalancer) GetAdminAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

func (inst TransferBalancer) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_TransferBalancer,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst TransferBalancer) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *TransferBalancer) Validate() error {
	// Check whether all (required) parameters are set:
	{
		if inst.NewBalancer == nil {
			return errors.New("NewBalancer parameter is not set")
		}
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.StakeManager is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.Admin is not set")
		}
	}
	return nil
}

func (inst *TransferBalancer) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("TransferBalancer")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=1]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param("NewBalancer", *inst.NewBalancer))
					})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=2]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("stakeManager", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("       admin", inst.AccountMetaSlice.Get(1)))
					})
				})
		})
}

func (obj TransferBalancer) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `NewBalancer` param:
	err = encoder.Encode(obj.NewBalancer)
	if err != nil {
		return err
	}
	return nil
}
func (obj *TransferBalancer) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `NewBalancer`:
	err = decoder.Decode(&obj.NewBalancer)
	if err != nil {
		return err
	}
	return nil
}

// NewTransferBalancerInstruction declares a new TransferBalancer instruction with the provided parameters and accounts.
func NewTransferBalancerInstruction(
	// Parameters:
	newBalancer ag_solanago.PublicKey,
	// Accounts:
	stakeManager ag_solanago.PublicKey,
	admin ag_solanago.PublicKey) *TransferBalancer {
	return NewTransferBalancerInstructionBuilder().
		SetNewBalancer(newBalancer).
		SetStakeManagerAccount(stakeManager).
		SetAdminAccount(admin)
}
