// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package lsd_program

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// TransferStackAdmin is the `transferStackAdmin` instruction.
type TransferStackAdmin struct {
	NewAdmin *ag_solanago.PublicKey

	// [0] = [WRITE] stack
	//
	// [1] = [SIGNER] admin
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewTransferStackAdminInstructionBuilder creates a new `TransferStackAdmin` instruction builder.
func NewTransferStackAdminInstructionBuilder() *TransferStackAdmin {
	nd := &TransferStackAdmin{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 2),
	}
	return nd
}

// SetNewAdmin sets the "newAdmin" parameter.
func (inst *TransferStackAdmin) SetNewAdmin(newAdmin ag_solanago.PublicKey) *TransferStackAdmin {
	inst.NewAdmin = &newAdmin
	return inst
}

// SetStackAccount sets the "stack" account.
func (inst *TransferStackAdmin) SetStackAccount(stack ag_solanago.PublicKey) *TransferStackAdmin {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(stack).WRITE()
	return inst
}

// GetStackAccount gets the "stack" account.
func (inst *TransferStackAdmin) GetStackAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetAdminAccount sets the "admin" account.
func (inst *TransferStackAdmin) SetAdminAccount(admin ag_solanago.PublicKey) *TransferStackAdmin {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(admin).SIGNER()
	return inst
}

// GetAdminAccount gets the "admin" account.
func (inst *TransferStackAdmin) GetAdminAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

func (inst TransferStackAdmin) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_TransferStackAdmin,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst TransferStackAdmin) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *TransferStackAdmin) Validate() error {
	// Check whether all (required) parameters are set:
	{
		if inst.NewAdmin == nil {
			return errors.New("NewAdmin parameter is not set")
		}
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.Stack is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.Admin is not set")
		}
	}
	return nil
}

func (inst *TransferStackAdmin) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("TransferStackAdmin")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=1]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param("NewAdmin", *inst.NewAdmin))
					})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=2]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("stack", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("admin", inst.AccountMetaSlice.Get(1)))
					})
				})
		})
}

func (obj TransferStackAdmin) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `NewAdmin` param:
	err = encoder.Encode(obj.NewAdmin)
	if err != nil {
		return err
	}
	return nil
}
func (obj *TransferStackAdmin) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `NewAdmin`:
	err = decoder.Decode(&obj.NewAdmin)
	if err != nil {
		return err
	}
	return nil
}

// NewTransferStackAdminInstruction declares a new TransferStackAdmin instruction with the provided parameters and accounts.
func NewTransferStackAdminInstruction(
	// Parameters:
	newAdmin ag_solanago.PublicKey,
	// Accounts:
	stack ag_solanago.PublicKey,
	admin ag_solanago.PublicKey) *TransferStackAdmin {
	return NewTransferStackAdminInstructionBuilder().
		SetNewAdmin(newAdmin).
		SetStackAccount(stack).
		SetAdminAccount(admin)
}
