// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package lsd_program

import (
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
)

type EraProcessData struct {
	NeedBond             uint64
	NeedUnbond           uint64
	OldActive            uint64
	NewActive            uint64
	PendingStakeAccounts []ag_solanago.PublicKey
}

func (obj EraProcessData) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `NeedBond` param:
	err = encoder.Encode(obj.NeedBond)
	if err != nil {
		return err
	}
	// Serialize `NeedUnbond` param:
	err = encoder.Encode(obj.NeedUnbond)
	if err != nil {
		return err
	}
	// Serialize `OldActive` param:
	err = encoder.Encode(obj.OldActive)
	if err != nil {
		return err
	}
	// Serialize `NewActive` param:
	err = encoder.Encode(obj.NewActive)
	if err != nil {
		return err
	}
	// Serialize `PendingStakeAccounts` param:
	err = encoder.Encode(obj.PendingStakeAccounts)
	if err != nil {
		return err
	}
	return nil
}

func (obj *EraProcessData) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `NeedBond`:
	err = decoder.Decode(&obj.NeedBond)
	if err != nil {
		return err
	}
	// Deserialize `NeedUnbond`:
	err = decoder.Decode(&obj.NeedUnbond)
	if err != nil {
		return err
	}
	// Deserialize `OldActive`:
	err = decoder.Decode(&obj.OldActive)
	if err != nil {
		return err
	}
	// Deserialize `NewActive`:
	err = decoder.Decode(&obj.NewActive)
	if err != nil {
		return err
	}
	// Deserialize `PendingStakeAccounts`:
	err = decoder.Decode(&obj.PendingStakeAccounts)
	if err != nil {
		return err
	}
	return nil
}

type EraRate struct {
	Era  uint64
	Rate uint64
}

func (obj EraRate) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `Era` param:
	err = encoder.Encode(obj.Era)
	if err != nil {
		return err
	}
	// Serialize `Rate` param:
	err = encoder.Encode(obj.Rate)
	if err != nil {
		return err
	}
	return nil
}

func (obj *EraRate) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `Era`:
	err = decoder.Decode(&obj.Era)
	if err != nil {
		return err
	}
	// Deserialize `Rate`:
	err = decoder.Decode(&obj.Rate)
	if err != nil {
		return err
	}
	return nil
}
