// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.
// This file contains parsers for the types defined in the IDL.

package lsd_program

import (
	"bytes"
	"fmt"
	errors "github.com/gagliardetto/anchor-go/errors"
	binary "github.com/gagliardetto/binary"
	solanago "github.com/gagliardetto/solana-go"
)

type EraProcessData struct {
	NeedBond             uint64               `json:"needBond"`
	NeedUnbond           uint64               `json:"needUnbond"`
	OldActive            uint64               `json:"oldActive"`
	NewActive            uint64               `json:"newActive"`
	PendingStakeAccounts []solanago.PublicKey `json:"pendingStakeAccounts"`
}

func (obj EraProcessData) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `NeedBond`:
	err = encoder.Encode(obj.NeedBond)
	if err != nil {
		return errors.NewField("NeedBond", err)
	}
	// Serialize `NeedUnbond`:
	err = encoder.Encode(obj.NeedUnbond)
	if err != nil {
		return errors.NewField("NeedUnbond", err)
	}
	// Serialize `OldActive`:
	err = encoder.Encode(obj.OldActive)
	if err != nil {
		return errors.NewField("OldActive", err)
	}
	// Serialize `NewActive`:
	err = encoder.Encode(obj.NewActive)
	if err != nil {
		return errors.NewField("NewActive", err)
	}
	// Serialize `PendingStakeAccounts`:
	err = encoder.Encode(obj.PendingStakeAccounts)
	if err != nil {
		return errors.NewField("PendingStakeAccounts", err)
	}
	return nil
}

func (obj EraProcessData) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding EraProcessData: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *EraProcessData) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `NeedBond`:
	err = decoder.Decode(&obj.NeedBond)
	if err != nil {
		return errors.NewField("NeedBond", err)
	}
	// Deserialize `NeedUnbond`:
	err = decoder.Decode(&obj.NeedUnbond)
	if err != nil {
		return errors.NewField("NeedUnbond", err)
	}
	// Deserialize `OldActive`:
	err = decoder.Decode(&obj.OldActive)
	if err != nil {
		return errors.NewField("OldActive", err)
	}
	// Deserialize `NewActive`:
	err = decoder.Decode(&obj.NewActive)
	if err != nil {
		return errors.NewField("NewActive", err)
	}
	// Deserialize `PendingStakeAccounts`:
	err = decoder.Decode(&obj.PendingStakeAccounts)
	if err != nil {
		return errors.NewField("PendingStakeAccounts", err)
	}
	return nil
}

func (obj *EraProcessData) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling EraProcessData: %w", err)
	}
	return nil
}

func UnmarshalEraProcessData(buf []byte) (*EraProcessData, error) {
	obj := new(EraProcessData)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type EraRate struct {
	Era  uint64 `json:"era"`
	Rate uint64 `json:"rate"`
}

func (obj EraRate) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Era`:
	err = encoder.Encode(obj.Era)
	if err != nil {
		return errors.NewField("Era", err)
	}
	// Serialize `Rate`:
	err = encoder.Encode(obj.Rate)
	if err != nil {
		return errors.NewField("Rate", err)
	}
	return nil
}

func (obj EraRate) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding EraRate: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *EraRate) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Era`:
	err = decoder.Decode(&obj.Era)
	if err != nil {
		return errors.NewField("Era", err)
	}
	// Deserialize `Rate`:
	err = decoder.Decode(&obj.Rate)
	if err != nil {
		return errors.NewField("Rate", err)
	}
	return nil
}

func (obj *EraRate) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling EraRate: %w", err)
	}
	return nil
}

func UnmarshalEraRate(buf []byte) (*EraRate, error) {
	obj := new(EraRate)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type Stack struct {
	Admin                  solanago.PublicKey   `json:"admin"`
	StackFeeCommission     uint64               `json:"stackFeeCommission"`
	StakeManagersLenLimit  uint64               `json:"stakeManagersLenLimit"`
	EntrustedStakeManagers []solanago.PublicKey `json:"entrustedStakeManagers"`
}

func (obj Stack) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Admin`:
	err = encoder.Encode(obj.Admin)
	if err != nil {
		return errors.NewField("Admin", err)
	}
	// Serialize `StackFeeCommission`:
	err = encoder.Encode(obj.StackFeeCommission)
	if err != nil {
		return errors.NewField("StackFeeCommission", err)
	}
	// Serialize `StakeManagersLenLimit`:
	err = encoder.Encode(obj.StakeManagersLenLimit)
	if err != nil {
		return errors.NewField("StakeManagersLenLimit", err)
	}
	// Serialize `EntrustedStakeManagers`:
	err = encoder.Encode(obj.EntrustedStakeManagers)
	if err != nil {
		return errors.NewField("EntrustedStakeManagers", err)
	}
	return nil
}

func (obj Stack) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding Stack: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *Stack) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Admin`:
	err = decoder.Decode(&obj.Admin)
	if err != nil {
		return errors.NewField("Admin", err)
	}
	// Deserialize `StackFeeCommission`:
	err = decoder.Decode(&obj.StackFeeCommission)
	if err != nil {
		return errors.NewField("StackFeeCommission", err)
	}
	// Deserialize `StakeManagersLenLimit`:
	err = decoder.Decode(&obj.StakeManagersLenLimit)
	if err != nil {
		return errors.NewField("StakeManagersLenLimit", err)
	}
	// Deserialize `EntrustedStakeManagers`:
	err = decoder.Decode(&obj.EntrustedStakeManagers)
	if err != nil {
		return errors.NewField("EntrustedStakeManagers", err)
	}
	return nil
}

func (obj *Stack) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling Stack: %w", err)
	}
	return nil
}

func UnmarshalStack(buf []byte) (*Stack, error) {
	obj := new(Stack)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type StakeManager struct {
	Admin                 solanago.PublicKey   `json:"admin"`
	Balancer              solanago.PublicKey   `json:"balancer"`
	Stack                 solanago.PublicKey   `json:"stack"`
	LsdTokenMint          solanago.PublicKey   `json:"lsdTokenMint"`
	PoolSeedBump          uint8                `json:"poolSeedBump"`
	RentExemptForPoolAcc  uint64               `json:"rentExemptForPoolAcc"`
	MinStakeAmount        uint64               `json:"minStakeAmount"`
	PlatformFeeCommission uint64               `json:"platformFeeCommission"`
	StackFeeCommission    uint64               `json:"stackFeeCommission"`
	RateChangeLimit       uint64               `json:"rateChangeLimit"`
	StakeAccountsLenLimit uint64               `json:"stakeAccountsLenLimit"`
	SplitAccountsLenLimit uint64               `json:"splitAccountsLenLimit"`
	UnbondingDuration     uint64               `json:"unbondingDuration"`
	LatestEra             uint64               `json:"latestEra"`
	Rate                  uint64               `json:"rate"`
	EraBond               uint64               `json:"eraBond"`
	EraUnbond             uint64               `json:"eraUnbond"`
	Active                uint64               `json:"active"`
	TotalPlatformFee      uint64               `json:"totalPlatformFee"`
	Validators            []solanago.PublicKey `json:"validators"`
	StakeAccounts         []solanago.PublicKey `json:"stakeAccounts"`
	SplitAccounts         []solanago.PublicKey `json:"splitAccounts"`
	EraRates              []EraRate            `json:"eraRates"`
	EraProcessData        EraProcessData       `json:"eraProcessData"`
}

func (obj StakeManager) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Admin`:
	err = encoder.Encode(obj.Admin)
	if err != nil {
		return errors.NewField("Admin", err)
	}
	// Serialize `Balancer`:
	err = encoder.Encode(obj.Balancer)
	if err != nil {
		return errors.NewField("Balancer", err)
	}
	// Serialize `Stack`:
	err = encoder.Encode(obj.Stack)
	if err != nil {
		return errors.NewField("Stack", err)
	}
	// Serialize `LsdTokenMint`:
	err = encoder.Encode(obj.LsdTokenMint)
	if err != nil {
		return errors.NewField("LsdTokenMint", err)
	}
	// Serialize `PoolSeedBump`:
	err = encoder.Encode(obj.PoolSeedBump)
	if err != nil {
		return errors.NewField("PoolSeedBump", err)
	}
	// Serialize `RentExemptForPoolAcc`:
	err = encoder.Encode(obj.RentExemptForPoolAcc)
	if err != nil {
		return errors.NewField("RentExemptForPoolAcc", err)
	}
	// Serialize `MinStakeAmount`:
	err = encoder.Encode(obj.MinStakeAmount)
	if err != nil {
		return errors.NewField("MinStakeAmount", err)
	}
	// Serialize `PlatformFeeCommission`:
	err = encoder.Encode(obj.PlatformFeeCommission)
	if err != nil {
		return errors.NewField("PlatformFeeCommission", err)
	}
	// Serialize `StackFeeCommission`:
	err = encoder.Encode(obj.StackFeeCommission)
	if err != nil {
		return errors.NewField("StackFeeCommission", err)
	}
	// Serialize `RateChangeLimit`:
	err = encoder.Encode(obj.RateChangeLimit)
	if err != nil {
		return errors.NewField("RateChangeLimit", err)
	}
	// Serialize `StakeAccountsLenLimit`:
	err = encoder.Encode(obj.StakeAccountsLenLimit)
	if err != nil {
		return errors.NewField("StakeAccountsLenLimit", err)
	}
	// Serialize `SplitAccountsLenLimit`:
	err = encoder.Encode(obj.SplitAccountsLenLimit)
	if err != nil {
		return errors.NewField("SplitAccountsLenLimit", err)
	}
	// Serialize `UnbondingDuration`:
	err = encoder.Encode(obj.UnbondingDuration)
	if err != nil {
		return errors.NewField("UnbondingDuration", err)
	}
	// Serialize `LatestEra`:
	err = encoder.Encode(obj.LatestEra)
	if err != nil {
		return errors.NewField("LatestEra", err)
	}
	// Serialize `Rate`:
	err = encoder.Encode(obj.Rate)
	if err != nil {
		return errors.NewField("Rate", err)
	}
	// Serialize `EraBond`:
	err = encoder.Encode(obj.EraBond)
	if err != nil {
		return errors.NewField("EraBond", err)
	}
	// Serialize `EraUnbond`:
	err = encoder.Encode(obj.EraUnbond)
	if err != nil {
		return errors.NewField("EraUnbond", err)
	}
	// Serialize `Active`:
	err = encoder.Encode(obj.Active)
	if err != nil {
		return errors.NewField("Active", err)
	}
	// Serialize `TotalPlatformFee`:
	err = encoder.Encode(obj.TotalPlatformFee)
	if err != nil {
		return errors.NewField("TotalPlatformFee", err)
	}
	// Serialize `Validators`:
	err = encoder.Encode(obj.Validators)
	if err != nil {
		return errors.NewField("Validators", err)
	}
	// Serialize `StakeAccounts`:
	err = encoder.Encode(obj.StakeAccounts)
	if err != nil {
		return errors.NewField("StakeAccounts", err)
	}
	// Serialize `SplitAccounts`:
	err = encoder.Encode(obj.SplitAccounts)
	if err != nil {
		return errors.NewField("SplitAccounts", err)
	}
	// Serialize `EraRates`:
	err = encoder.Encode(obj.EraRates)
	if err != nil {
		return errors.NewField("EraRates", err)
	}
	// Serialize `EraProcessData`:
	err = encoder.Encode(obj.EraProcessData)
	if err != nil {
		return errors.NewField("EraProcessData", err)
	}
	return nil
}

func (obj StakeManager) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding StakeManager: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *StakeManager) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Admin`:
	err = decoder.Decode(&obj.Admin)
	if err != nil {
		return errors.NewField("Admin", err)
	}
	// Deserialize `Balancer`:
	err = decoder.Decode(&obj.Balancer)
	if err != nil {
		return errors.NewField("Balancer", err)
	}
	// Deserialize `Stack`:
	err = decoder.Decode(&obj.Stack)
	if err != nil {
		return errors.NewField("Stack", err)
	}
	// Deserialize `LsdTokenMint`:
	err = decoder.Decode(&obj.LsdTokenMint)
	if err != nil {
		return errors.NewField("LsdTokenMint", err)
	}
	// Deserialize `PoolSeedBump`:
	err = decoder.Decode(&obj.PoolSeedBump)
	if err != nil {
		return errors.NewField("PoolSeedBump", err)
	}
	// Deserialize `RentExemptForPoolAcc`:
	err = decoder.Decode(&obj.RentExemptForPoolAcc)
	if err != nil {
		return errors.NewField("RentExemptForPoolAcc", err)
	}
	// Deserialize `MinStakeAmount`:
	err = decoder.Decode(&obj.MinStakeAmount)
	if err != nil {
		return errors.NewField("MinStakeAmount", err)
	}
	// Deserialize `PlatformFeeCommission`:
	err = decoder.Decode(&obj.PlatformFeeCommission)
	if err != nil {
		return errors.NewField("PlatformFeeCommission", err)
	}
	// Deserialize `StackFeeCommission`:
	err = decoder.Decode(&obj.StackFeeCommission)
	if err != nil {
		return errors.NewField("StackFeeCommission", err)
	}
	// Deserialize `RateChangeLimit`:
	err = decoder.Decode(&obj.RateChangeLimit)
	if err != nil {
		return errors.NewField("RateChangeLimit", err)
	}
	// Deserialize `StakeAccountsLenLimit`:
	err = decoder.Decode(&obj.StakeAccountsLenLimit)
	if err != nil {
		return errors.NewField("StakeAccountsLenLimit", err)
	}
	// Deserialize `SplitAccountsLenLimit`:
	err = decoder.Decode(&obj.SplitAccountsLenLimit)
	if err != nil {
		return errors.NewField("SplitAccountsLenLimit", err)
	}
	// Deserialize `UnbondingDuration`:
	err = decoder.Decode(&obj.UnbondingDuration)
	if err != nil {
		return errors.NewField("UnbondingDuration", err)
	}
	// Deserialize `LatestEra`:
	err = decoder.Decode(&obj.LatestEra)
	if err != nil {
		return errors.NewField("LatestEra", err)
	}
	// Deserialize `Rate`:
	err = decoder.Decode(&obj.Rate)
	if err != nil {
		return errors.NewField("Rate", err)
	}
	// Deserialize `EraBond`:
	err = decoder.Decode(&obj.EraBond)
	if err != nil {
		return errors.NewField("EraBond", err)
	}
	// Deserialize `EraUnbond`:
	err = decoder.Decode(&obj.EraUnbond)
	if err != nil {
		return errors.NewField("EraUnbond", err)
	}
	// Deserialize `Active`:
	err = decoder.Decode(&obj.Active)
	if err != nil {
		return errors.NewField("Active", err)
	}
	// Deserialize `TotalPlatformFee`:
	err = decoder.Decode(&obj.TotalPlatformFee)
	if err != nil {
		return errors.NewField("TotalPlatformFee", err)
	}
	// Deserialize `Validators`:
	err = decoder.Decode(&obj.Validators)
	if err != nil {
		return errors.NewField("Validators", err)
	}
	// Deserialize `StakeAccounts`:
	err = decoder.Decode(&obj.StakeAccounts)
	if err != nil {
		return errors.NewField("StakeAccounts", err)
	}
	// Deserialize `SplitAccounts`:
	err = decoder.Decode(&obj.SplitAccounts)
	if err != nil {
		return errors.NewField("SplitAccounts", err)
	}
	// Deserialize `EraRates`:
	err = decoder.Decode(&obj.EraRates)
	if err != nil {
		return errors.NewField("EraRates", err)
	}
	// Deserialize `EraProcessData`:
	err = decoder.Decode(&obj.EraProcessData)
	if err != nil {
		return errors.NewField("EraProcessData", err)
	}
	return nil
}

func (obj *StakeManager) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling StakeManager: %w", err)
	}
	return nil
}

func UnmarshalStakeManager(buf []byte) (*StakeManager, error) {
	obj := new(StakeManager)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type UnstakeAccount struct {
	StakeManager solanago.PublicKey `json:"stakeManager"`
	Recipient    solanago.PublicKey `json:"recipient"`
	Amount       uint64             `json:"amount"`
	CreatedEpoch uint64             `json:"createdEpoch"`
}

func (obj UnstakeAccount) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `StakeManager`:
	err = encoder.Encode(obj.StakeManager)
	if err != nil {
		return errors.NewField("StakeManager", err)
	}
	// Serialize `Recipient`:
	err = encoder.Encode(obj.Recipient)
	if err != nil {
		return errors.NewField("Recipient", err)
	}
	// Serialize `Amount`:
	err = encoder.Encode(obj.Amount)
	if err != nil {
		return errors.NewField("Amount", err)
	}
	// Serialize `CreatedEpoch`:
	err = encoder.Encode(obj.CreatedEpoch)
	if err != nil {
		return errors.NewField("CreatedEpoch", err)
	}
	return nil
}

func (obj UnstakeAccount) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding UnstakeAccount: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *UnstakeAccount) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `StakeManager`:
	err = decoder.Decode(&obj.StakeManager)
	if err != nil {
		return errors.NewField("StakeManager", err)
	}
	// Deserialize `Recipient`:
	err = decoder.Decode(&obj.Recipient)
	if err != nil {
		return errors.NewField("Recipient", err)
	}
	// Deserialize `Amount`:
	err = decoder.Decode(&obj.Amount)
	if err != nil {
		return errors.NewField("Amount", err)
	}
	// Deserialize `CreatedEpoch`:
	err = decoder.Decode(&obj.CreatedEpoch)
	if err != nil {
		return errors.NewField("CreatedEpoch", err)
	}
	return nil
}

func (obj *UnstakeAccount) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling UnstakeAccount: %w", err)
	}
	return nil
}

func UnmarshalUnstakeAccount(buf []byte) (*UnstakeAccount, error) {
	obj := new(UnstakeAccount)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type StackFeeAccount struct {
	Bump   uint8  `json:"bump"`
	Amount uint64 `json:"amount"`
}

func (obj StackFeeAccount) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Bump`:
	err = encoder.Encode(obj.Bump)
	if err != nil {
		return errors.NewField("Bump", err)
	}
	// Serialize `Amount`:
	err = encoder.Encode(obj.Amount)
	if err != nil {
		return errors.NewField("Amount", err)
	}
	return nil
}

func (obj StackFeeAccount) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding StackFeeAccount: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *StackFeeAccount) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Bump`:
	err = decoder.Decode(&obj.Bump)
	if err != nil {
		return errors.NewField("Bump", err)
	}
	// Deserialize `Amount`:
	err = decoder.Decode(&obj.Amount)
	if err != nil {
		return errors.NewField("Amount", err)
	}
	return nil
}

func (obj *StackFeeAccount) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling StackFeeAccount: %w", err)
	}
	return nil
}

func UnmarshalStackFeeAccount(buf []byte) (*StackFeeAccount, error) {
	obj := new(StackFeeAccount)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type EventEraBond struct {
	Era          uint64             `json:"era"`
	StakeAccount solanago.PublicKey `json:"stakeAccount"`
	BondAmount   uint64             `json:"bondAmount"`
}

func (obj EventEraBond) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Era`:
	err = encoder.Encode(obj.Era)
	if err != nil {
		return errors.NewField("Era", err)
	}
	// Serialize `StakeAccount`:
	err = encoder.Encode(obj.StakeAccount)
	if err != nil {
		return errors.NewField("StakeAccount", err)
	}
	// Serialize `BondAmount`:
	err = encoder.Encode(obj.BondAmount)
	if err != nil {
		return errors.NewField("BondAmount", err)
	}
	return nil
}

func (obj EventEraBond) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding EventEraBond: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *EventEraBond) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Era`:
	err = decoder.Decode(&obj.Era)
	if err != nil {
		return errors.NewField("Era", err)
	}
	// Deserialize `StakeAccount`:
	err = decoder.Decode(&obj.StakeAccount)
	if err != nil {
		return errors.NewField("StakeAccount", err)
	}
	// Deserialize `BondAmount`:
	err = decoder.Decode(&obj.BondAmount)
	if err != nil {
		return errors.NewField("BondAmount", err)
	}
	return nil
}

func (obj *EventEraBond) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling EventEraBond: %w", err)
	}
	return nil
}

func UnmarshalEventEraBond(buf []byte) (*EventEraBond, error) {
	obj := new(EventEraBond)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type EventEraMerge struct {
	SrcStakeAccount solanago.PublicKey `json:"srcStakeAccount"`
	DstStakeAccount solanago.PublicKey `json:"dstStakeAccount"`
}

func (obj EventEraMerge) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `SrcStakeAccount`:
	err = encoder.Encode(obj.SrcStakeAccount)
	if err != nil {
		return errors.NewField("SrcStakeAccount", err)
	}
	// Serialize `DstStakeAccount`:
	err = encoder.Encode(obj.DstStakeAccount)
	if err != nil {
		return errors.NewField("DstStakeAccount", err)
	}
	return nil
}

func (obj EventEraMerge) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding EventEraMerge: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *EventEraMerge) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `SrcStakeAccount`:
	err = decoder.Decode(&obj.SrcStakeAccount)
	if err != nil {
		return errors.NewField("SrcStakeAccount", err)
	}
	// Deserialize `DstStakeAccount`:
	err = decoder.Decode(&obj.DstStakeAccount)
	if err != nil {
		return errors.NewField("DstStakeAccount", err)
	}
	return nil
}

func (obj *EventEraMerge) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling EventEraMerge: %w", err)
	}
	return nil
}

func UnmarshalEventEraMerge(buf []byte) (*EventEraMerge, error) {
	obj := new(EventEraMerge)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type EventEraNew struct {
	NewEra     uint64 `json:"newEra"`
	NeedBond   uint64 `json:"needBond"`
	NeedUnbond uint64 `json:"needUnbond"`
	Active     uint64 `json:"active"`
}

func (obj EventEraNew) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `NewEra`:
	err = encoder.Encode(obj.NewEra)
	if err != nil {
		return errors.NewField("NewEra", err)
	}
	// Serialize `NeedBond`:
	err = encoder.Encode(obj.NeedBond)
	if err != nil {
		return errors.NewField("NeedBond", err)
	}
	// Serialize `NeedUnbond`:
	err = encoder.Encode(obj.NeedUnbond)
	if err != nil {
		return errors.NewField("NeedUnbond", err)
	}
	// Serialize `Active`:
	err = encoder.Encode(obj.Active)
	if err != nil {
		return errors.NewField("Active", err)
	}
	return nil
}

func (obj EventEraNew) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding EventEraNew: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *EventEraNew) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `NewEra`:
	err = decoder.Decode(&obj.NewEra)
	if err != nil {
		return errors.NewField("NewEra", err)
	}
	// Deserialize `NeedBond`:
	err = decoder.Decode(&obj.NeedBond)
	if err != nil {
		return errors.NewField("NeedBond", err)
	}
	// Deserialize `NeedUnbond`:
	err = decoder.Decode(&obj.NeedUnbond)
	if err != nil {
		return errors.NewField("NeedUnbond", err)
	}
	// Deserialize `Active`:
	err = decoder.Decode(&obj.Active)
	if err != nil {
		return errors.NewField("Active", err)
	}
	return nil
}

func (obj *EventEraNew) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling EventEraNew: %w", err)
	}
	return nil
}

func UnmarshalEventEraNew(buf []byte) (*EventEraNew, error) {
	obj := new(EventEraNew)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type EventEraSkipBond struct {
	Era            uint64 `json:"era"`
	SkipBondAmount uint64 `json:"skipBondAmount"`
}

func (obj EventEraSkipBond) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Era`:
	err = encoder.Encode(obj.Era)
	if err != nil {
		return errors.NewField("Era", err)
	}
	// Serialize `SkipBondAmount`:
	err = encoder.Encode(obj.SkipBondAmount)
	if err != nil {
		return errors.NewField("SkipBondAmount", err)
	}
	return nil
}

func (obj EventEraSkipBond) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding EventEraSkipBond: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *EventEraSkipBond) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Era`:
	err = decoder.Decode(&obj.Era)
	if err != nil {
		return errors.NewField("Era", err)
	}
	// Deserialize `SkipBondAmount`:
	err = decoder.Decode(&obj.SkipBondAmount)
	if err != nil {
		return errors.NewField("SkipBondAmount", err)
	}
	return nil
}

func (obj *EventEraSkipBond) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling EventEraSkipBond: %w", err)
	}
	return nil
}

func UnmarshalEventEraSkipBond(buf []byte) (*EventEraSkipBond, error) {
	obj := new(EventEraSkipBond)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type EventEraUnbond struct {
	Era              uint64             `json:"era"`
	FromStakeAccount solanago.PublicKey `json:"fromStakeAccount"`
	SplitAccount     solanago.PublicKey `json:"splitAccount"`
	UnbondAmount     uint64             `json:"unbondAmount"`
}

func (obj EventEraUnbond) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Era`:
	err = encoder.Encode(obj.Era)
	if err != nil {
		return errors.NewField("Era", err)
	}
	// Serialize `FromStakeAccount`:
	err = encoder.Encode(obj.FromStakeAccount)
	if err != nil {
		return errors.NewField("FromStakeAccount", err)
	}
	// Serialize `SplitAccount`:
	err = encoder.Encode(obj.SplitAccount)
	if err != nil {
		return errors.NewField("SplitAccount", err)
	}
	// Serialize `UnbondAmount`:
	err = encoder.Encode(obj.UnbondAmount)
	if err != nil {
		return errors.NewField("UnbondAmount", err)
	}
	return nil
}

func (obj EventEraUnbond) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding EventEraUnbond: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *EventEraUnbond) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Era`:
	err = decoder.Decode(&obj.Era)
	if err != nil {
		return errors.NewField("Era", err)
	}
	// Deserialize `FromStakeAccount`:
	err = decoder.Decode(&obj.FromStakeAccount)
	if err != nil {
		return errors.NewField("FromStakeAccount", err)
	}
	// Deserialize `SplitAccount`:
	err = decoder.Decode(&obj.SplitAccount)
	if err != nil {
		return errors.NewField("SplitAccount", err)
	}
	// Deserialize `UnbondAmount`:
	err = decoder.Decode(&obj.UnbondAmount)
	if err != nil {
		return errors.NewField("UnbondAmount", err)
	}
	return nil
}

func (obj *EventEraUnbond) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling EventEraUnbond: %w", err)
	}
	return nil
}

func UnmarshalEventEraUnbond(buf []byte) (*EventEraUnbond, error) {
	obj := new(EventEraUnbond)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type EventEraUpdateActive struct {
	Era          uint64             `json:"era"`
	StakeAccount solanago.PublicKey `json:"stakeAccount"`
	StakeAmount  uint64             `json:"stakeAmount"`
}

func (obj EventEraUpdateActive) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Era`:
	err = encoder.Encode(obj.Era)
	if err != nil {
		return errors.NewField("Era", err)
	}
	// Serialize `StakeAccount`:
	err = encoder.Encode(obj.StakeAccount)
	if err != nil {
		return errors.NewField("StakeAccount", err)
	}
	// Serialize `StakeAmount`:
	err = encoder.Encode(obj.StakeAmount)
	if err != nil {
		return errors.NewField("StakeAmount", err)
	}
	return nil
}

func (obj EventEraUpdateActive) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding EventEraUpdateActive: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *EventEraUpdateActive) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Era`:
	err = decoder.Decode(&obj.Era)
	if err != nil {
		return errors.NewField("Era", err)
	}
	// Deserialize `StakeAccount`:
	err = decoder.Decode(&obj.StakeAccount)
	if err != nil {
		return errors.NewField("StakeAccount", err)
	}
	// Deserialize `StakeAmount`:
	err = decoder.Decode(&obj.StakeAmount)
	if err != nil {
		return errors.NewField("StakeAmount", err)
	}
	return nil
}

func (obj *EventEraUpdateActive) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling EventEraUpdateActive: %w", err)
	}
	return nil
}

func UnmarshalEventEraUpdateActive(buf []byte) (*EventEraUpdateActive, error) {
	obj := new(EventEraUpdateActive)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type EventEraUpdateRate struct {
	Era         uint64 `json:"era"`
	Rate        uint64 `json:"rate"`
	PlatformFee uint64 `json:"platformFee"`
	StackFee    uint64 `json:"stackFee"`
}

func (obj EventEraUpdateRate) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Era`:
	err = encoder.Encode(obj.Era)
	if err != nil {
		return errors.NewField("Era", err)
	}
	// Serialize `Rate`:
	err = encoder.Encode(obj.Rate)
	if err != nil {
		return errors.NewField("Rate", err)
	}
	// Serialize `PlatformFee`:
	err = encoder.Encode(obj.PlatformFee)
	if err != nil {
		return errors.NewField("PlatformFee", err)
	}
	// Serialize `StackFee`:
	err = encoder.Encode(obj.StackFee)
	if err != nil {
		return errors.NewField("StackFee", err)
	}
	return nil
}

func (obj EventEraUpdateRate) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding EventEraUpdateRate: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *EventEraUpdateRate) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Era`:
	err = decoder.Decode(&obj.Era)
	if err != nil {
		return errors.NewField("Era", err)
	}
	// Deserialize `Rate`:
	err = decoder.Decode(&obj.Rate)
	if err != nil {
		return errors.NewField("Rate", err)
	}
	// Deserialize `PlatformFee`:
	err = decoder.Decode(&obj.PlatformFee)
	if err != nil {
		return errors.NewField("PlatformFee", err)
	}
	// Deserialize `StackFee`:
	err = decoder.Decode(&obj.StackFee)
	if err != nil {
		return errors.NewField("StackFee", err)
	}
	return nil
}

func (obj *EventEraUpdateRate) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling EventEraUpdateRate: %w", err)
	}
	return nil
}

func UnmarshalEventEraUpdateRate(buf []byte) (*EventEraUpdateRate, error) {
	obj := new(EventEraUpdateRate)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type EventEraWithdraw struct {
	Era            uint64             `json:"era"`
	StakeAccount   solanago.PublicKey `json:"stakeAccount"`
	WithdrawAmount uint64             `json:"withdrawAmount"`
}

func (obj EventEraWithdraw) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Era`:
	err = encoder.Encode(obj.Era)
	if err != nil {
		return errors.NewField("Era", err)
	}
	// Serialize `StakeAccount`:
	err = encoder.Encode(obj.StakeAccount)
	if err != nil {
		return errors.NewField("StakeAccount", err)
	}
	// Serialize `WithdrawAmount`:
	err = encoder.Encode(obj.WithdrawAmount)
	if err != nil {
		return errors.NewField("WithdrawAmount", err)
	}
	return nil
}

func (obj EventEraWithdraw) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding EventEraWithdraw: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *EventEraWithdraw) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Era`:
	err = decoder.Decode(&obj.Era)
	if err != nil {
		return errors.NewField("Era", err)
	}
	// Deserialize `StakeAccount`:
	err = decoder.Decode(&obj.StakeAccount)
	if err != nil {
		return errors.NewField("StakeAccount", err)
	}
	// Deserialize `WithdrawAmount`:
	err = decoder.Decode(&obj.WithdrawAmount)
	if err != nil {
		return errors.NewField("WithdrawAmount", err)
	}
	return nil
}

func (obj *EventEraWithdraw) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling EventEraWithdraw: %w", err)
	}
	return nil
}

func UnmarshalEventEraWithdraw(buf []byte) (*EventEraWithdraw, error) {
	obj := new(EventEraWithdraw)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type EventRedelegate struct {
	FromStakeAccount solanago.PublicKey `json:"fromStakeAccount"`
	ToStakeAccount   solanago.PublicKey `json:"toStakeAccount"`
	RedelegateAmount uint64             `json:"redelegateAmount"`
}

func (obj EventRedelegate) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `FromStakeAccount`:
	err = encoder.Encode(obj.FromStakeAccount)
	if err != nil {
		return errors.NewField("FromStakeAccount", err)
	}
	// Serialize `ToStakeAccount`:
	err = encoder.Encode(obj.ToStakeAccount)
	if err != nil {
		return errors.NewField("ToStakeAccount", err)
	}
	// Serialize `RedelegateAmount`:
	err = encoder.Encode(obj.RedelegateAmount)
	if err != nil {
		return errors.NewField("RedelegateAmount", err)
	}
	return nil
}

func (obj EventRedelegate) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding EventRedelegate: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *EventRedelegate) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `FromStakeAccount`:
	err = decoder.Decode(&obj.FromStakeAccount)
	if err != nil {
		return errors.NewField("FromStakeAccount", err)
	}
	// Deserialize `ToStakeAccount`:
	err = decoder.Decode(&obj.ToStakeAccount)
	if err != nil {
		return errors.NewField("ToStakeAccount", err)
	}
	// Deserialize `RedelegateAmount`:
	err = decoder.Decode(&obj.RedelegateAmount)
	if err != nil {
		return errors.NewField("RedelegateAmount", err)
	}
	return nil
}

func (obj *EventRedelegate) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling EventRedelegate: %w", err)
	}
	return nil
}

func UnmarshalEventRedelegate(buf []byte) (*EventRedelegate, error) {
	obj := new(EventRedelegate)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type EventStake struct {
	Era            uint64             `json:"era"`
	Staker         solanago.PublicKey `json:"staker"`
	MintTo         solanago.PublicKey `json:"mintTo"`
	StakeAmount    uint64             `json:"stakeAmount"`
	LsdTokenAmount uint64             `json:"lsdTokenAmount"`
}

func (obj EventStake) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Era`:
	err = encoder.Encode(obj.Era)
	if err != nil {
		return errors.NewField("Era", err)
	}
	// Serialize `Staker`:
	err = encoder.Encode(obj.Staker)
	if err != nil {
		return errors.NewField("Staker", err)
	}
	// Serialize `MintTo`:
	err = encoder.Encode(obj.MintTo)
	if err != nil {
		return errors.NewField("MintTo", err)
	}
	// Serialize `StakeAmount`:
	err = encoder.Encode(obj.StakeAmount)
	if err != nil {
		return errors.NewField("StakeAmount", err)
	}
	// Serialize `LsdTokenAmount`:
	err = encoder.Encode(obj.LsdTokenAmount)
	if err != nil {
		return errors.NewField("LsdTokenAmount", err)
	}
	return nil
}

func (obj EventStake) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding EventStake: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *EventStake) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Era`:
	err = decoder.Decode(&obj.Era)
	if err != nil {
		return errors.NewField("Era", err)
	}
	// Deserialize `Staker`:
	err = decoder.Decode(&obj.Staker)
	if err != nil {
		return errors.NewField("Staker", err)
	}
	// Deserialize `MintTo`:
	err = decoder.Decode(&obj.MintTo)
	if err != nil {
		return errors.NewField("MintTo", err)
	}
	// Deserialize `StakeAmount`:
	err = decoder.Decode(&obj.StakeAmount)
	if err != nil {
		return errors.NewField("StakeAmount", err)
	}
	// Deserialize `LsdTokenAmount`:
	err = decoder.Decode(&obj.LsdTokenAmount)
	if err != nil {
		return errors.NewField("LsdTokenAmount", err)
	}
	return nil
}

func (obj *EventStake) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling EventStake: %w", err)
	}
	return nil
}

func UnmarshalEventStake(buf []byte) (*EventStake, error) {
	obj := new(EventStake)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type EventUnstake struct {
	Era              uint64             `json:"era"`
	Staker           solanago.PublicKey `json:"staker"`
	BurnLsdTokenFrom solanago.PublicKey `json:"burnLsdTokenFrom"`
	UnstakeAccount   solanago.PublicKey `json:"unstakeAccount"`
	UnstakeAmount    uint64             `json:"unstakeAmount"`
	SolAmount        uint64             `json:"solAmount"`
}

func (obj EventUnstake) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Era`:
	err = encoder.Encode(obj.Era)
	if err != nil {
		return errors.NewField("Era", err)
	}
	// Serialize `Staker`:
	err = encoder.Encode(obj.Staker)
	if err != nil {
		return errors.NewField("Staker", err)
	}
	// Serialize `BurnLsdTokenFrom`:
	err = encoder.Encode(obj.BurnLsdTokenFrom)
	if err != nil {
		return errors.NewField("BurnLsdTokenFrom", err)
	}
	// Serialize `UnstakeAccount`:
	err = encoder.Encode(obj.UnstakeAccount)
	if err != nil {
		return errors.NewField("UnstakeAccount", err)
	}
	// Serialize `UnstakeAmount`:
	err = encoder.Encode(obj.UnstakeAmount)
	if err != nil {
		return errors.NewField("UnstakeAmount", err)
	}
	// Serialize `SolAmount`:
	err = encoder.Encode(obj.SolAmount)
	if err != nil {
		return errors.NewField("SolAmount", err)
	}
	return nil
}

func (obj EventUnstake) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding EventUnstake: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *EventUnstake) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Era`:
	err = decoder.Decode(&obj.Era)
	if err != nil {
		return errors.NewField("Era", err)
	}
	// Deserialize `Staker`:
	err = decoder.Decode(&obj.Staker)
	if err != nil {
		return errors.NewField("Staker", err)
	}
	// Deserialize `BurnLsdTokenFrom`:
	err = decoder.Decode(&obj.BurnLsdTokenFrom)
	if err != nil {
		return errors.NewField("BurnLsdTokenFrom", err)
	}
	// Deserialize `UnstakeAccount`:
	err = decoder.Decode(&obj.UnstakeAccount)
	if err != nil {
		return errors.NewField("UnstakeAccount", err)
	}
	// Deserialize `UnstakeAmount`:
	err = decoder.Decode(&obj.UnstakeAmount)
	if err != nil {
		return errors.NewField("UnstakeAmount", err)
	}
	// Deserialize `SolAmount`:
	err = decoder.Decode(&obj.SolAmount)
	if err != nil {
		return errors.NewField("SolAmount", err)
	}
	return nil
}

func (obj *EventUnstake) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling EventUnstake: %w", err)
	}
	return nil
}

func UnmarshalEventUnstake(buf []byte) (*EventUnstake, error) {
	obj := new(EventUnstake)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}

type EventWithdraw struct {
	Era            uint64             `json:"era"`
	Staker         solanago.PublicKey `json:"staker"`
	UnstakeAccount solanago.PublicKey `json:"unstakeAccount"`
	WithdrawAmount uint64             `json:"withdrawAmount"`
}

func (obj EventWithdraw) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	// Serialize `Era`:
	err = encoder.Encode(obj.Era)
	if err != nil {
		return errors.NewField("Era", err)
	}
	// Serialize `Staker`:
	err = encoder.Encode(obj.Staker)
	if err != nil {
		return errors.NewField("Staker", err)
	}
	// Serialize `UnstakeAccount`:
	err = encoder.Encode(obj.UnstakeAccount)
	if err != nil {
		return errors.NewField("UnstakeAccount", err)
	}
	// Serialize `WithdrawAmount`:
	err = encoder.Encode(obj.WithdrawAmount)
	if err != nil {
		return errors.NewField("WithdrawAmount", err)
	}
	return nil
}

func (obj EventWithdraw) Marshal() ([]byte, error) {
	buf := bytes.NewBuffer(nil)
	encoder := binary.NewBorshEncoder(buf)
	err := obj.MarshalWithEncoder(encoder)
	if err != nil {
		return nil, fmt.Errorf("error while encoding EventWithdraw: %w", err)
	}
	return buf.Bytes(), nil
}

func (obj *EventWithdraw) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	// Deserialize `Era`:
	err = decoder.Decode(&obj.Era)
	if err != nil {
		return errors.NewField("Era", err)
	}
	// Deserialize `Staker`:
	err = decoder.Decode(&obj.Staker)
	if err != nil {
		return errors.NewField("Staker", err)
	}
	// Deserialize `UnstakeAccount`:
	err = decoder.Decode(&obj.UnstakeAccount)
	if err != nil {
		return errors.NewField("UnstakeAccount", err)
	}
	// Deserialize `WithdrawAmount`:
	err = decoder.Decode(&obj.WithdrawAmount)
	if err != nil {
		return errors.NewField("WithdrawAmount", err)
	}
	return nil
}

func (obj *EventWithdraw) Unmarshal(buf []byte) error {
	err := obj.UnmarshalWithDecoder(binary.NewBorshDecoder(buf))
	if err != nil {
		return fmt.Errorf("error while unmarshaling EventWithdraw: %w", err)
	}
	return nil
}

func UnmarshalEventWithdraw(buf []byte) (*EventWithdraw, error) {
	obj := new(EventWithdraw)
	err := obj.Unmarshal(buf)
	if err != nil {
		return nil, err
	}
	return obj, nil
}
