// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package lsd_program

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// Withdraw is the `withdraw` instruction.
type Withdraw struct {

	// [0] = [WRITE] stakeManager
	//
	// [1] = [WRITE] stakePool
	//
	// [2] = [WRITE] unstakeAccount
	//
	// [3] = [WRITE] recipient
	//
	// [4] = [] clock
	//
	// [5] = [] systemProgram
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewWithdrawInstructionBuilder creates a new `Withdraw` instruction builder.
func NewWithdrawInstructionBuilder() *Withdraw {
	nd := &Withdraw{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 6),
	}
	return nd
}

// SetStakeManagerAccount sets the "stakeManager" account.
func (inst *Withdraw) SetStakeManagerAccount(stakeManager ag_solanago.PublicKey) *Withdraw {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(stakeManager).WRITE()
	return inst
}

// GetStakeManagerAccount gets the "stakeManager" account.
func (inst *Withdraw) GetStakeManagerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetStakePoolAccount sets the "stakePool" account.
func (inst *Withdraw) SetStakePoolAccount(stakePool ag_solanago.PublicKey) *Withdraw {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(stakePool).WRITE()
	return inst
}

// GetStakePoolAccount gets the "stakePool" account.
func (inst *Withdraw) GetStakePoolAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

// SetUnstakeAccountAccount sets the "unstakeAccount" account.
func (inst *Withdraw) SetUnstakeAccountAccount(unstakeAccount ag_solanago.PublicKey) *Withdraw {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(unstakeAccount).WRITE()
	return inst
}

// GetUnstakeAccountAccount gets the "unstakeAccount" account.
func (inst *Withdraw) GetUnstakeAccountAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(2)
}

// SetRecipientAccount sets the "recipient" account.
func (inst *Withdraw) SetRecipientAccount(recipient ag_solanago.PublicKey) *Withdraw {
	inst.AccountMetaSlice[3] = ag_solanago.Meta(recipient).WRITE()
	return inst
}

// GetRecipientAccount gets the "recipient" account.
func (inst *Withdraw) GetRecipientAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(3)
}

// SetClockAccount sets the "clock" account.
func (inst *Withdraw) SetClockAccount(clock ag_solanago.PublicKey) *Withdraw {
	inst.AccountMetaSlice[4] = ag_solanago.Meta(clock)
	return inst
}

// GetClockAccount gets the "clock" account.
func (inst *Withdraw) GetClockAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(4)
}

// SetSystemProgramAccount sets the "systemProgram" account.
func (inst *Withdraw) SetSystemProgramAccount(systemProgram ag_solanago.PublicKey) *Withdraw {
	inst.AccountMetaSlice[5] = ag_solanago.Meta(systemProgram)
	return inst
}

// GetSystemProgramAccount gets the "systemProgram" account.
func (inst *Withdraw) GetSystemProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(5)
}

func (inst Withdraw) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_Withdraw,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst Withdraw) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *Withdraw) Validate() error {
	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.StakeManager is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.StakePool is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.UnstakeAccount is not set")
		}
		if inst.AccountMetaSlice[3] == nil {
			return errors.New("accounts.Recipient is not set")
		}
		if inst.AccountMetaSlice[4] == nil {
			return errors.New("accounts.Clock is not set")
		}
		if inst.AccountMetaSlice[5] == nil {
			return errors.New("accounts.SystemProgram is not set")
		}
	}
	return nil
}

func (inst *Withdraw) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("Withdraw")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=0]").ParentFunc(func(paramsBranch ag_treeout.Branches) {})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=6]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta(" stakeManager", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("    stakePool", inst.AccountMetaSlice.Get(1)))
						accountsBranch.Child(ag_format.Meta("      unstake", inst.AccountMetaSlice.Get(2)))
						accountsBranch.Child(ag_format.Meta("    recipient", inst.AccountMetaSlice.Get(3)))
						accountsBranch.Child(ag_format.Meta("        clock", inst.AccountMetaSlice.Get(4)))
						accountsBranch.Child(ag_format.Meta("systemProgram", inst.AccountMetaSlice.Get(5)))
					})
				})
		})
}

func (obj Withdraw) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	return nil
}
func (obj *Withdraw) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	return nil
}

// NewWithdrawInstruction declares a new Withdraw instruction with the provided parameters and accounts.
func NewWithdrawInstruction(
	// Accounts:
	stakeManager ag_solanago.PublicKey,
	stakePool ag_solanago.PublicKey,
	unstakeAccount ag_solanago.PublicKey,
	recipient ag_solanago.PublicKey,
	clock ag_solanago.PublicKey,
	systemProgram ag_solanago.PublicKey) *Withdraw {
	return NewWithdrawInstructionBuilder().
		SetStakeManagerAccount(stakeManager).
		SetStakePoolAccount(stakePool).
		SetUnstakeAccountAccount(unstakeAccount).
		SetRecipientAccount(recipient).
		SetClockAccount(clock).
		SetSystemProgramAccount(systemProgram)
}
