
# Endpoint = "https://api.devnet.solana.com"
Endpoint = "https://solana-dev-rpc.stafi.io"
KeystorePath = "./keys/solana_keys.json"
# keystore will be omitted if ExportTx is enabled
ExportTx = false

StakeManagerAddress = "5T3iezF2qUNfHGSWKLm6SVfZYVE8yipRbmUzGgiQaRs4"

## signers
FeePayerAccount = "ErCsmTQhM9qt17ce8XDTasKo76FEdg2scP2UX4VLxKDb"
AdminAccount = "GgAy6GnqaPJUdGfCQGMgW2fGMMvmxc3E7a2oizFuCbhF"

# RateChangeLimit = 0
# UnbondingDuration = 8
# AddValidatorAddress   = ""
# RemoveValidatorAddress = ""
# MinStakeAmount = 0
# PlatformFeeCommission = 0
# NewBalancerAddress = ""
# NewAdminAddress = ""
