
EndpointList = ["https://api.devnet.solana.com"]
KeystorePath = "./keys/solana_keys.json"

LsdProgramID = "5N1PkgbPx5Qs3eGaJre16AHsNMRPYM9JSwxXDG83tWX9"

StackAddress = "5ou6pU6ByghiA148DokoVQLpPqGcnww9qS8TQzwcmQcx"
StakeManagerAddress = ""                                      # entrusted mode if empty

FeePayerAccount = "CCD2dZ17Gse1EEadCznr94bMNyiFsEfAmywwiFuP5G34"
