
Endpoint = "https://api.devnet.solana.com"
KeystorePath = "./keys/solana_keys.json"
LogFilePath = "./log_data"

StakeManagerAddress = "6g8ziuefcXnmP1kmCXd7CGxdQrL59CkdnH9C6vQnQYkp"

## signers
FeePayerAccount = "ErCsmTQhM9qt17ce8XDTasKo76FEdg2scP2UX4VLxKDb"
