// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package stack

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// AcceptStackAdmin is the `acceptStackAdmin` instruction.
type AcceptStackAdmin struct {

	// [0] = [SIGNER] pendingAdmin
	//
	// [1] = [WRITE] stack
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewAcceptStackAdminInstructionBuilder creates a new `AcceptStackAdmin` instruction builder.
func NewAcceptStackAdminInstructionBuilder() *AcceptStackAdmin {
	nd := &AcceptStackAdmin{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 2),
	}
	return nd
}

// SetPendingAdminAccount sets the "pendingAdmin" account.
func (inst *AcceptStackAdmin) SetPendingAdminAccount(pendingAdmin ag_solanago.PublicKey) *AcceptStackAdmin {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(pendingAdmin).SIGNER()
	return inst
}

// GetPendingAdminAccount gets the "pendingAdmin" account.
func (inst *AcceptStackAdmin) GetPendingAdminAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetStackAccount sets the "stack" account.
func (inst *AcceptStackAdmin) SetStackAccount(stack ag_solanago.PublicKey) *AcceptStackAdmin {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(stack).WRITE()
	return inst
}

// GetStackAccount gets the "stack" account.
func (inst *AcceptStackAdmin) GetStackAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

func (inst AcceptStackAdmin) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_AcceptStackAdmin,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst AcceptStackAdmin) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *AcceptStackAdmin) Validate() error {
	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.PendingAdmin is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.Stack is not set")
		}
	}
	return nil
}

func (inst *AcceptStackAdmin) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("AcceptStackAdmin")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=0]").ParentFunc(func(paramsBranch ag_treeout.Branches) {})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=2]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("pendingAdmin", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("       stack", inst.AccountMetaSlice.Get(1)))
					})
				})
		})
}

func (obj AcceptStackAdmin) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	return nil
}
func (obj *AcceptStackAdmin) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	return nil
}

// NewAcceptStackAdminInstruction declares a new AcceptStackAdmin instruction with the provided parameters and accounts.
func NewAcceptStackAdminInstruction(
	// Accounts:
	pendingAdmin ag_solanago.PublicKey,
	stack ag_solanago.PublicKey) *AcceptStackAdmin {
	return NewAcceptStackAdminInstructionBuilder().
		SetPendingAdminAccount(pendingAdmin).
		SetStackAccount(stack)
}
