// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package stack

import (
	"fmt"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
)

type Stack struct {
	Admin                  ag_solanago.PublicKey
	PendingAdmin           ag_solanago.PublicKey
	StackFeeCommission     uint64
	StakeManagersLenLimit  uint64
	EntrustedStakeManagers []ag_solanago.PublicKey
}

var StackDiscriminator = [8]byte{58, 70, 168, 244, 188, 169, 129, 79}

func (obj Stack) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Write account discriminator:
	err = encoder.WriteBytes(StackDiscriminator[:], false)
	if err != nil {
		return err
	}
	// Serialize `Admin` param:
	err = encoder.Encode(obj.Admin)
	if err != nil {
		return err
	}
	// Serialize `PendingAdmin` param:
	err = encoder.Encode(obj.PendingAdmin)
	if err != nil {
		return err
	}
	// Serialize `StackFeeCommission` param:
	err = encoder.Encode(obj.StackFeeCommission)
	if err != nil {
		return err
	}
	// Serialize `StakeManagersLenLimit` param:
	err = encoder.Encode(obj.StakeManagersLenLimit)
	if err != nil {
		return err
	}
	// Serialize `EntrustedStakeManagers` param:
	err = encoder.Encode(obj.EntrustedStakeManagers)
	if err != nil {
		return err
	}
	return nil
}

func (obj *Stack) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Read and check account discriminator:
	{
		discriminator, err := decoder.ReadTypeID()
		if err != nil {
			return err
		}
		if !discriminator.Equal(StackDiscriminator[:]) {
			return fmt.Errorf(
				"wrong discriminator: wanted %s, got %s",
				"[58 70 168 244 188 169 129 79]",
				fmt.Sprint(discriminator[:]))
		}
	}
	// Deserialize `Admin`:
	err = decoder.Decode(&obj.Admin)
	if err != nil {
		return err
	}
	// Deserialize `PendingAdmin`:
	err = decoder.Decode(&obj.PendingAdmin)
	if err != nil {
		return err
	}
	// Deserialize `StackFeeCommission`:
	err = decoder.Decode(&obj.StackFeeCommission)
	if err != nil {
		return err
	}
	// Deserialize `StakeManagersLenLimit`:
	err = decoder.Decode(&obj.StakeManagersLenLimit)
	if err != nil {
		return err
	}
	// Deserialize `EntrustedStakeManagers`:
	err = decoder.Decode(&obj.EntrustedStakeManagers)
	if err != nil {
		return err
	}
	return nil
}
