// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package stack

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// InitializeStack is the `initializeStack` instruction.
type InitializeStack struct {
	StackIndex *uint8

	// [0] = [WRITE] stack
	//
	// [1] = [WRITE, SIGNER] rentPayer
	//
	// [2] = [SIGNER] admin
	//
	// [3] = [] systemProgram
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewInitializeStackInstructionBuilder creates a new `InitializeStack` instruction builder.
func NewInitializeStackInstructionBuilder() *InitializeStack {
	nd := &InitializeStack{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 4),
	}
	return nd
}

// SetStackIndex sets the "stackIndex" parameter.
func (inst *InitializeStack) SetStackIndex(stackIndex uint8) *InitializeStack {
	inst.StackIndex = &stackIndex
	return inst
}

// SetStackAccount sets the "stack" account.
func (inst *InitializeStack) SetStackAccount(stack ag_solanago.PublicKey) *InitializeStack {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(stack).WRITE()
	return inst
}

// GetStackAccount gets the "stack" account.
func (inst *InitializeStack) GetStackAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetRentPayerAccount sets the "rentPayer" account.
func (inst *InitializeStack) SetRentPayerAccount(rentPayer ag_solanago.PublicKey) *InitializeStack {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(rentPayer).WRITE().SIGNER()
	return inst
}

// GetRentPayerAccount gets the "rentPayer" account.
func (inst *InitializeStack) GetRentPayerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

// SetAdminAccount sets the "admin" account.
func (inst *InitializeStack) SetAdminAccount(admin ag_solanago.PublicKey) *InitializeStack {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(admin).SIGNER()
	return inst
}

// GetAdminAccount gets the "admin" account.
func (inst *InitializeStack) GetAdminAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(2)
}

// SetSystemProgramAccount sets the "systemProgram" account.
func (inst *InitializeStack) SetSystemProgramAccount(systemProgram ag_solanago.PublicKey) *InitializeStack {
	inst.AccountMetaSlice[3] = ag_solanago.Meta(systemProgram)
	return inst
}

// GetSystemProgramAccount gets the "systemProgram" account.
func (inst *InitializeStack) GetSystemProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(3)
}

func (inst InitializeStack) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_InitializeStack,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst InitializeStack) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *InitializeStack) Validate() error {
	// Check whether all (required) parameters are set:
	{
		if inst.StackIndex == nil {
			return errors.New("StackIndex parameter is not set")
		}
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.Stack is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.RentPayer is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.Admin is not set")
		}
		if inst.AccountMetaSlice[3] == nil {
			return errors.New("accounts.SystemProgram is not set")
		}
	}
	return nil
}

func (inst *InitializeStack) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("InitializeStack")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=1]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param("StackIndex", *inst.StackIndex))
					})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=4]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("        stack", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("    rentPayer", inst.AccountMetaSlice.Get(1)))
						accountsBranch.Child(ag_format.Meta("        admin", inst.AccountMetaSlice.Get(2)))
						accountsBranch.Child(ag_format.Meta("systemProgram", inst.AccountMetaSlice.Get(3)))
					})
				})
		})
}

func (obj InitializeStack) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `StackIndex` param:
	err = encoder.Encode(obj.StackIndex)
	if err != nil {
		return err
	}
	return nil
}
func (obj *InitializeStack) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `StackIndex`:
	err = decoder.Decode(&obj.StackIndex)
	if err != nil {
		return err
	}
	return nil
}

// NewInitializeStackInstruction declares a new InitializeStack instruction with the provided parameters and accounts.
func NewInitializeStackInstruction(
	// Parameters:
	stackIndex uint8,
	// Accounts:
	stack ag_solanago.PublicKey,
	rentPayer ag_solanago.PublicKey,
	admin ag_solanago.PublicKey,
	systemProgram ag_solanago.PublicKey) *InitializeStack {
	return NewInitializeStackInstructionBuilder().
		SetStackIndex(stackIndex).
		SetStackAccount(stack).
		SetRentPayerAccount(rentPayer).
		SetAdminAccount(admin).
		SetSystemProgramAccount(systemProgram)
}
