// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package stack

import (
	"bytes"
	"fmt"
	ag_spew "github.com/davecgh/go-spew/spew"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_text "github.com/gagliardetto/solana-go/text"
	ag_treeout "github.com/gagliardetto/treeout"
)

var ProgramID ag_solanago.PublicKey

func SetProgramID(pubkey ag_solanago.PublicKey) {
	ProgramID = pubkey
	ag_solanago.RegisterInstructionDecoder(ProgramID, registryDecodeInstruction)
}

const ProgramName = "Stack"

func init() {
	if !ProgramID.IsZero() {
		ag_solanago.RegisterInstructionDecoder(ProgramID, registryDecodeInstruction)
	}
}

var (
	Instruction_InitializeStack = ag_binary.TypeID([8]byte{139, 248, 249, 177, 239, 66, 51, 252})

	Instruction_TransferStackAdmin = ag_binary.TypeID([8]byte{239, 183, 112, 103, 100, 99, 128, 84})

	Instruction_AcceptStackAdmin = ag_binary.TypeID([8]byte{149, 67, 170, 219, 80, 71, 184, 107})

	Instruction_SetStackFeeCommission = ag_binary.TypeID([8]byte{170, 16, 193, 90, 33, 62, 62, 97})

	Instruction_AddEntrustedStakeManager = ag_binary.TypeID([8]byte{81, 65, 28, 165, 239, 10, 152, 193})

	Instruction_RemoveEntrustedStakeManager = ag_binary.TypeID([8]byte{232, 175, 69, 153, 85, 181, 33, 160})
)

// InstructionIDToName returns the name of the instruction given its ID.
func InstructionIDToName(id ag_binary.TypeID) string {
	switch id {
	case Instruction_InitializeStack:
		return "InitializeStack"
	case Instruction_TransferStackAdmin:
		return "TransferStackAdmin"
	case Instruction_AcceptStackAdmin:
		return "AcceptStackAdmin"
	case Instruction_SetStackFeeCommission:
		return "SetStackFeeCommission"
	case Instruction_AddEntrustedStakeManager:
		return "AddEntrustedStakeManager"
	case Instruction_RemoveEntrustedStakeManager:
		return "RemoveEntrustedStakeManager"
	default:
		return ""
	}
}

type Instruction struct {
	ag_binary.BaseVariant
}

func (inst *Instruction) EncodeToTree(parent ag_treeout.Branches) {
	if enToTree, ok := inst.Impl.(ag_text.EncodableToTree); ok {
		enToTree.EncodeToTree(parent)
	} else {
		parent.Child(ag_spew.Sdump(inst))
	}
}

var InstructionImplDef = ag_binary.NewVariantDefinition(
	ag_binary.AnchorTypeIDEncoding,
	[]ag_binary.VariantType{
		{
			"initialize_stack", (*InitializeStack)(nil),
		},
		{
			"transfer_stack_admin", (*TransferStackAdmin)(nil),
		},
		{
			"accept_stack_admin", (*AcceptStackAdmin)(nil),
		},
		{
			"set_stack_fee_commission", (*SetStackFeeCommission)(nil),
		},
		{
			"add_entrusted_stake_manager", (*AddEntrustedStakeManager)(nil),
		},
		{
			"remove_entrusted_stake_manager", (*RemoveEntrustedStakeManager)(nil),
		},
	},
)

func (inst *Instruction) ProgramID() ag_solanago.PublicKey {
	return ProgramID
}

func (inst *Instruction) Accounts() (out []*ag_solanago.AccountMeta) {
	return inst.Impl.(ag_solanago.AccountsGettable).GetAccounts()
}

func (inst *Instruction) Data() ([]byte, error) {
	buf := new(bytes.Buffer)
	if err := ag_binary.NewBorshEncoder(buf).Encode(inst); err != nil {
		return nil, fmt.Errorf("unable to encode instruction: %w", err)
	}
	return buf.Bytes(), nil
}

func (inst *Instruction) TextEncode(encoder *ag_text.Encoder, option *ag_text.Option) error {
	return encoder.Encode(inst.Impl, option)
}

func (inst *Instruction) UnmarshalWithDecoder(decoder *ag_binary.Decoder) error {
	return inst.BaseVariant.UnmarshalBinaryVariant(decoder, InstructionImplDef)
}

func (inst *Instruction) MarshalWithEncoder(encoder *ag_binary.Encoder) error {
	err := encoder.WriteBytes(inst.TypeID.Bytes(), false)
	if err != nil {
		return fmt.Errorf("unable to write variant type: %w", err)
	}
	return encoder.Encode(inst.Impl)
}

func registryDecodeInstruction(accounts []*ag_solanago.AccountMeta, data []byte) (interface{}, error) {
	inst, err := DecodeInstruction(accounts, data)
	if err != nil {
		return nil, err
	}
	return inst, nil
}

func DecodeInstruction(accounts []*ag_solanago.AccountMeta, data []byte) (*Instruction, error) {
	inst := new(Instruction)
	if err := ag_binary.NewBorshDecoder(data).Decode(inst); err != nil {
		return nil, fmt.Errorf("unable to decode instruction: %w", err)
	}
	if v, ok := inst.Impl.(ag_solanago.AccountsSettable); ok {
		err := v.SetAccounts(accounts)
		if err != nil {
			return nil, fmt.Errorf("unable to set accounts for instruction: %w", err)
		}
	}
	return inst, nil
}
