// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package stack

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// RemoveEntrustedStakeManager is the `removeEntrustedStakeManager` instruction.
type RemoveEntrustedStakeManager struct {
	StakeManager *ag_solanago.PublicKey

	// [0] = [WRITE] stack
	//
	// [1] = [SIGNER] admin
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewRemoveEntrustedStakeManagerInstructionBuilder creates a new `RemoveEntrustedStakeManager` instruction builder.
func NewRemoveEntrustedStakeManagerInstructionBuilder() *RemoveEntrustedStakeManager {
	nd := &RemoveEntrustedStakeManager{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 2),
	}
	return nd
}

// SetStakeManager sets the "stakeManager" parameter.
func (inst *RemoveEntrustedStakeManager) SetStakeManager(stakeManager ag_solanago.PublicKey) *RemoveEntrustedStakeManager {
	inst.StakeManager = &stakeManager
	return inst
}

// SetStackAccount sets the "stack" account.
func (inst *RemoveEntrustedStakeManager) SetStackAccount(stack ag_solanago.PublicKey) *RemoveEntrustedStakeManager {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(stack).WRITE()
	return inst
}

// GetStackAccount gets the "stack" account.
func (inst *RemoveEntrustedStakeManager) GetStackAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetAdminAccount sets the "admin" account.
func (inst *RemoveEntrustedStakeManager) SetAdminAccount(admin ag_solanago.PublicKey) *RemoveEntrustedStakeManager {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(admin).SIGNER()
	return inst
}

// GetAdminAccount gets the "admin" account.
func (inst *RemoveEntrustedStakeManager) GetAdminAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

func (inst RemoveEntrustedStakeManager) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_RemoveEntrustedStakeManager,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst RemoveEntrustedStakeManager) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *RemoveEntrustedStakeManager) Validate() error {
	// Check whether all (required) parameters are set:
	{
		if inst.StakeManager == nil {
			return errors.New("StakeManager parameter is not set")
		}
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.Stack is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.Admin is not set")
		}
	}
	return nil
}

func (inst *RemoveEntrustedStakeManager) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("RemoveEntrustedStakeManager")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=1]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param("StakeManager", *inst.StakeManager))
					})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=2]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("stack", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("admin", inst.AccountMetaSlice.Get(1)))
					})
				})
		})
}

func (obj RemoveEntrustedStakeManager) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `StakeManager` param:
	err = encoder.Encode(obj.StakeManager)
	if err != nil {
		return err
	}
	return nil
}
func (obj *RemoveEntrustedStakeManager) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `StakeManager`:
	err = decoder.Decode(&obj.StakeManager)
	if err != nil {
		return err
	}
	return nil
}

// NewRemoveEntrustedStakeManagerInstruction declares a new RemoveEntrustedStakeManager instruction with the provided parameters and accounts.
func NewRemoveEntrustedStakeManagerInstruction(
	// Parameters:
	stakeManager ag_solanago.PublicKey,
	// Accounts:
	stack ag_solanago.PublicKey,
	admin ag_solanago.PublicKey) *RemoveEntrustedStakeManager {
	return NewRemoveEntrustedStakeManagerInstructionBuilder().
		SetStakeManager(stakeManager).
		SetStackAccount(stack).
		SetAdminAccount(admin)
}
