// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package stack

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// SetStackFeeCommission is the `setStackFeeCommission` instruction.
type SetStackFeeCommission struct {
	StackFeeCommission *uint64

	// [0] = [WRITE] stack
	//
	// [1] = [SIGNER] admin
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewSetStackFeeCommissionInstructionBuilder creates a new `SetStackFeeCommission` instruction builder.
func NewSetStackFeeCommissionInstructionBuilder() *SetStackFeeCommission {
	nd := &SetStackFeeCommission{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 2),
	}
	return nd
}

// SetStackFeeCommission sets the "stackFeeCommission" parameter.
func (inst *SetStackFeeCommission) SetStackFeeCommission(stackFeeCommission uint64) *SetStackFeeCommission {
	inst.StackFeeCommission = &stackFeeCommission
	return inst
}

// SetStackAccount sets the "stack" account.
func (inst *SetStackFeeCommission) SetStackAccount(stack ag_solanago.PublicKey) *SetStackFeeCommission {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(stack).WRITE()
	return inst
}

// GetStackAccount gets the "stack" account.
func (inst *SetStackFeeCommission) GetStackAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetAdminAccount sets the "admin" account.
func (inst *SetStackFeeCommission) SetAdminAccount(admin ag_solanago.PublicKey) *SetStackFeeCommission {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(admin).SIGNER()
	return inst
}

// GetAdminAccount gets the "admin" account.
func (inst *SetStackFeeCommission) GetAdminAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

func (inst SetStackFeeCommission) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_SetStackFeeCommission,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst SetStackFeeCommission) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *SetStackFeeCommission) Validate() error {
	// Check whether all (required) parameters are set:
	{
		if inst.StackFeeCommission == nil {
			return errors.New("StackFeeCommission parameter is not set")
		}
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.Stack is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.Admin is not set")
		}
	}
	return nil
}

func (inst *SetStackFeeCommission) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("SetStackFeeCommission")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=1]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param("StackFeeCommission", *inst.StackFeeCommission))
					})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=2]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("stack", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("admin", inst.AccountMetaSlice.Get(1)))
					})
				})
		})
}

func (obj SetStackFeeCommission) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `StackFeeCommission` param:
	err = encoder.Encode(obj.StackFeeCommission)
	if err != nil {
		return err
	}
	return nil
}
func (obj *SetStackFeeCommission) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `StackFeeCommission`:
	err = decoder.Decode(&obj.StackFeeCommission)
	if err != nil {
		return err
	}
	return nil
}

// NewSetStackFeeCommissionInstruction declares a new SetStackFeeCommission instruction with the provided parameters and accounts.
func NewSetStackFeeCommissionInstruction(
	// Parameters:
	stackFeeCommission uint64,
	// Accounts:
	stack ag_solanago.PublicKey,
	admin ag_solanago.PublicKey) *SetStackFeeCommission {
	return NewSetStackFeeCommissionInstructionBuilder().
		SetStackFeeCommission(stackFeeCommission).
		SetStackAccount(stack).
		SetAdminAccount(admin)
}
