// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package stake_manager

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// EraMerge is the `eraMerge` instruction.
type EraMerge struct {

	// [0] = [WRITE] stakeManager
	//
	// [1] = [WRITE] srcStakeAccount
	//
	// [2] = [WRITE] dstStakeAccount
	//
	// [3] = [] stakePool
	//
	// [4] = [] clock
	//
	// [5] = [] stakeHistory
	//
	// [6] = [] stakeProgram
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewEraMergeInstructionBuilder creates a new `EraMerge` instruction builder.
func NewEraMergeInstructionBuilder() *EraMerge {
	nd := &EraMerge{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 7),
	}
	return nd
}

// SetStakeManagerAccount sets the "stakeManager" account.
func (inst *EraMerge) SetStakeManagerAccount(stakeManager ag_solanago.PublicKey) *EraMerge {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(stakeManager).WRITE()
	return inst
}

// GetStakeManagerAccount gets the "stakeManager" account.
func (inst *EraMerge) GetStakeManagerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetSrcStakeAccountAccount sets the "srcStakeAccount" account.
func (inst *EraMerge) SetSrcStakeAccountAccount(srcStakeAccount ag_solanago.PublicKey) *EraMerge {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(srcStakeAccount).WRITE()
	return inst
}

// GetSrcStakeAccountAccount gets the "srcStakeAccount" account.
func (inst *EraMerge) GetSrcStakeAccountAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

// SetDstStakeAccountAccount sets the "dstStakeAccount" account.
func (inst *EraMerge) SetDstStakeAccountAccount(dstStakeAccount ag_solanago.PublicKey) *EraMerge {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(dstStakeAccount).WRITE()
	return inst
}

// GetDstStakeAccountAccount gets the "dstStakeAccount" account.
func (inst *EraMerge) GetDstStakeAccountAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(2)
}

// SetStakePoolAccount sets the "stakePool" account.
func (inst *EraMerge) SetStakePoolAccount(stakePool ag_solanago.PublicKey) *EraMerge {
	inst.AccountMetaSlice[3] = ag_solanago.Meta(stakePool)
	return inst
}

// GetStakePoolAccount gets the "stakePool" account.
func (inst *EraMerge) GetStakePoolAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(3)
}

// SetClockAccount sets the "clock" account.
func (inst *EraMerge) SetClockAccount(clock ag_solanago.PublicKey) *EraMerge {
	inst.AccountMetaSlice[4] = ag_solanago.Meta(clock)
	return inst
}

// GetClockAccount gets the "clock" account.
func (inst *EraMerge) GetClockAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(4)
}

// SetStakeHistoryAccount sets the "stakeHistory" account.
func (inst *EraMerge) SetStakeHistoryAccount(stakeHistory ag_solanago.PublicKey) *EraMerge {
	inst.AccountMetaSlice[5] = ag_solanago.Meta(stakeHistory)
	return inst
}

// GetStakeHistoryAccount gets the "stakeHistory" account.
func (inst *EraMerge) GetStakeHistoryAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(5)
}

// SetStakeProgramAccount sets the "stakeProgram" account.
func (inst *EraMerge) SetStakeProgramAccount(stakeProgram ag_solanago.PublicKey) *EraMerge {
	inst.AccountMetaSlice[6] = ag_solanago.Meta(stakeProgram)
	return inst
}

// GetStakeProgramAccount gets the "stakeProgram" account.
func (inst *EraMerge) GetStakeProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(6)
}

func (inst EraMerge) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_EraMerge,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst EraMerge) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *EraMerge) Validate() error {
	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.StakeManager is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.SrcStakeAccount is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.DstStakeAccount is not set")
		}
		if inst.AccountMetaSlice[3] == nil {
			return errors.New("accounts.StakePool is not set")
		}
		if inst.AccountMetaSlice[4] == nil {
			return errors.New("accounts.Clock is not set")
		}
		if inst.AccountMetaSlice[5] == nil {
			return errors.New("accounts.StakeHistory is not set")
		}
		if inst.AccountMetaSlice[6] == nil {
			return errors.New("accounts.StakeProgram is not set")
		}
	}
	return nil
}

func (inst *EraMerge) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("EraMerge")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=0]").ParentFunc(func(paramsBranch ag_treeout.Branches) {})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=7]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("stakeManager", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("    srcStake", inst.AccountMetaSlice.Get(1)))
						accountsBranch.Child(ag_format.Meta("    dstStake", inst.AccountMetaSlice.Get(2)))
						accountsBranch.Child(ag_format.Meta("   stakePool", inst.AccountMetaSlice.Get(3)))
						accountsBranch.Child(ag_format.Meta("       clock", inst.AccountMetaSlice.Get(4)))
						accountsBranch.Child(ag_format.Meta("stakeHistory", inst.AccountMetaSlice.Get(5)))
						accountsBranch.Child(ag_format.Meta("stakeProgram", inst.AccountMetaSlice.Get(6)))
					})
				})
		})
}

func (obj EraMerge) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	return nil
}
func (obj *EraMerge) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	return nil
}

// NewEraMergeInstruction declares a new EraMerge instruction with the provided parameters and accounts.
func NewEraMergeInstruction(
	// Accounts:
	stakeManager ag_solanago.PublicKey,
	srcStakeAccount ag_solanago.PublicKey,
	dstStakeAccount ag_solanago.PublicKey,
	stakePool ag_solanago.PublicKey,
	clock ag_solanago.PublicKey,
	stakeHistory ag_solanago.PublicKey,
	stakeProgram ag_solanago.PublicKey) *EraMerge {
	return NewEraMergeInstructionBuilder().
		SetStakeManagerAccount(stakeManager).
		SetSrcStakeAccountAccount(srcStakeAccount).
		SetDstStakeAccountAccount(dstStakeAccount).
		SetStakePoolAccount(stakePool).
		SetClockAccount(clock).
		SetStakeHistoryAccount(stakeHistory).
		SetStakeProgramAccount(stakeProgram)
}
