// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package stake_manager

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// EraUpdateRate is the `eraUpdateRate` instruction.
type EraUpdateRate struct {

	// [0] = [WRITE] stakeManager
	//
	// [1] = [] stack
	//
	// [2] = [WRITE] stakeManagerAdmin
	//
	// [3] = [WRITE] stackAdmin
	//
	// [4] = [] stakePool
	//
	// [5] = [WRITE] lsdTokenMint
	//
	// [6] = [WRITE] platformFeeRecipient
	//
	// [7] = [WRITE] stackFeeRecipient
	//
	// [8] = [WRITE] stackFeeAccount
	//
	// [9] = [WRITE, SIGNER] rentPayer
	//
	// [10] = [] associatedTokenProgram
	//
	// [11] = [] tokenProgram
	//
	// [12] = [] systemProgram
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewEraUpdateRateInstructionBuilder creates a new `EraUpdateRate` instruction builder.
func NewEraUpdateRateInstructionBuilder() *EraUpdateRate {
	nd := &EraUpdateRate{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 13),
	}
	return nd
}

// SetStakeManagerAccount sets the "stakeManager" account.
func (inst *EraUpdateRate) SetStakeManagerAccount(stakeManager ag_solanago.PublicKey) *EraUpdateRate {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(stakeManager).WRITE()
	return inst
}

// GetStakeManagerAccount gets the "stakeManager" account.
func (inst *EraUpdateRate) GetStakeManagerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetStackAccount sets the "stack" account.
func (inst *EraUpdateRate) SetStackAccount(stack ag_solanago.PublicKey) *EraUpdateRate {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(stack)
	return inst
}

// GetStackAccount gets the "stack" account.
func (inst *EraUpdateRate) GetStackAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

// SetStakeManagerAdminAccount sets the "stakeManagerAdmin" account.
func (inst *EraUpdateRate) SetStakeManagerAdminAccount(stakeManagerAdmin ag_solanago.PublicKey) *EraUpdateRate {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(stakeManagerAdmin).WRITE()
	return inst
}

// GetStakeManagerAdminAccount gets the "stakeManagerAdmin" account.
func (inst *EraUpdateRate) GetStakeManagerAdminAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(2)
}

// SetStackAdminAccount sets the "stackAdmin" account.
func (inst *EraUpdateRate) SetStackAdminAccount(stackAdmin ag_solanago.PublicKey) *EraUpdateRate {
	inst.AccountMetaSlice[3] = ag_solanago.Meta(stackAdmin).WRITE()
	return inst
}

// GetStackAdminAccount gets the "stackAdmin" account.
func (inst *EraUpdateRate) GetStackAdminAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(3)
}

// SetStakePoolAccount sets the "stakePool" account.
func (inst *EraUpdateRate) SetStakePoolAccount(stakePool ag_solanago.PublicKey) *EraUpdateRate {
	inst.AccountMetaSlice[4] = ag_solanago.Meta(stakePool)
	return inst
}

// GetStakePoolAccount gets the "stakePool" account.
func (inst *EraUpdateRate) GetStakePoolAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(4)
}

// SetLsdTokenMintAccount sets the "lsdTokenMint" account.
func (inst *EraUpdateRate) SetLsdTokenMintAccount(lsdTokenMint ag_solanago.PublicKey) *EraUpdateRate {
	inst.AccountMetaSlice[5] = ag_solanago.Meta(lsdTokenMint).WRITE()
	return inst
}

// GetLsdTokenMintAccount gets the "lsdTokenMint" account.
func (inst *EraUpdateRate) GetLsdTokenMintAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(5)
}

// SetPlatformFeeRecipientAccount sets the "platformFeeRecipient" account.
func (inst *EraUpdateRate) SetPlatformFeeRecipientAccount(platformFeeRecipient ag_solanago.PublicKey) *EraUpdateRate {
	inst.AccountMetaSlice[6] = ag_solanago.Meta(platformFeeRecipient).WRITE()
	return inst
}

// GetPlatformFeeRecipientAccount gets the "platformFeeRecipient" account.
func (inst *EraUpdateRate) GetPlatformFeeRecipientAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(6)
}

// SetStackFeeRecipientAccount sets the "stackFeeRecipient" account.
func (inst *EraUpdateRate) SetStackFeeRecipientAccount(stackFeeRecipient ag_solanago.PublicKey) *EraUpdateRate {
	inst.AccountMetaSlice[7] = ag_solanago.Meta(stackFeeRecipient).WRITE()
	return inst
}

// GetStackFeeRecipientAccount gets the "stackFeeRecipient" account.
func (inst *EraUpdateRate) GetStackFeeRecipientAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(7)
}

// SetStackFeeAccountAccount sets the "stackFeeAccount" account.
func (inst *EraUpdateRate) SetStackFeeAccountAccount(stackFeeAccount ag_solanago.PublicKey) *EraUpdateRate {
	inst.AccountMetaSlice[8] = ag_solanago.Meta(stackFeeAccount).WRITE()
	return inst
}

// GetStackFeeAccountAccount gets the "stackFeeAccount" account.
func (inst *EraUpdateRate) GetStackFeeAccountAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(8)
}

// SetRentPayerAccount sets the "rentPayer" account.
func (inst *EraUpdateRate) SetRentPayerAccount(rentPayer ag_solanago.PublicKey) *EraUpdateRate {
	inst.AccountMetaSlice[9] = ag_solanago.Meta(rentPayer).WRITE().SIGNER()
	return inst
}

// GetRentPayerAccount gets the "rentPayer" account.
func (inst *EraUpdateRate) GetRentPayerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(9)
}

// SetAssociatedTokenProgramAccount sets the "associatedTokenProgram" account.
func (inst *EraUpdateRate) SetAssociatedTokenProgramAccount(associatedTokenProgram ag_solanago.PublicKey) *EraUpdateRate {
	inst.AccountMetaSlice[10] = ag_solanago.Meta(associatedTokenProgram)
	return inst
}

// GetAssociatedTokenProgramAccount gets the "associatedTokenProgram" account.
func (inst *EraUpdateRate) GetAssociatedTokenProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(10)
}

// SetTokenProgramAccount sets the "tokenProgram" account.
func (inst *EraUpdateRate) SetTokenProgramAccount(tokenProgram ag_solanago.PublicKey) *EraUpdateRate {
	inst.AccountMetaSlice[11] = ag_solanago.Meta(tokenProgram)
	return inst
}

// GetTokenProgramAccount gets the "tokenProgram" account.
func (inst *EraUpdateRate) GetTokenProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(11)
}

// SetSystemProgramAccount sets the "systemProgram" account.
func (inst *EraUpdateRate) SetSystemProgramAccount(systemProgram ag_solanago.PublicKey) *EraUpdateRate {
	inst.AccountMetaSlice[12] = ag_solanago.Meta(systemProgram)
	return inst
}

// GetSystemProgramAccount gets the "systemProgram" account.
func (inst *EraUpdateRate) GetSystemProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(12)
}

func (inst EraUpdateRate) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_EraUpdateRate,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst EraUpdateRate) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *EraUpdateRate) Validate() error {
	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.StakeManager is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.Stack is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.StakeManagerAdmin is not set")
		}
		if inst.AccountMetaSlice[3] == nil {
			return errors.New("accounts.StackAdmin is not set")
		}
		if inst.AccountMetaSlice[4] == nil {
			return errors.New("accounts.StakePool is not set")
		}
		if inst.AccountMetaSlice[5] == nil {
			return errors.New("accounts.LsdTokenMint is not set")
		}
		if inst.AccountMetaSlice[6] == nil {
			return errors.New("accounts.PlatformFeeRecipient is not set")
		}
		if inst.AccountMetaSlice[7] == nil {
			return errors.New("accounts.StackFeeRecipient is not set")
		}
		if inst.AccountMetaSlice[8] == nil {
			return errors.New("accounts.StackFeeAccount is not set")
		}
		if inst.AccountMetaSlice[9] == nil {
			return errors.New("accounts.RentPayer is not set")
		}
		if inst.AccountMetaSlice[10] == nil {
			return errors.New("accounts.AssociatedTokenProgram is not set")
		}
		if inst.AccountMetaSlice[11] == nil {
			return errors.New("accounts.TokenProgram is not set")
		}
		if inst.AccountMetaSlice[12] == nil {
			return errors.New("accounts.SystemProgram is not set")
		}
	}
	return nil
}

func (inst *EraUpdateRate) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("EraUpdateRate")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=0]").ParentFunc(func(paramsBranch ag_treeout.Branches) {})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=13]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("          stakeManager", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("                 stack", inst.AccountMetaSlice.Get(1)))
						accountsBranch.Child(ag_format.Meta("     stakeManagerAdmin", inst.AccountMetaSlice.Get(2)))
						accountsBranch.Child(ag_format.Meta("            stackAdmin", inst.AccountMetaSlice.Get(3)))
						accountsBranch.Child(ag_format.Meta("             stakePool", inst.AccountMetaSlice.Get(4)))
						accountsBranch.Child(ag_format.Meta("          lsdTokenMint", inst.AccountMetaSlice.Get(5)))
						accountsBranch.Child(ag_format.Meta("  platformFeeRecipient", inst.AccountMetaSlice.Get(6)))
						accountsBranch.Child(ag_format.Meta("     stackFeeRecipient", inst.AccountMetaSlice.Get(7)))
						accountsBranch.Child(ag_format.Meta("              stackFee", inst.AccountMetaSlice.Get(8)))
						accountsBranch.Child(ag_format.Meta("             rentPayer", inst.AccountMetaSlice.Get(9)))
						accountsBranch.Child(ag_format.Meta("associatedTokenProgram", inst.AccountMetaSlice.Get(10)))
						accountsBranch.Child(ag_format.Meta("          tokenProgram", inst.AccountMetaSlice.Get(11)))
						accountsBranch.Child(ag_format.Meta("         systemProgram", inst.AccountMetaSlice.Get(12)))
					})
				})
		})
}

func (obj EraUpdateRate) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	return nil
}
func (obj *EraUpdateRate) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	return nil
}

// NewEraUpdateRateInstruction declares a new EraUpdateRate instruction with the provided parameters and accounts.
func NewEraUpdateRateInstruction(
	// Accounts:
	stakeManager ag_solanago.PublicKey,
	stack ag_solanago.PublicKey,
	stakeManagerAdmin ag_solanago.PublicKey,
	stackAdmin ag_solanago.PublicKey,
	stakePool ag_solanago.PublicKey,
	lsdTokenMint ag_solanago.PublicKey,
	platformFeeRecipient ag_solanago.PublicKey,
	stackFeeRecipient ag_solanago.PublicKey,
	stackFeeAccount ag_solanago.PublicKey,
	rentPayer ag_solanago.PublicKey,
	associatedTokenProgram ag_solanago.PublicKey,
	tokenProgram ag_solanago.PublicKey,
	systemProgram ag_solanago.PublicKey) *EraUpdateRate {
	return NewEraUpdateRateInstructionBuilder().
		SetStakeManagerAccount(stakeManager).
		SetStackAccount(stack).
		SetStakeManagerAdminAccount(stakeManagerAdmin).
		SetStackAdminAccount(stackAdmin).
		SetStakePoolAccount(stakePool).
		SetLsdTokenMintAccount(lsdTokenMint).
		SetPlatformFeeRecipientAccount(platformFeeRecipient).
		SetStackFeeRecipientAccount(stackFeeRecipient).
		SetStackFeeAccountAccount(stackFeeAccount).
		SetRentPayerAccount(rentPayer).
		SetAssociatedTokenProgramAccount(associatedTokenProgram).
		SetTokenProgramAccount(tokenProgram).
		SetSystemProgramAccount(systemProgram)
}
