// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package stake_manager

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// InitializeStakeManager is the `initializeStakeManager` instruction.
type InitializeStakeManager struct {
	StakeManagerIndex *uint8

	// [0] = [WRITE] stakeManager
	//
	// [1] = [] stack
	//
	// [2] = [] stakePool
	//
	// [3] = [WRITE] stackFeeAccount
	//
	// [4] = [WRITE] lsdTokenMint
	//
	// [5] = [] validator
	//
	// [6] = [WRITE, SIGNER] rentPayer
	//
	// [7] = [SIGNER] admin
	//
	// [8] = [] tokenProgram
	//
	// [9] = [] systemProgram
	//
	// [10] = [] rent
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewInitializeStakeManagerInstructionBuilder creates a new `InitializeStakeManager` instruction builder.
func NewInitializeStakeManagerInstructionBuilder() *InitializeStakeManager {
	nd := &InitializeStakeManager{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 11),
	}
	return nd
}

// SetStakeManagerIndex sets the "stakeManagerIndex" parameter.
func (inst *InitializeStakeManager) SetStakeManagerIndex(stakeManagerIndex uint8) *InitializeStakeManager {
	inst.StakeManagerIndex = &stakeManagerIndex
	return inst
}

// SetStakeManagerAccount sets the "stakeManager" account.
func (inst *InitializeStakeManager) SetStakeManagerAccount(stakeManager ag_solanago.PublicKey) *InitializeStakeManager {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(stakeManager).WRITE()
	return inst
}

// GetStakeManagerAccount gets the "stakeManager" account.
func (inst *InitializeStakeManager) GetStakeManagerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetStackAccount sets the "stack" account.
func (inst *InitializeStakeManager) SetStackAccount(stack ag_solanago.PublicKey) *InitializeStakeManager {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(stack)
	return inst
}

// GetStackAccount gets the "stack" account.
func (inst *InitializeStakeManager) GetStackAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

// SetStakePoolAccount sets the "stakePool" account.
func (inst *InitializeStakeManager) SetStakePoolAccount(stakePool ag_solanago.PublicKey) *InitializeStakeManager {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(stakePool)
	return inst
}

// GetStakePoolAccount gets the "stakePool" account.
func (inst *InitializeStakeManager) GetStakePoolAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(2)
}

// SetStackFeeAccountAccount sets the "stackFeeAccount" account.
func (inst *InitializeStakeManager) SetStackFeeAccountAccount(stackFeeAccount ag_solanago.PublicKey) *InitializeStakeManager {
	inst.AccountMetaSlice[3] = ag_solanago.Meta(stackFeeAccount).WRITE()
	return inst
}

// GetStackFeeAccountAccount gets the "stackFeeAccount" account.
func (inst *InitializeStakeManager) GetStackFeeAccountAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(3)
}

// SetLsdTokenMintAccount sets the "lsdTokenMint" account.
func (inst *InitializeStakeManager) SetLsdTokenMintAccount(lsdTokenMint ag_solanago.PublicKey) *InitializeStakeManager {
	inst.AccountMetaSlice[4] = ag_solanago.Meta(lsdTokenMint).WRITE()
	return inst
}

// GetLsdTokenMintAccount gets the "lsdTokenMint" account.
func (inst *InitializeStakeManager) GetLsdTokenMintAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(4)
}

// SetValidatorAccount sets the "validator" account.
func (inst *InitializeStakeManager) SetValidatorAccount(validator ag_solanago.PublicKey) *InitializeStakeManager {
	inst.AccountMetaSlice[5] = ag_solanago.Meta(validator)
	return inst
}

// GetValidatorAccount gets the "validator" account.
func (inst *InitializeStakeManager) GetValidatorAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(5)
}

// SetRentPayerAccount sets the "rentPayer" account.
func (inst *InitializeStakeManager) SetRentPayerAccount(rentPayer ag_solanago.PublicKey) *InitializeStakeManager {
	inst.AccountMetaSlice[6] = ag_solanago.Meta(rentPayer).WRITE().SIGNER()
	return inst
}

// GetRentPayerAccount gets the "rentPayer" account.
func (inst *InitializeStakeManager) GetRentPayerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(6)
}

// SetAdminAccount sets the "admin" account.
func (inst *InitializeStakeManager) SetAdminAccount(admin ag_solanago.PublicKey) *InitializeStakeManager {
	inst.AccountMetaSlice[7] = ag_solanago.Meta(admin).SIGNER()
	return inst
}

// GetAdminAccount gets the "admin" account.
func (inst *InitializeStakeManager) GetAdminAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(7)
}

// SetTokenProgramAccount sets the "tokenProgram" account.
func (inst *InitializeStakeManager) SetTokenProgramAccount(tokenProgram ag_solanago.PublicKey) *InitializeStakeManager {
	inst.AccountMetaSlice[8] = ag_solanago.Meta(tokenProgram)
	return inst
}

// GetTokenProgramAccount gets the "tokenProgram" account.
func (inst *InitializeStakeManager) GetTokenProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(8)
}

// SetSystemProgramAccount sets the "systemProgram" account.
func (inst *InitializeStakeManager) SetSystemProgramAccount(systemProgram ag_solanago.PublicKey) *InitializeStakeManager {
	inst.AccountMetaSlice[9] = ag_solanago.Meta(systemProgram)
	return inst
}

// GetSystemProgramAccount gets the "systemProgram" account.
func (inst *InitializeStakeManager) GetSystemProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(9)
}

// SetRentAccount sets the "rent" account.
func (inst *InitializeStakeManager) SetRentAccount(rent ag_solanago.PublicKey) *InitializeStakeManager {
	inst.AccountMetaSlice[10] = ag_solanago.Meta(rent)
	return inst
}

// GetRentAccount gets the "rent" account.
func (inst *InitializeStakeManager) GetRentAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(10)
}

func (inst InitializeStakeManager) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_InitializeStakeManager,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst InitializeStakeManager) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *InitializeStakeManager) Validate() error {
	// Check whether all (required) parameters are set:
	{
		if inst.StakeManagerIndex == nil {
			return errors.New("StakeManagerIndex parameter is not set")
		}
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.StakeManager is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.Stack is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.StakePool is not set")
		}
		if inst.AccountMetaSlice[3] == nil {
			return errors.New("accounts.StackFeeAccount is not set")
		}
		if inst.AccountMetaSlice[4] == nil {
			return errors.New("accounts.LsdTokenMint is not set")
		}
		if inst.AccountMetaSlice[5] == nil {
			return errors.New("accounts.Validator is not set")
		}
		if inst.AccountMetaSlice[6] == nil {
			return errors.New("accounts.RentPayer is not set")
		}
		if inst.AccountMetaSlice[7] == nil {
			return errors.New("accounts.Admin is not set")
		}
		if inst.AccountMetaSlice[8] == nil {
			return errors.New("accounts.TokenProgram is not set")
		}
		if inst.AccountMetaSlice[9] == nil {
			return errors.New("accounts.SystemProgram is not set")
		}
		if inst.AccountMetaSlice[10] == nil {
			return errors.New("accounts.Rent is not set")
		}
	}
	return nil
}

func (inst *InitializeStakeManager) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("InitializeStakeManager")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=1]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param("StakeManagerIndex", *inst.StakeManagerIndex))
					})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=11]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta(" stakeManager", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("        stack", inst.AccountMetaSlice.Get(1)))
						accountsBranch.Child(ag_format.Meta("    stakePool", inst.AccountMetaSlice.Get(2)))
						accountsBranch.Child(ag_format.Meta("     stackFee", inst.AccountMetaSlice.Get(3)))
						accountsBranch.Child(ag_format.Meta(" lsdTokenMint", inst.AccountMetaSlice.Get(4)))
						accountsBranch.Child(ag_format.Meta("    validator", inst.AccountMetaSlice.Get(5)))
						accountsBranch.Child(ag_format.Meta("    rentPayer", inst.AccountMetaSlice.Get(6)))
						accountsBranch.Child(ag_format.Meta("        admin", inst.AccountMetaSlice.Get(7)))
						accountsBranch.Child(ag_format.Meta(" tokenProgram", inst.AccountMetaSlice.Get(8)))
						accountsBranch.Child(ag_format.Meta("systemProgram", inst.AccountMetaSlice.Get(9)))
						accountsBranch.Child(ag_format.Meta("         rent", inst.AccountMetaSlice.Get(10)))
					})
				})
		})
}

func (obj InitializeStakeManager) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `StakeManagerIndex` param:
	err = encoder.Encode(obj.StakeManagerIndex)
	if err != nil {
		return err
	}
	return nil
}
func (obj *InitializeStakeManager) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `StakeManagerIndex`:
	err = decoder.Decode(&obj.StakeManagerIndex)
	if err != nil {
		return err
	}
	return nil
}

// NewInitializeStakeManagerInstruction declares a new InitializeStakeManager instruction with the provided parameters and accounts.
func NewInitializeStakeManagerInstruction(
	// Parameters:
	stakeManagerIndex uint8,
	// Accounts:
	stakeManager ag_solanago.PublicKey,
	stack ag_solanago.PublicKey,
	stakePool ag_solanago.PublicKey,
	stackFeeAccount ag_solanago.PublicKey,
	lsdTokenMint ag_solanago.PublicKey,
	validator ag_solanago.PublicKey,
	rentPayer ag_solanago.PublicKey,
	admin ag_solanago.PublicKey,
	tokenProgram ag_solanago.PublicKey,
	systemProgram ag_solanago.PublicKey,
	rent ag_solanago.PublicKey) *InitializeStakeManager {
	return NewInitializeStakeManagerInstructionBuilder().
		SetStakeManagerIndex(stakeManagerIndex).
		SetStakeManagerAccount(stakeManager).
		SetStackAccount(stack).
		SetStakePoolAccount(stakePool).
		SetStackFeeAccountAccount(stackFeeAccount).
		SetLsdTokenMintAccount(lsdTokenMint).
		SetValidatorAccount(validator).
		SetRentPayerAccount(rentPayer).
		SetAdminAccount(admin).
		SetTokenProgramAccount(tokenProgram).
		SetSystemProgramAccount(systemProgram).
		SetRentAccount(rent)
}
