// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package stake_manager

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// ReallocStakeManager is the `reallocStakeManager` instruction.
type ReallocStakeManager struct {
	NewSize *uint32

	// [0] = [WRITE] stakeManager
	//
	// [1] = [SIGNER] admin
	//
	// [2] = [WRITE, SIGNER] rentPayer
	//
	// [3] = [] systemProgram
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewReallocStakeManagerInstructionBuilder creates a new `ReallocStakeManager` instruction builder.
func NewReallocStakeManagerInstructionBuilder() *ReallocStakeManager {
	nd := &ReallocStakeManager{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 4),
	}
	return nd
}

// SetNewSize sets the "newSize" parameter.
func (inst *ReallocStakeManager) SetNewSize(newSize uint32) *ReallocStakeManager {
	inst.NewSize = &newSize
	return inst
}

// SetStakeManagerAccount sets the "stakeManager" account.
func (inst *ReallocStakeManager) SetStakeManagerAccount(stakeManager ag_solanago.PublicKey) *ReallocStakeManager {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(stakeManager).WRITE()
	return inst
}

// GetStakeManagerAccount gets the "stakeManager" account.
func (inst *ReallocStakeManager) GetStakeManagerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetAdminAccount sets the "admin" account.
func (inst *ReallocStakeManager) SetAdminAccount(admin ag_solanago.PublicKey) *ReallocStakeManager {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(admin).SIGNER()
	return inst
}

// GetAdminAccount gets the "admin" account.
func (inst *ReallocStakeManager) GetAdminAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

// SetRentPayerAccount sets the "rentPayer" account.
func (inst *ReallocStakeManager) SetRentPayerAccount(rentPayer ag_solanago.PublicKey) *ReallocStakeManager {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(rentPayer).WRITE().SIGNER()
	return inst
}

// GetRentPayerAccount gets the "rentPayer" account.
func (inst *ReallocStakeManager) GetRentPayerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(2)
}

// SetSystemProgramAccount sets the "systemProgram" account.
func (inst *ReallocStakeManager) SetSystemProgramAccount(systemProgram ag_solanago.PublicKey) *ReallocStakeManager {
	inst.AccountMetaSlice[3] = ag_solanago.Meta(systemProgram)
	return inst
}

// GetSystemProgramAccount gets the "systemProgram" account.
func (inst *ReallocStakeManager) GetSystemProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(3)
}

func (inst ReallocStakeManager) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_ReallocStakeManager,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst ReallocStakeManager) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *ReallocStakeManager) Validate() error {
	// Check whether all (required) parameters are set:
	{
		if inst.NewSize == nil {
			return errors.New("NewSize parameter is not set")
		}
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.StakeManager is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.Admin is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.RentPayer is not set")
		}
		if inst.AccountMetaSlice[3] == nil {
			return errors.New("accounts.SystemProgram is not set")
		}
	}
	return nil
}

func (inst *ReallocStakeManager) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("ReallocStakeManager")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=1]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param("NewSize", *inst.NewSize))
					})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=4]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta(" stakeManager", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("        admin", inst.AccountMetaSlice.Get(1)))
						accountsBranch.Child(ag_format.Meta("    rentPayer", inst.AccountMetaSlice.Get(2)))
						accountsBranch.Child(ag_format.Meta("systemProgram", inst.AccountMetaSlice.Get(3)))
					})
				})
		})
}

func (obj ReallocStakeManager) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `NewSize` param:
	err = encoder.Encode(obj.NewSize)
	if err != nil {
		return err
	}
	return nil
}
func (obj *ReallocStakeManager) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `NewSize`:
	err = decoder.Decode(&obj.NewSize)
	if err != nil {
		return err
	}
	return nil
}

// NewReallocStakeManagerInstruction declares a new ReallocStakeManager instruction with the provided parameters and accounts.
func NewReallocStakeManagerInstruction(
	// Parameters:
	newSize uint32,
	// Accounts:
	stakeManager ag_solanago.PublicKey,
	admin ag_solanago.PublicKey,
	rentPayer ag_solanago.PublicKey,
	systemProgram ag_solanago.PublicKey) *ReallocStakeManager {
	return NewReallocStakeManagerInstructionBuilder().
		SetNewSize(newSize).
		SetStakeManagerAccount(stakeManager).
		SetAdminAccount(admin).
		SetRentPayerAccount(rentPayer).
		SetSystemProgramAccount(systemProgram)
}
