// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package stake_manager

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// Redelegate is the `redelegate` instruction.
type Redelegate struct {
	RedelegateAmount *uint64

	// [0] = [WRITE] stakeManager
	//
	// [1] = [SIGNER] balancer
	//
	// [2] = [WRITE] toValidator
	//
	// [3] = [] stakePool
	//
	// [4] = [WRITE] fromStakeAccount
	//
	// [5] = [WRITE, SIGNER] splitStakeAccount
	//
	// [6] = [WRITE, SIGNER] toStakeAccount
	//
	// [7] = [WRITE, SIGNER] rentPayer
	//
	// [8] = [] clock
	//
	// [9] = [] stakeConfig
	//
	// [10] = [] stakeHistory
	//
	// [11] = [] stakeProgram
	//
	// [12] = [] systemProgram
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewRedelegateInstructionBuilder creates a new `Redelegate` instruction builder.
func NewRedelegateInstructionBuilder() *Redelegate {
	nd := &Redelegate{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 13),
	}
	return nd
}

// SetRedelegateAmount sets the "redelegateAmount" parameter.
func (inst *Redelegate) SetRedelegateAmount(redelegateAmount uint64) *Redelegate {
	inst.RedelegateAmount = &redelegateAmount
	return inst
}

// SetStakeManagerAccount sets the "stakeManager" account.
func (inst *Redelegate) SetStakeManagerAccount(stakeManager ag_solanago.PublicKey) *Redelegate {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(stakeManager).WRITE()
	return inst
}

// GetStakeManagerAccount gets the "stakeManager" account.
func (inst *Redelegate) GetStakeManagerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetBalancerAccount sets the "balancer" account.
func (inst *Redelegate) SetBalancerAccount(balancer ag_solanago.PublicKey) *Redelegate {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(balancer).SIGNER()
	return inst
}

// GetBalancerAccount gets the "balancer" account.
func (inst *Redelegate) GetBalancerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

// SetToValidatorAccount sets the "toValidator" account.
func (inst *Redelegate) SetToValidatorAccount(toValidator ag_solanago.PublicKey) *Redelegate {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(toValidator).WRITE()
	return inst
}

// GetToValidatorAccount gets the "toValidator" account.
func (inst *Redelegate) GetToValidatorAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(2)
}

// SetStakePoolAccount sets the "stakePool" account.
func (inst *Redelegate) SetStakePoolAccount(stakePool ag_solanago.PublicKey) *Redelegate {
	inst.AccountMetaSlice[3] = ag_solanago.Meta(stakePool)
	return inst
}

// GetStakePoolAccount gets the "stakePool" account.
func (inst *Redelegate) GetStakePoolAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(3)
}

// SetFromStakeAccountAccount sets the "fromStakeAccount" account.
func (inst *Redelegate) SetFromStakeAccountAccount(fromStakeAccount ag_solanago.PublicKey) *Redelegate {
	inst.AccountMetaSlice[4] = ag_solanago.Meta(fromStakeAccount).WRITE()
	return inst
}

// GetFromStakeAccountAccount gets the "fromStakeAccount" account.
func (inst *Redelegate) GetFromStakeAccountAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(4)
}

// SetSplitStakeAccountAccount sets the "splitStakeAccount" account.
func (inst *Redelegate) SetSplitStakeAccountAccount(splitStakeAccount ag_solanago.PublicKey) *Redelegate {
	inst.AccountMetaSlice[5] = ag_solanago.Meta(splitStakeAccount).WRITE().SIGNER()
	return inst
}

// GetSplitStakeAccountAccount gets the "splitStakeAccount" account.
func (inst *Redelegate) GetSplitStakeAccountAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(5)
}

// SetToStakeAccountAccount sets the "toStakeAccount" account.
func (inst *Redelegate) SetToStakeAccountAccount(toStakeAccount ag_solanago.PublicKey) *Redelegate {
	inst.AccountMetaSlice[6] = ag_solanago.Meta(toStakeAccount).WRITE().SIGNER()
	return inst
}

// GetToStakeAccountAccount gets the "toStakeAccount" account.
func (inst *Redelegate) GetToStakeAccountAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(6)
}

// SetRentPayerAccount sets the "rentPayer" account.
func (inst *Redelegate) SetRentPayerAccount(rentPayer ag_solanago.PublicKey) *Redelegate {
	inst.AccountMetaSlice[7] = ag_solanago.Meta(rentPayer).WRITE().SIGNER()
	return inst
}

// GetRentPayerAccount gets the "rentPayer" account.
func (inst *Redelegate) GetRentPayerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(7)
}

// SetClockAccount sets the "clock" account.
func (inst *Redelegate) SetClockAccount(clock ag_solanago.PublicKey) *Redelegate {
	inst.AccountMetaSlice[8] = ag_solanago.Meta(clock)
	return inst
}

// GetClockAccount gets the "clock" account.
func (inst *Redelegate) GetClockAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(8)
}

// SetStakeConfigAccount sets the "stakeConfig" account.
func (inst *Redelegate) SetStakeConfigAccount(stakeConfig ag_solanago.PublicKey) *Redelegate {
	inst.AccountMetaSlice[9] = ag_solanago.Meta(stakeConfig)
	return inst
}

// GetStakeConfigAccount gets the "stakeConfig" account.
func (inst *Redelegate) GetStakeConfigAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(9)
}

// SetStakeHistoryAccount sets the "stakeHistory" account.
func (inst *Redelegate) SetStakeHistoryAccount(stakeHistory ag_solanago.PublicKey) *Redelegate {
	inst.AccountMetaSlice[10] = ag_solanago.Meta(stakeHistory)
	return inst
}

// GetStakeHistoryAccount gets the "stakeHistory" account.
func (inst *Redelegate) GetStakeHistoryAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(10)
}

// SetStakeProgramAccount sets the "stakeProgram" account.
func (inst *Redelegate) SetStakeProgramAccount(stakeProgram ag_solanago.PublicKey) *Redelegate {
	inst.AccountMetaSlice[11] = ag_solanago.Meta(stakeProgram)
	return inst
}

// GetStakeProgramAccount gets the "stakeProgram" account.
func (inst *Redelegate) GetStakeProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(11)
}

// SetSystemProgramAccount sets the "systemProgram" account.
func (inst *Redelegate) SetSystemProgramAccount(systemProgram ag_solanago.PublicKey) *Redelegate {
	inst.AccountMetaSlice[12] = ag_solanago.Meta(systemProgram)
	return inst
}

// GetSystemProgramAccount gets the "systemProgram" account.
func (inst *Redelegate) GetSystemProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(12)
}

func (inst Redelegate) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_Redelegate,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst Redelegate) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *Redelegate) Validate() error {
	// Check whether all (required) parameters are set:
	{
		if inst.RedelegateAmount == nil {
			return errors.New("RedelegateAmount parameter is not set")
		}
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.StakeManager is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.Balancer is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.ToValidator is not set")
		}
		if inst.AccountMetaSlice[3] == nil {
			return errors.New("accounts.StakePool is not set")
		}
		if inst.AccountMetaSlice[4] == nil {
			return errors.New("accounts.FromStakeAccount is not set")
		}
		if inst.AccountMetaSlice[5] == nil {
			return errors.New("accounts.SplitStakeAccount is not set")
		}
		if inst.AccountMetaSlice[6] == nil {
			return errors.New("accounts.ToStakeAccount is not set")
		}
		if inst.AccountMetaSlice[7] == nil {
			return errors.New("accounts.RentPayer is not set")
		}
		if inst.AccountMetaSlice[8] == nil {
			return errors.New("accounts.Clock is not set")
		}
		if inst.AccountMetaSlice[9] == nil {
			return errors.New("accounts.StakeConfig is not set")
		}
		if inst.AccountMetaSlice[10] == nil {
			return errors.New("accounts.StakeHistory is not set")
		}
		if inst.AccountMetaSlice[11] == nil {
			return errors.New("accounts.StakeProgram is not set")
		}
		if inst.AccountMetaSlice[12] == nil {
			return errors.New("accounts.SystemProgram is not set")
		}
	}
	return nil
}

func (inst *Redelegate) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("Redelegate")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=1]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param("RedelegateAmount", *inst.RedelegateAmount))
					})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=13]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta(" stakeManager", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("     balancer", inst.AccountMetaSlice.Get(1)))
						accountsBranch.Child(ag_format.Meta("  toValidator", inst.AccountMetaSlice.Get(2)))
						accountsBranch.Child(ag_format.Meta("    stakePool", inst.AccountMetaSlice.Get(3)))
						accountsBranch.Child(ag_format.Meta("    fromStake", inst.AccountMetaSlice.Get(4)))
						accountsBranch.Child(ag_format.Meta("   splitStake", inst.AccountMetaSlice.Get(5)))
						accountsBranch.Child(ag_format.Meta("      toStake", inst.AccountMetaSlice.Get(6)))
						accountsBranch.Child(ag_format.Meta("    rentPayer", inst.AccountMetaSlice.Get(7)))
						accountsBranch.Child(ag_format.Meta("        clock", inst.AccountMetaSlice.Get(8)))
						accountsBranch.Child(ag_format.Meta("  stakeConfig", inst.AccountMetaSlice.Get(9)))
						accountsBranch.Child(ag_format.Meta(" stakeHistory", inst.AccountMetaSlice.Get(10)))
						accountsBranch.Child(ag_format.Meta(" stakeProgram", inst.AccountMetaSlice.Get(11)))
						accountsBranch.Child(ag_format.Meta("systemProgram", inst.AccountMetaSlice.Get(12)))
					})
				})
		})
}

func (obj Redelegate) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `RedelegateAmount` param:
	err = encoder.Encode(obj.RedelegateAmount)
	if err != nil {
		return err
	}
	return nil
}
func (obj *Redelegate) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `RedelegateAmount`:
	err = decoder.Decode(&obj.RedelegateAmount)
	if err != nil {
		return err
	}
	return nil
}

// NewRedelegateInstruction declares a new Redelegate instruction with the provided parameters and accounts.
func NewRedelegateInstruction(
	// Parameters:
	redelegateAmount uint64,
	// Accounts:
	stakeManager ag_solanago.PublicKey,
	balancer ag_solanago.PublicKey,
	toValidator ag_solanago.PublicKey,
	stakePool ag_solanago.PublicKey,
	fromStakeAccount ag_solanago.PublicKey,
	splitStakeAccount ag_solanago.PublicKey,
	toStakeAccount ag_solanago.PublicKey,
	rentPayer ag_solanago.PublicKey,
	clock ag_solanago.PublicKey,
	stakeConfig ag_solanago.PublicKey,
	stakeHistory ag_solanago.PublicKey,
	stakeProgram ag_solanago.PublicKey,
	systemProgram ag_solanago.PublicKey) *Redelegate {
	return NewRedelegateInstructionBuilder().
		SetRedelegateAmount(redelegateAmount).
		SetStakeManagerAccount(stakeManager).
		SetBalancerAccount(balancer).
		SetToValidatorAccount(toValidator).
		SetStakePoolAccount(stakePool).
		SetFromStakeAccountAccount(fromStakeAccount).
		SetSplitStakeAccountAccount(splitStakeAccount).
		SetToStakeAccountAccount(toStakeAccount).
		SetRentPayerAccount(rentPayer).
		SetClockAccount(clock).
		SetStakeConfigAccount(stakeConfig).
		SetStakeHistoryAccount(stakeHistory).
		SetStakeProgramAccount(stakeProgram).
		SetSystemProgramAccount(systemProgram)
}
