// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package stake_manager

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// SetPlatformStackFeeCommission is the `setPlatformStackFeeCommission` instruction.
type SetPlatformStackFeeCommission struct {
	StackFeeCommission *uint64

	// [0] = [WRITE] stakeManager
	//
	// [1] = [] stack
	//
	// [2] = [SIGNER] admin
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewSetPlatformStackFeeCommissionInstructionBuilder creates a new `SetPlatformStackFeeCommission` instruction builder.
func NewSetPlatformStackFeeCommissionInstructionBuilder() *SetPlatformStackFeeCommission {
	nd := &SetPlatformStackFeeCommission{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 3),
	}
	return nd
}

// SetStackFeeCommission sets the "stackFeeCommission" parameter.
func (inst *SetPlatformStackFeeCommission) SetStackFeeCommission(stackFeeCommission uint64) *SetPlatformStackFeeCommission {
	inst.StackFeeCommission = &stackFeeCommission
	return inst
}

// SetStakeManagerAccount sets the "stakeManager" account.
func (inst *SetPlatformStackFeeCommission) SetStakeManagerAccount(stakeManager ag_solanago.PublicKey) *SetPlatformStackFeeCommission {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(stakeManager).WRITE()
	return inst
}

// GetStakeManagerAccount gets the "stakeManager" account.
func (inst *SetPlatformStackFeeCommission) GetStakeManagerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetStackAccount sets the "stack" account.
func (inst *SetPlatformStackFeeCommission) SetStackAccount(stack ag_solanago.PublicKey) *SetPlatformStackFeeCommission {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(stack)
	return inst
}

// GetStackAccount gets the "stack" account.
func (inst *SetPlatformStackFeeCommission) GetStackAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

// SetAdminAccount sets the "admin" account.
func (inst *SetPlatformStackFeeCommission) SetAdminAccount(admin ag_solanago.PublicKey) *SetPlatformStackFeeCommission {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(admin).SIGNER()
	return inst
}

// GetAdminAccount gets the "admin" account.
func (inst *SetPlatformStackFeeCommission) GetAdminAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(2)
}

func (inst SetPlatformStackFeeCommission) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_SetPlatformStackFeeCommission,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst SetPlatformStackFeeCommission) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *SetPlatformStackFeeCommission) Validate() error {
	// Check whether all (required) parameters are set:
	{
		if inst.StackFeeCommission == nil {
			return errors.New("StackFeeCommission parameter is not set")
		}
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.StakeManager is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.Stack is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.Admin is not set")
		}
	}
	return nil
}

func (inst *SetPlatformStackFeeCommission) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("SetPlatformStackFeeCommission")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=1]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param("StackFeeCommission", *inst.StackFeeCommission))
					})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=3]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("stakeManager", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("       stack", inst.AccountMetaSlice.Get(1)))
						accountsBranch.Child(ag_format.Meta("       admin", inst.AccountMetaSlice.Get(2)))
					})
				})
		})
}

func (obj SetPlatformStackFeeCommission) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `StackFeeCommission` param:
	err = encoder.Encode(obj.StackFeeCommission)
	if err != nil {
		return err
	}
	return nil
}
func (obj *SetPlatformStackFeeCommission) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `StackFeeCommission`:
	err = decoder.Decode(&obj.StackFeeCommission)
	if err != nil {
		return err
	}
	return nil
}

// NewSetPlatformStackFeeCommissionInstruction declares a new SetPlatformStackFeeCommission instruction with the provided parameters and accounts.
func NewSetPlatformStackFeeCommissionInstruction(
	// Parameters:
	stackFeeCommission uint64,
	// Accounts:
	stakeManager ag_solanago.PublicKey,
	stack ag_solanago.PublicKey,
	admin ag_solanago.PublicKey) *SetPlatformStackFeeCommission {
	return NewSetPlatformStackFeeCommissionInstructionBuilder().
		SetStackFeeCommission(stackFeeCommission).
		SetStakeManagerAccount(stakeManager).
		SetStackAccount(stack).
		SetAdminAccount(admin)
}
