// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package stake_manager

import (
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
)

type ConfigStakeManagerParams struct {
	MinStakeAmount        *uint64                `bin:"optional"`
	PlatformFeeCommission *uint64                `bin:"optional"`
	UnbondingDuration     *uint64                `bin:"optional"`
	RateChangeLimit       *uint64                `bin:"optional"`
	Balancer              *ag_solanago.PublicKey `bin:"optional"`
	AddValidator          *ag_solanago.PublicKey `bin:"optional"`
	RemoveValidator       *ag_solanago.PublicKey `bin:"optional"`
}

func (obj ConfigStakeManagerParams) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `MinStakeAmount` param (optional):
	{
		if obj.MinStakeAmount == nil {
			err = encoder.WriteBool(false)
			if err != nil {
				return err
			}
		} else {
			err = encoder.WriteBool(true)
			if err != nil {
				return err
			}
			err = encoder.Encode(obj.MinStakeAmount)
			if err != nil {
				return err
			}
		}
	}
	// Serialize `PlatformFeeCommission` param (optional):
	{
		if obj.PlatformFeeCommission == nil {
			err = encoder.WriteBool(false)
			if err != nil {
				return err
			}
		} else {
			err = encoder.WriteBool(true)
			if err != nil {
				return err
			}
			err = encoder.Encode(obj.PlatformFeeCommission)
			if err != nil {
				return err
			}
		}
	}
	// Serialize `UnbondingDuration` param (optional):
	{
		if obj.UnbondingDuration == nil {
			err = encoder.WriteBool(false)
			if err != nil {
				return err
			}
		} else {
			err = encoder.WriteBool(true)
			if err != nil {
				return err
			}
			err = encoder.Encode(obj.UnbondingDuration)
			if err != nil {
				return err
			}
		}
	}
	// Serialize `RateChangeLimit` param (optional):
	{
		if obj.RateChangeLimit == nil {
			err = encoder.WriteBool(false)
			if err != nil {
				return err
			}
		} else {
			err = encoder.WriteBool(true)
			if err != nil {
				return err
			}
			err = encoder.Encode(obj.RateChangeLimit)
			if err != nil {
				return err
			}
		}
	}
	// Serialize `Balancer` param (optional):
	{
		if obj.Balancer == nil {
			err = encoder.WriteBool(false)
			if err != nil {
				return err
			}
		} else {
			err = encoder.WriteBool(true)
			if err != nil {
				return err
			}
			err = encoder.Encode(obj.Balancer)
			if err != nil {
				return err
			}
		}
	}
	// Serialize `AddValidator` param (optional):
	{
		if obj.AddValidator == nil {
			err = encoder.WriteBool(false)
			if err != nil {
				return err
			}
		} else {
			err = encoder.WriteBool(true)
			if err != nil {
				return err
			}
			err = encoder.Encode(obj.AddValidator)
			if err != nil {
				return err
			}
		}
	}
	// Serialize `RemoveValidator` param (optional):
	{
		if obj.RemoveValidator == nil {
			err = encoder.WriteBool(false)
			if err != nil {
				return err
			}
		} else {
			err = encoder.WriteBool(true)
			if err != nil {
				return err
			}
			err = encoder.Encode(obj.RemoveValidator)
			if err != nil {
				return err
			}
		}
	}
	return nil
}

func (obj *ConfigStakeManagerParams) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `MinStakeAmount` (optional):
	{
		ok, err := decoder.ReadBool()
		if err != nil {
			return err
		}
		if ok {
			err = decoder.Decode(&obj.MinStakeAmount)
			if err != nil {
				return err
			}
		}
	}
	// Deserialize `PlatformFeeCommission` (optional):
	{
		ok, err := decoder.ReadBool()
		if err != nil {
			return err
		}
		if ok {
			err = decoder.Decode(&obj.PlatformFeeCommission)
			if err != nil {
				return err
			}
		}
	}
	// Deserialize `UnbondingDuration` (optional):
	{
		ok, err := decoder.ReadBool()
		if err != nil {
			return err
		}
		if ok {
			err = decoder.Decode(&obj.UnbondingDuration)
			if err != nil {
				return err
			}
		}
	}
	// Deserialize `RateChangeLimit` (optional):
	{
		ok, err := decoder.ReadBool()
		if err != nil {
			return err
		}
		if ok {
			err = decoder.Decode(&obj.RateChangeLimit)
			if err != nil {
				return err
			}
		}
	}
	// Deserialize `Balancer` (optional):
	{
		ok, err := decoder.ReadBool()
		if err != nil {
			return err
		}
		if ok {
			err = decoder.Decode(&obj.Balancer)
			if err != nil {
				return err
			}
		}
	}
	// Deserialize `AddValidator` (optional):
	{
		ok, err := decoder.ReadBool()
		if err != nil {
			return err
		}
		if ok {
			err = decoder.Decode(&obj.AddValidator)
			if err != nil {
				return err
			}
		}
	}
	// Deserialize `RemoveValidator` (optional):
	{
		ok, err := decoder.ReadBool()
		if err != nil {
			return err
		}
		if ok {
			err = decoder.Decode(&obj.RemoveValidator)
			if err != nil {
				return err
			}
		}
	}
	return nil
}

type CreateMetadataParams struct {
	TokenName   string
	TokenSymbol string
	TokenUri    string
}

func (obj CreateMetadataParams) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `TokenName` param:
	err = encoder.Encode(obj.TokenName)
	if err != nil {
		return err
	}
	// Serialize `TokenSymbol` param:
	err = encoder.Encode(obj.TokenSymbol)
	if err != nil {
		return err
	}
	// Serialize `TokenUri` param:
	err = encoder.Encode(obj.TokenUri)
	if err != nil {
		return err
	}
	return nil
}

func (obj *CreateMetadataParams) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `TokenName`:
	err = decoder.Decode(&obj.TokenName)
	if err != nil {
		return err
	}
	// Deserialize `TokenSymbol`:
	err = decoder.Decode(&obj.TokenSymbol)
	if err != nil {
		return err
	}
	// Deserialize `TokenUri`:
	err = decoder.Decode(&obj.TokenUri)
	if err != nil {
		return err
	}
	return nil
}

type EraProcessData struct {
	NeedBond             uint64
	NeedUnbond           uint64
	PendingUnbond        uint64
	OldActive            uint64
	NewActive            uint64
	PendingStakeAccounts []ag_solanago.PublicKey
}

func (obj EraProcessData) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `NeedBond` param:
	err = encoder.Encode(obj.NeedBond)
	if err != nil {
		return err
	}
	// Serialize `NeedUnbond` param:
	err = encoder.Encode(obj.NeedUnbond)
	if err != nil {
		return err
	}
	// Serialize `PendingUnbond` param:
	err = encoder.Encode(obj.PendingUnbond)
	if err != nil {
		return err
	}
	// Serialize `OldActive` param:
	err = encoder.Encode(obj.OldActive)
	if err != nil {
		return err
	}
	// Serialize `NewActive` param:
	err = encoder.Encode(obj.NewActive)
	if err != nil {
		return err
	}
	// Serialize `PendingStakeAccounts` param:
	err = encoder.Encode(obj.PendingStakeAccounts)
	if err != nil {
		return err
	}
	return nil
}

func (obj *EraProcessData) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `NeedBond`:
	err = decoder.Decode(&obj.NeedBond)
	if err != nil {
		return err
	}
	// Deserialize `NeedUnbond`:
	err = decoder.Decode(&obj.NeedUnbond)
	if err != nil {
		return err
	}
	// Deserialize `PendingUnbond`:
	err = decoder.Decode(&obj.PendingUnbond)
	if err != nil {
		return err
	}
	// Deserialize `OldActive`:
	err = decoder.Decode(&obj.OldActive)
	if err != nil {
		return err
	}
	// Deserialize `NewActive`:
	err = decoder.Decode(&obj.NewActive)
	if err != nil {
		return err
	}
	// Deserialize `PendingStakeAccounts`:
	err = decoder.Decode(&obj.PendingStakeAccounts)
	if err != nil {
		return err
	}
	return nil
}

type EraRate struct {
	Era  uint64
	Rate uint64
}

func (obj EraRate) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `Era` param:
	err = encoder.Encode(obj.Era)
	if err != nil {
		return err
	}
	// Serialize `Rate` param:
	err = encoder.Encode(obj.Rate)
	if err != nil {
		return err
	}
	return nil
}

func (obj *EraRate) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `Era`:
	err = decoder.Decode(&obj.Era)
	if err != nil {
		return err
	}
	// Deserialize `Rate`:
	err = decoder.Decode(&obj.Rate)
	if err != nil {
		return err
	}
	return nil
}
