// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package stake_manager

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// Unstake is the `unstake` instruction.
type Unstake struct {
	UnstakeAmount *uint64

	// [0] = [WRITE] stakeManager
	//
	// [1] = [WRITE] lsdTokenMint
	//
	// [2] = [WRITE] burnLsdTokenFrom
	//
	// [3] = [SIGNER] burnLsdTokenAuthority
	//
	// [4] = [WRITE, SIGNER] unstakeAccount
	//
	// [5] = [WRITE, SIGNER] rentPayer
	//
	// [6] = [] systemProgram
	//
	// [7] = [] tokenProgram
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewUnstakeInstructionBuilder creates a new `Unstake` instruction builder.
func NewUnstakeInstructionBuilder() *Unstake {
	nd := &Unstake{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 8),
	}
	return nd
}

// SetUnstakeAmount sets the "unstakeAmount" parameter.
func (inst *Unstake) SetUnstakeAmount(unstakeAmount uint64) *Unstake {
	inst.UnstakeAmount = &unstakeAmount
	return inst
}

// SetStakeManagerAccount sets the "stakeManager" account.
func (inst *Unstake) SetStakeManagerAccount(stakeManager ag_solanago.PublicKey) *Unstake {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(stakeManager).WRITE()
	return inst
}

// GetStakeManagerAccount gets the "stakeManager" account.
func (inst *Unstake) GetStakeManagerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetLsdTokenMintAccount sets the "lsdTokenMint" account.
func (inst *Unstake) SetLsdTokenMintAccount(lsdTokenMint ag_solanago.PublicKey) *Unstake {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(lsdTokenMint).WRITE()
	return inst
}

// GetLsdTokenMintAccount gets the "lsdTokenMint" account.
func (inst *Unstake) GetLsdTokenMintAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

// SetBurnLsdTokenFromAccount sets the "burnLsdTokenFrom" account.
func (inst *Unstake) SetBurnLsdTokenFromAccount(burnLsdTokenFrom ag_solanago.PublicKey) *Unstake {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(burnLsdTokenFrom).WRITE()
	return inst
}

// GetBurnLsdTokenFromAccount gets the "burnLsdTokenFrom" account.
func (inst *Unstake) GetBurnLsdTokenFromAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(2)
}

// SetBurnLsdTokenAuthorityAccount sets the "burnLsdTokenAuthority" account.
func (inst *Unstake) SetBurnLsdTokenAuthorityAccount(burnLsdTokenAuthority ag_solanago.PublicKey) *Unstake {
	inst.AccountMetaSlice[3] = ag_solanago.Meta(burnLsdTokenAuthority).SIGNER()
	return inst
}

// GetBurnLsdTokenAuthorityAccount gets the "burnLsdTokenAuthority" account.
func (inst *Unstake) GetBurnLsdTokenAuthorityAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(3)
}

// SetUnstakeAccountAccount sets the "unstakeAccount" account.
func (inst *Unstake) SetUnstakeAccountAccount(unstakeAccount ag_solanago.PublicKey) *Unstake {
	inst.AccountMetaSlice[4] = ag_solanago.Meta(unstakeAccount).WRITE().SIGNER()
	return inst
}

// GetUnstakeAccountAccount gets the "unstakeAccount" account.
func (inst *Unstake) GetUnstakeAccountAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(4)
}

// SetRentPayerAccount sets the "rentPayer" account.
func (inst *Unstake) SetRentPayerAccount(rentPayer ag_solanago.PublicKey) *Unstake {
	inst.AccountMetaSlice[5] = ag_solanago.Meta(rentPayer).WRITE().SIGNER()
	return inst
}

// GetRentPayerAccount gets the "rentPayer" account.
func (inst *Unstake) GetRentPayerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(5)
}

// SetSystemProgramAccount sets the "systemProgram" account.
func (inst *Unstake) SetSystemProgramAccount(systemProgram ag_solanago.PublicKey) *Unstake {
	inst.AccountMetaSlice[6] = ag_solanago.Meta(systemProgram)
	return inst
}

// GetSystemProgramAccount gets the "systemProgram" account.
func (inst *Unstake) GetSystemProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(6)
}

// SetTokenProgramAccount sets the "tokenProgram" account.
func (inst *Unstake) SetTokenProgramAccount(tokenProgram ag_solanago.PublicKey) *Unstake {
	inst.AccountMetaSlice[7] = ag_solanago.Meta(tokenProgram)
	return inst
}

// GetTokenProgramAccount gets the "tokenProgram" account.
func (inst *Unstake) GetTokenProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(7)
}

func (inst Unstake) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_Unstake,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst Unstake) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *Unstake) Validate() error {
	// Check whether all (required) parameters are set:
	{
		if inst.UnstakeAmount == nil {
			return errors.New("UnstakeAmount parameter is not set")
		}
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.StakeManager is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.LsdTokenMint is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.BurnLsdTokenFrom is not set")
		}
		if inst.AccountMetaSlice[3] == nil {
			return errors.New("accounts.BurnLsdTokenAuthority is not set")
		}
		if inst.AccountMetaSlice[4] == nil {
			return errors.New("accounts.UnstakeAccount is not set")
		}
		if inst.AccountMetaSlice[5] == nil {
			return errors.New("accounts.RentPayer is not set")
		}
		if inst.AccountMetaSlice[6] == nil {
			return errors.New("accounts.SystemProgram is not set")
		}
		if inst.AccountMetaSlice[7] == nil {
			return errors.New("accounts.TokenProgram is not set")
		}
	}
	return nil
}

func (inst *Unstake) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("Unstake")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=1]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param("UnstakeAmount", *inst.UnstakeAmount))
					})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=8]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("         stakeManager", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("         lsdTokenMint", inst.AccountMetaSlice.Get(1)))
						accountsBranch.Child(ag_format.Meta("     burnLsdTokenFrom", inst.AccountMetaSlice.Get(2)))
						accountsBranch.Child(ag_format.Meta("burnLsdTokenAuthority", inst.AccountMetaSlice.Get(3)))
						accountsBranch.Child(ag_format.Meta("              unstake", inst.AccountMetaSlice.Get(4)))
						accountsBranch.Child(ag_format.Meta("            rentPayer", inst.AccountMetaSlice.Get(5)))
						accountsBranch.Child(ag_format.Meta("        systemProgram", inst.AccountMetaSlice.Get(6)))
						accountsBranch.Child(ag_format.Meta("         tokenProgram", inst.AccountMetaSlice.Get(7)))
					})
				})
		})
}

func (obj Unstake) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `UnstakeAmount` param:
	err = encoder.Encode(obj.UnstakeAmount)
	if err != nil {
		return err
	}
	return nil
}
func (obj *Unstake) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `UnstakeAmount`:
	err = decoder.Decode(&obj.UnstakeAmount)
	if err != nil {
		return err
	}
	return nil
}

// NewUnstakeInstruction declares a new Unstake instruction with the provided parameters and accounts.
func NewUnstakeInstruction(
	// Parameters:
	unstakeAmount uint64,
	// Accounts:
	stakeManager ag_solanago.PublicKey,
	lsdTokenMint ag_solanago.PublicKey,
	burnLsdTokenFrom ag_solanago.PublicKey,
	burnLsdTokenAuthority ag_solanago.PublicKey,
	unstakeAccount ag_solanago.PublicKey,
	rentPayer ag_solanago.PublicKey,
	systemProgram ag_solanago.PublicKey,
	tokenProgram ag_solanago.PublicKey) *Unstake {
	return NewUnstakeInstructionBuilder().
		SetUnstakeAmount(unstakeAmount).
		SetStakeManagerAccount(stakeManager).
		SetLsdTokenMintAccount(lsdTokenMint).
		SetBurnLsdTokenFromAccount(burnLsdTokenFrom).
		SetBurnLsdTokenAuthorityAccount(burnLsdTokenAuthority).
		SetUnstakeAccountAccount(unstakeAccount).
		SetRentPayerAccount(rentPayer).
		SetSystemProgramAccount(systemProgram).
		SetTokenProgramAccount(tokenProgram)
}
